### ISSUE TITLE
[CX-84] bug: Traffic table network logs when pause, auto resumes.

### ISSUE THREAD

**Issue by rohanmathur91** [requestly/requestly#1007]
### Describe your issue?

When I press "pause" in the Network traffic tab, and then I switch to HTTP Rules tab, traffic log resumes automatically.

### Repro steps

1. Go network traffic table and connect any app.
2. Pause the logs and navigate to `HTTP Rules`.
3. Navigate back to the traffic table.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac OS

### Requestly Version

1.5.10

<sub>[CX-84](https://linear.app/requestly/issue/CX-84/bug-traffic-table-network-logs-when-pause-auto-resumes)</sub>

**Comment by contact-requestly** [comment]
TEST1

**Comment by wrongsahil** [comment]
TEST2

**Comment by wrongsahil** [comment]
@nsrCodes fixed this issue
