### ISSUE TITLE
Please consider adding a note to the readme to clarify that all data is processed locally

### ISSUE THREAD

**Issue by Dameck** [requestly/requestly#1012]
I'm missing the information that no requests/data from Requestly leave the app and are sent via a cloud. I didn't find anything in the code that indicates data leaving the app at first glance. Perhaps this information, stating that Requestly operates entirely locally, should be included in the FAQ/Readme.

**Comment by sagarsoni7** [comment]
Thanks @Dameck ! This is a really good suggestion
