### ISSUE TITLE
Export recording in JSON or CSV

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#1036]
Intent is to capture the steps performed in the recording. This should serve as an input to UI automation.

Requested by:
[Manoj Vysyaraju](https://www.linkedin.com/in/vysyarajusaimanoj/)

**Comment by contact-requestly** [comment]
We already support exporting recordings as JSON. This is saved as `.rqly` file but it is actually a json

![image](https://github.com/requestly/requestly/assets/126000930/75e42484-52a5-4098-be81-aff5d5c9268a)
