### ISSUE TITLE
[CX-90] Enable developers to configure request/response override rules directly from network traffic in chrome devtools 

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#1043]
Currently, users go to [the Requestly dashboard](https://app.requestly.io/rules) to set up HTTP traffic modification rules. Requestly offers the following modification rules
- Modify HTTP Request & Response Headers
- Modify API request body
- Modify API response body & status code
- URL Redirects
- Script Injection

Requestly desktop app provides a much more convenient and better user experience for setting up the rules directly from network traffic as communicated in this [tweet here](https://twitter.com/RequestlyIO/status/1656537017197666307)

The idea is to provide a similar experience where developers/QAs inspect the traffic of a website do a right click and set up the rules easily. It is fine to then go to the dashboard to manage the rules and activate and deactivate them.

Right now, Requestly devTools in Chrome only shows the logs of whether a rule is run on the page or not.  If we can use the existing network tab, its ideal. If not, Extend the devtools to show network traffic and the ability to configure rules.

<sub>[CX-90](https://linear.app/requestly/issue/CX-90/enable-developers-to-configure-requestresponse-override-rules-directly)</sub>

**Comment by sachinjain024** [comment]
We are already live with v0 of the Devtools panel but it doesn't support showing & overriding of request & response body. For versions greater than v23.8.25, this panel should be available which can be used to inspect the network traffic and setup rules to modify HTTP headers, inject scripts, and URL redirects.

This devtools panel also shows the executed rules as shown on the left side.

![Requestly product screenshots (2)](https://github.com/requestly/requestly/assets/3108399/dbcec8ef-da04-4b01-8143-6417618b7522)

**Comment by sachinjain024** [comment]
We're almost done with adding support for previewing request payload and response body in Requestly developer tools. Here's a quick video of how it will look like 👇

https://www.youtube.com/watch?v=VG_r4PBvQKI

**Comment by wrongsahil** [comment]
Released in version v23.9.20
