### ISSUE TITLE
[CX-93] bug: Formatting bug

### ISSUE THREAD

**Issue by diogobcondeco** [requestly/requestly#1049]
### Describe your issue?

I was editing my modified response json and whenever I wrote a single character it formatted all the json from the prettier version to the raw version.

I formatted it with prettier again and it just keeps happening...

The only solution I found was to simply copy my json to VSCode and make the changes there and put it back in Requestly... it just feels extremely annoying, sometimes I just want to change a true to false and I have to do all this process.

### Repro steps

1 - edit a response json (I'm using a long json)
2 - have the json formatted with prettier
3 - write a few characters and it will reformat to the raw version

### What Requestly tool were you using?

- [X] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome 116

### Requestly Version

v23.9.2

<sub>[CX-93](https://linear.app/requestly/issue/CX-93/bug-formatting-bug)</sub>

**Comment by nafees87n** [comment]
Hey @diogobcondeco thanks for logging this issue. We will try to fix this as soon as possible
