### ISSUE TITLE
Password support in Mock Server

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#1050]
For security reasons, i want the mock server to be accessible only if the user send password along with the request.

Password can be sent in multiple ways
- Query Param - `https://username.requestly.dev/users?x-password=1234`
- Header - `x-password: 1234`

**Comment by CodHeK** [comment]
@wrongsahil sounds good. I'm thinking of having it in the `headers`, hope that's okay? Another thing, we'd probably need a way to enter passwords for each route right? Can I get some help around the UI for that please?

**Comment by wrongsahil** [comment]
@CodHeK I think se should keep it in query params right now as Requestly Cloud Mock Server lets you copy the URL. So ideally users assume that the password is already copied along with the URL

1. We can work on the backend for now and keep harcoded values in the dummy mocks. After this, you can start working on the UI for this too.
2. We should add these validations on the UI only while creating the mock. Not in the server. But lets use the basic validations in the UI (min 8 characters, only alphabets and numbers as they don't get encoded in the url).

**Comment by CodHeK** [comment]
Got it. Done. Opened up a pull request [here](https://github.com/requestly/requestly-mock-server/pull/3)

**Comment by CodHeK** [comment]
@wrongsahil Adding the workflow for creating a password [here](https://github.com/requestly/requestly/pull/1107). Could you please take a look once, if it looks fine?

**Comment by wrongsahil** [comment]
Supported in Mock Server now
![CleanShot 2024-07-16 at 10 38 10](https://github.com/user-attachments/assets/6efefa91-e196-48ad-86d0-c46beccde8ae)
