### ISSUE TITLE
Remove the option for import settings from Charles from the main import flow in web app

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#1127]
- [ ] "Import from Charles" option is to be removed from the existing workflow. On import, the user should be taken to the parser modal directly. Desktop app flow should remain the same.
<img src="https://github.com/requestly/requestly/assets/16779465/92410f24-c57e-4458-b89a-1632d981b5c0" width=400 />

- [ ] Further, host "Import from Charles" on a new route.
- [ ] Documentation to be updated as per the new flow.

**Comment by echo-sg** [comment]
Closing this as this is completed.
