### ISSUE TITLE
Show "Show More" in the Response/Request Editor in Devtools when body is larger than 500KB

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#1130]
**Why**
To improve the performance of rendering Response/Request Body in devtools, we should show `Show More` in the Body. 

Similar Experience
- Requestly Desktop App
<img width="566" alt="image" src="https://github.com/requestly/requestly/assets/16779465/c952f213-9cab-4f13-a982-d8f320daaca6">

**Comment by sagarsoni7** [comment]
fixed by https://github.com/requestly/requestly/pull/1915
