### ISSUE TITLE
[RQ-690] enhancement: Remove <script> tag from Insert Script Rule if present 

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#1133]
**Why**
Since the rules is insert script, users normally think that <script> tags are also needed. Due to which rules break

**What**
Remove <script> tag from starting and ending of Insert Script Rule if present

**Comment by VDisawal** [comment]
Hey @echo-sg !
I would love to work on this.

I've done some initial analysis and can think of 3 ways to deal with this-
1) As soon as we see leading/trailing script tags on the code editor we can just remove them in-place. This way the user would automatically understand that the script tags are'nt needed. For this, the change is pretty simple. We would need to make edits on this component (`app/src/components/features/rules/RulePairs/Pairs/Rows/RowsMarkup/CustomScriptRow/index.js`). We would add the necessary checks for script tag on the `scriptBodyChangeHandler` method. 
2) We could let the user add the code with the tag, and then we can handle the removal of the script tag on click of the save button. This can be done on the `runMinorFixesOnRule` method in `app/src/utils/rules/misc.js` or any other place in `handleBtnOnClick` method in `app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/index.js`
3) Throw a validation error on click of save, in case the code editor has the script tags. This can be easily done in the `validateRule` method in `app/src/components/features/rules/RuleBuilder/Header/ActionButtons/CreateRuleButton/actions/index.js`

Kindly let me know if any of these options seem suitable, or if you have a better alternative in mind.

Thanks!

**Comment by disawalva** [comment]
Hi @wrongsahil @echo-sg !
Can I work on this?
If so, can you please let me know if any of the aforementioned approaches are good enough?

Eagerly waiting for your reply.

Thanks!

**Comment by VDisawal** [comment]
Hey @wrongsahil @echo-sg !
Can I work on this?
If so, can you please let me know if any of the aforementioned approaches are good enough?

Eagerly waiting for your reply.

Thanks!

**Comment by VDisawal** [comment]
Hey @wrongsahil @echo-sg ! It would be great if you could guide me on the same.
Eagerly waiting for your reply.

**Comment by sagarsoni7** [comment]
Thanks @VDisawal ! Your second approach sounds the best.
I think @nsrCodes can work on this since he holds the most context. Could you help in PR review?

**Comment by VDisawal** [comment]
Hey @sagarsoni7 ! 
I am not sure if I would be of much help in the code review given that I am new to the project.
However, if you think that would be better (than submitting the PR) I am open to it.
Thanks!

**Comment by VDisawal** [comment]
Hey @sagarsoni7! Would it be fine if I raise the PR?

**Comment by sagarsoni7** [comment]
Hi @VDisawal, we've decided to handle this project in-house due to limited bandwidth. We appreciate your offer to contribute and hope to collaborate in the future. Thanks for your understanding
