### ISSUE TITLE
[CX-121] how do i copy the fetch of a request i can only copy the curl and the url?

### ISSUE THREAD

**Issue by phillipbruh** [requestly/requestly#1157]
how do i copy the fetch of a request i can only copy the curl and the url

i could not post on the questions so i posted it here

<sub>[CX-121](https://linear.app/requestly/issue/CX-121/how-do-i-copy-the-fetch-of-a-request-i-can-only-copy-the-curl-and-the)</sub>

**Comment by nsrCodes** [comment]
Hey @phillipbruh 
This is currently not directly possible inside the app. We have logged this internally as a feature request and will let you know once we this is available.

Meanwhile, you can use tools like [curlconverter](https://curlconverter.com/javascript/) to generate the `fetch` equivalent of the copied curl

**Comment by phillipbruh** [comment]
yes I did that thanks

**Comment by phillipbruh** [comment]
thank you for making this software btw its one of the best tools i have
