### ISSUE TITLE
bug: YouTube chat doesn't work when Requestly is on

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#1204]
### Describe your issue?

when the extension works on live broadcasts on YouTube, the chat does not work, it is impossible to write a message in it, you have to turn it off requestly runnig although I don’t have any rules for YouTube

### Repro steps

No rules just extension activated.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome on Windows

### Requestly Version

23.10.22

**Comment by sachinjain024** [comment]
@nafees87n Could you please check if this is still an issue?

**Comment by nsrCodes** [comment]
Verified this is no longer an issue on the extension, but this fails for the desktop app. Will create a separate issue for that
