### ISSUE TITLE
bug: can't login

### ISSUE THREAD

**Issue by oceanim** [requestly/requestly#1218]
### Describe your issue?

When I login success, tips success. but the login dialog didn't closed. I closed dialog, stay in the not logged in state.
It doesn't work in desktop applications either.

```
POST https://us-central1-project-7820168409702389920.cloudfunctions.net/getEnterpriseAdminDetails net::ERR_CONNECTION_CLOSED
(anonymous) @ main.b9a3ce8b.js:6724
(anonymous) @ main.b9a3ce8b.js:2
In @ main.b9a3ce8b.js:2
SZt @ main.b9a3ce8b.js:6724
(anonymous) @ main.b9a3ce8b.js:6724
k @ main.b9a3ce8b.js:2
Promise.then (async)
S @ main.b9a3ce8b.js:2
(anonymous) @ main.b9a3ce8b.js:2
In @ main.b9a3ce8b.js:2
CIe @ main.b9a3ce8b.js:6724
wZt @ main.b9a3ce8b.js:6724
(anonymous) @ main.b9a3ce8b.js:6724
(anonymous) @ main.b9a3ce8b.js:7435
(anonymous) @ main.b9a3ce8b.js:7435
wQn @ main.b9a3ce8b.js:7435
(anonymous) @ main.b9a3ce8b.js:7435
(anonymous) @ main.b9a3ce8b.js:1680
Promise.then (async)
registerStateListener @ main.b9a3ce8b.js:1680
onAuthStateChanged @ main.b9a3ce8b.js:1680
HZ @ main.b9a3ce8b.js:2295
(anonymous) @ main.b9a3ce8b.js:7435
Oi @ main.b9a3ce8b.js:377
L5 @ main.b9a3ce8b.js:377
mC @ main.b9a3ce8b.js:377
i6 @ main.b9a3ce8b.js:377
t6 @ main.b9a3ce8b.js:377
Em @ main.b9a3ce8b.js:375
mC @ main.b9a3ce8b.js:377
i6 @ main.b9a3ce8b.js:377
Np @ main.b9a3ce8b.js:377
ce @ main.b9a3ce8b.js:533
We @ main.b9a3ce8b.js:533
main.b9a3ce8b.js:2760
```

```
Cross-Origin-Opener-Policy policy would block the window.close call.
close @ main.b9a3ce8b.js:2760
```

### Repro steps

Sign in with Google

### What Requestly tool were you using?

- [X] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

119.0.6045.123

### Requestly Version

23.11.8

### Error screenshot

![image](https://github.com/requestly/requestly/assets/74701401/dc02d9d1-e828-47a6-85c4-2e0343cc063a)

**Comment by sagarsoni7** [comment]
Thanks for logging this issue. There seemed to be an outage at the Firebase/GCP’s end. Are you able to login now?

**Comment by sagarsoni7** [comment]
https://status.firebase.google.com/incidents/JH8hiSsfnSZHMdZqFTaC

**Comment by oceanim** [comment]
> Thanks for logging this issue. There seemed to be an outage at the Firebase/GCP’s end. Are you able to login now?
I'm still not able to log in.

**Comment by JiangJiangYo** [comment]
> > Thanks for logging this issue. There seemed to be an outage at the Firebase/GCP’s end. Are you able to login now?
> > I'm still not able to log in.
我 也遇到 跟你一样的问题 , 这个问题发生了很长时间了  为什么到险遭都没解决呢 , 这么大的一个用户量 我希望尽早能解决这个问题 , 我的数据 已经全部丢失 这让我对这个插件很失望 我已经在Google插件市场中反馈了这个问题了
