### ISSUE TITLE
bug: Connect Apps - Safari not working on Sonoma

### ISSUE THREAD

**Issue by StefanWrightGlassbox** [requestly/requestly#1224]
### Describe your issue?

Recently I tried using Requestly to launch an instance of Safari (I had no other instances of Safari open), upon opening though I proceeded to the amiusing page and it reported I was NOT going via Requestly.
I spoke with the live chat about this, I was not using a VPN at the time either before or after choosing to run Safari)

During the live chat I did find the following:
When I stopped using the Safari option from the ConnectApps and just set the system proxy to go through the Requestly port and the site is loading for me now that I want to intercept (or at least I see them in the Network Traffic tab)

The workaround was not perfect though as I encountered certificate errors, raising this as a new item though

### Repro steps

1. Open Requestly
2. Fron Network Traffic click Connect apps
3. Choose "Safari New profile"
4. Go to http://amiusing.requestly.io, you will get redirected to HTTPS anyway
5. You'll see Failure on screen
6. Try any ther website
7. You'll see nothing in the Network Traffic screen in Requestly.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS Sonoma

### Requestly Version

v1.5.12

**Comment by nsrCodes** [comment]
A fix has been released for this in [v1.5.13](https://github.com/requestly/requestly-desktop-app/releases/tag/v1.5.13)

The underlying issue for this is the same as https://github.com/requestly/requestly/issues/1225
So closing this as a duplicate for now
