### ISSUE TITLE
how to change proxy ip

### ISSUE THREAD

**Issue by meiguiyisenluo** [requestly/requestly#1229]
### Describe your issue?

it start proxy on 172.xx.xxx.x, it's my wsl ip ,but I want to proxy on my wlan 192.168.xx.xx.

### Repro steps

1. open requestly app
2. proxy on 172.xx.xxx.x, I can't access http://requestly.io to get the certificate on mobile device.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows11 23h2

### Requestly Version

I can't find the version

**Comment by nsrCodes** [comment]
Hey @meiguiyisenluo 
Can you explain how you got it to run on WSL ?

By default, it runs on your default internet network.

**Comment by meiguiyisenluo** [comment]
> Hey @meiguiyisenluo Can you explain how you got it to run on WSL ?
> 
> By default, it runs on your default internet network.

I just double click the Requestly desktop shortcut to open it ,its default proxy on my wsl ip. I run command ipconfig, the order of network adapters is ...wsl...wlan, maybe its related.

 I just tried again, but my wsl ip was gone  and  Requestly work successfully.

**Comment by meiguiyisenluo** [comment]
![image](https://github.com/requestly/requestly/assets/52649954/03cb657f-4fc6-46b2-b377-53a335744b57)
this can change the network priority，less of the number ,higher of the priority.

**Comment by nsrCodes** [comment]
Thanks for sharing your fix @meiguiyisenluo 
We haven't been able to validate this solution ourselves but feel free to reopen the issue incase this doesn't work.
