### ISSUE TITLE
bug: Long response body is being dropped when saving session

### ISSUE THREAD

**Issue by LievenAudenaeren** [requestly/requestly#1252]
### Describe your issue?

When recording a session and saving it for later use, the response body of certain calls is `null` when opening it up again. This is the case for Content-Type `application/json; charset=utf-8`. This also seems to be happening when downloading it to a .har file format.

### Repro steps

Repro steps:

1. Start a recording session that receives some larger responses with Content-Type `application/json; charset=utf-8`
2. Save the session for later use or Download it to a .har file
3. Open the session again
4. Check the responses containing the json content, it shows up as `null` instead of showing the actual response content.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows

### Requestly Version

v1.5.11

**Comment by nsrCodes** [comment]
Thanks for raising the issue, recent changes to persist logs moved their responses to a different location in state, the corresponding changes for log exporters were missed. 
A fix will be released soon.

**Comment by LievenAudenaeren** [comment]
Thanks for addressing this so soon!

**Comment by sachinjain024** [comment]
@nsrCodes Is this released?

**Comment by nsrCodes** [comment]
Yes @sachinjain024 this was released then itself. So closing this now.
