### ISSUE TITLE
Feature Request - Allow Overriding Response Status Code in Modify Response Rule

### ISSUE THREAD

**Issue by kirBMSTU** [requestly/requestly#128]
Is it possible to replace the response status? This is the only thing missing in the extension

**Comment by theinfin8y** [comment]
@kirBMSTU Are you trying to replace the response status of an XHR request?

**Comment by kirBMSTU** [comment]
> @kirBMSTU Are you trying to replace the response status of an XHR request?

yes, but i think it can be useful for fetch too

**Comment by theinfin8y** [comment]
Thanks @kirBMSTU We are taking this as a feature request. Right now, we don't support modifying the status code. Adding this to roadmap.

**Comment by kirBMSTU** [comment]
> Thanks @kirBMSTU We are taking this as a feature request. Right now, we don't support modifying the status code. Adding this to roadmap.

Thanks!

**Comment by laygir** [comment]
Hey hey 👋 

Is there any progress on this one? This is definitely the only thing missing in the extension!

**Comment by nafees87n** [comment]
Hey @kirBMSTU @laygir 
We don't support overriding response code in modify response rule as of now but this workaround might work.
We support creation of Mock APIs which can be used to create a mock API with the desired response status code. This mock API can then be set up in a redirect rule to redirect the actual site to this API to get the desired response status code.
Visit: https://app.requestly.io/mock-server

Let us know if this fits your use case.

**Comment by sachinjain024** [comment]
Reopening this as we are starting to work on this now.
