### ISSUE TITLE
Can it support response rewriting for other request types, such as html and javascript?

### ISSUE THREAD

**Issue by Xeikim** [requestly/requestly#1280]
Can it support response rewriting for other request types, such as html and javascript, which is very common in network packet capture?

**Comment by sagarsoni7** [comment]
The extension can't override response of HTML or JS but you can use the [desktop app](https://requestly.io/desktop) for this.

Alternatively, you can use [Mock Server](https://app.requestly.io/mock-server/) to host your rewritten file and create [Redirect Rules](https://requestly.io/products/web-debugger/redirect-urls/) accordingly.

Let me know if helps.

Relevant docs:

- https://developers.requestly.io/mock-server/overview/
- https://developers.requestly.io/http-rules/map-local-url-redirect/
- https://developers.requestly.io/installation/desktop-app/
