### ISSUE TITLE
bug: Unable to download Requestly Desktop for Apple Silicon - Page getting timed out

### ISSUE THREAD

**Issue by bkannanv1** [requestly/requestly#1283]
### Describe your issue?

Unable to download the Requestly Desktop App for Apple Silicon - https://requestly.io/downloads/

Please refer to the issue here - https://github.com/requestly/requestly-desktop-app/issues/64

### Repro steps

1. Navigate to https://requestly.io/downloads/
2. Hit the download link for Apple silicon

Expected: Should be able to download the Application
Actual: Page getting timed out

![image](https://github.com/requestly/requestly/assets/128489265/3cac408c-ce45-41f7-8385-ce8eb5c01b84)

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

N/A

### Error screenshot

![image](https://github.com/requestly/requestly/assets/128489265/fb4e49db-58d0-4404-aee5-c0f98a3a00e6)

**Comment by echo-sg** [comment]
Hey @bkannanv1 
Thanks for raising this issue, we are looking into it on priority.

**Comment by sagarsoni7** [comment]
The links have been fixed. Please feel free to reopen in case if the issue appears again.
