### ISSUE TITLE
Core features going premium

### ISSUE THREAD

**Issue by SoCuul** [requestly/requestly#1285]
I've loved using requestly for personal development projects, but the premium-restricting of features has severely limited my ability to use it. I heavily relied on the "modify response" rule which is now behind a paywall, which restricts my ability to use the extension for any of my work.

**Comment by sachinjain024** [comment]
I appreciate your kind words and your taking the time to open this ticket. Requestly is open-source so if you need the premium features you can build the extension from the source code. Hope it helps!

**Comment by SoCuul** [comment]
Thank you for replying! Do you have any pointers on which files manage the subscription connectivity?

**Comment by sachinjain024** [comment]
Limits are added only in the cloud version that you install from the Chrome Store. If you build the extension yourself, all the core features will be available except collaboration features.

**Comment by SoCuul** [comment]
> Limits are added only in the cloud version that you install from the Chrome Store. If you build the extension yourself, all the core features will be available except collaboration features.

Oh ok. Thank you so much! Is the manifest V3 version the recommended one to use?

**Comment by sachinjain024** [comment]
No, We did the manifest v3 implementation. It doesn't have all the features right now, feel free to build that and use it. Otherwise build from this repo only.

**Comment by sachinjain024** [comment]
If you want, you can also build desktop app from requestly/desktop-app repo and use it.

**Comment by SoCuul** [comment]
Sounds good. Thank you so much for your help with this!
