### ISSUE TITLE
bug: Cannot read properties of undefined (reading 'length') when testing a Replace String rule

### ISSUE THREAD

**Issue by github-account1111** [requestly/requestly#1290]
### Describe your issue?

I was trying to exclude URLs containing certain words from being processed by the rules. E.g. process everything with "reddit" unless it contains "submit." Since there isn't an "`unless`" statement (please correct me if I'm wrong) I tried using a regex lookaround but that results in the following error:

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at https://app.requestly.io/static/js/main.23bd6698.js:7464:70744
    at Array.map ()
    at https://app.requestly.io/static/js/main.23bd6698.js:7464:70560
    at F5r (https://app.requestly.io/static/js/main.23bd6698.js:7464:73593)
    at Ee (https://app.requestly.io/static/js/main.23bd6698.js:375:20903)
    at Ei (https://app.requestly.io/static/js/main.23bd6698.js:377:3324)
    at rE (https://app.requestly.io/static/js/main.23bd6698.js:377:47328)
    at zO (https://app.requestly.io/static/js/main.23bd6698.js:377:42022)
    at ZO (https://app.requestly.io/static/js/main.23bd6698.js:377:41950)
    at nE (https://app.requestly.io/static/js/main.23bd6698.js:377:41800)
    at Fb (https://app.requestly.io/static/js/main.23bd6698.js:377:37961)
    at kf (https://app.requestly.io/static/js/main.23bd6698.js:377:36851)
    at ce (https://app.requestly.io/static/js/main.23bd6698.js:533:1674)
    at MessagePort.Ge (https://app.requestly.io/static/js/main.23bd6698.js:533:2065)
```

### Repro steps

1. Go to [https://app.requestly.io/rules/editor/edit/Replace_4l72c](https://app.requestly.io/rules/editor/edit/Replace_4l72c)
2. Create the following Replace String rule:
   * If request
   * URL
   * RegEx
   * `/^https:\/\/www\.reddit\.com\/r\/.*\/((?!submit).)*/`
3. Test the rule using [https://www.reddit.com/r/pics/submit/](https://www.reddit.com/r/pics/submit/). As soon as I paste the URL the page crashes.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 10, Edge 120.0.2210.77

### Requestly Version

23\.11.8

### Error screenshot

![image](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/c0b7e7b5-5628-40ee-8666-de77a5ebf1bc/a4a4d2b3-0762-4a4b-a456-47f3e7285111?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9jMGI3ZTdiNS01NjI4LTQwZWUtODY2Ni1kZTc3YTVlYmYxYmMvYTRhNGQyYjMtMDc2Mi00YTRiLWE0NTYtNDdmM2U3Mjg1MTExIiwiaWF0IjoxNzAzNjUxNTg0LCJleHAiOjMzMjc0MjExNTg0fQ.SP94cnT0WtLV9w-i9vW6gJmdw6cWbaYSQQ2KoPJ-EYI)

![image](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/a4500420-a017-48b0-8eb4-f3ed62893ec5/f6a2cfbe-17b2-4e62-9cc5-347aa6d78ef3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9hNDUwMDQyMC1hMDE3LTQ4YjAtOGViNC1mM2VkNjI4OTNlYzUvZjZhMmNmYmUtMTdiMi00ZTYyLTljYzUtMzQ3YWE2ZDc4ZWYzIiwiaWF0IjoxNzAzNjUxNTg0LCJleHAiOjMzMjc0MjExNTg0fQ.KsVcJsSODOPzCUE2s83xiNbza_G2oCX_Qpllg89ZOg4)

**Comment by nafees87n** [comment]
Hi
Thanks for reporting this issue. We are trying to reproduce this. 
You correctly mentioned that, regex needs to be used for this. Let me share a rule with you for this use case

**Comment by nafees87n** [comment]
You can use the following regex for this:
<img width="765" alt="Screenshot 2023-12-22 at 12 12 53 PM" src="https://github.com/requestly/requestly/assets/56021937/b4cc851f-e7b4-49ef-9bd2-4749cf4035f6">
Here's a sharedlist for the same: https://app.requestly.io/rules#sharedList/1703227341465-reddit-negative-filter

You can also use this workaround when using negative filters: https://superuser.com/questions/1473199/how-to-implement-does-not-contain-or-negative-filter-in-requestly

**Comment by DarkWolff71** [comment]
@nafees87n 
Is the issue reproducible? I've tried with edge browser and it is working fine. 
If the issue still persists, I'll be happy to work on it.
