### ISSUE TITLE
bug: Navbar Element Get Remove When Window Size Get Reduce To 1150 to 1030

### ISSUE THREAD

**Issue by Chetax** [requestly/requestly#1301]
### Describe your issue?

bug: Navbar Element Get Remove When Window Size Get Reduce To 1150 to 1030

### Repro steps

\-Open [https://requestly.io/](https://requestly.io/) Site.
\-Open Developer tool (ctrl + shift+ i)
\-decrease size to 1122px than we can see search icon get remove
\-decrease size to 1032px than we can see Add to chrome button get outside the boundary

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome

### Requestly Version

120\.0.6099.129/130 / 20 December 2023 version for windows

### Error screenshot

![Screenshot 2023-12-27 173637](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/fec1c7f6-3932-43ba-81d7-1b05105ca372/2665d451-8475-42d1-a11f-2abcccea0e17?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9mZWMxYzdmNi0zOTMyLTQzYmEtODFkNy0xYjA1MTA1Y2EzNzIvMjY2NWQ0NTEtODQ3NS00MmQxLWExMWYtMmFiY2NjZWEwZTE3IiwiaWF0IjoxNzA0ODgyNzcxLCJleHAiOjMzMjc1NDQyNzcxfQ.orymgFcjCtrxKSFvQdJh7LXkWlS45gldH3LIdZlZ3cc)

![Screenshot 2023-12-27 173647](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/89822735-6765-481e-b27b-a6259658204b/b16aabf8-f1ef-4b44-8448-b631322d4359?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi84OTgyMjczNS02NzY1LTQ4MWUtYjI3Yi1hNjI1OTY1ODIwNGIvYjE2YWFiZjgtZjFlZi00YjQ0LTg0NDgtYjYzMTMyMmQ0MzU5IiwiaWF0IjoxNzA0ODgyNzcxLCJleHAiOjMzMjc1NDQyNzcxfQ.kI7pr15dIcA3iFQ3i1XQoYBFtr7hWpdXOXi5GGfUysU)

**Comment by Chetax** [comment]
@wrongsahil assign this issue to me .

**Comment by sagarsoni7** [comment]
Thanks for logging this issue @Chetax 
This page is powered by Wordpress and access for now is internal only
