### ISSUE TITLE
🔯 Intercept/filter request based on its payload and modify the request payload (GraphQL-related)

### ISSUE THREAD

**Issue by dwiyatci** [requestly/requestly#133]
Hi! 👋 I have a use case where I need to intercept a GraphQL HTTP request and modify/mock either the request or the response. The way to filter or distinguish a GraphQL request in general is to look at the `operationName` field in the request payload (as GraphQL requests usually go to the same API endpoint: `/graphql`).

To mock the response, I'm currently able to workaround it by using the beta feature of "Modify using JavaScript":
![app requestly io_rules_editor_edit_Response_4qf28](https://user-images.githubusercontent.com/4405796/130454224-b1ddccff-7200-4132-8b51-f55e5cea670c.png)

However, to mock the request, I believe I need two things:
1. **The ability to intercept/filter a request based on its payload** (content). I know that right now we can only filter by page URL, resource type, and request method (https://docs.requestly.io/using-rules/source-filters).
2. **The ability to modify the request payload** based on the filter set in point 1.

Will Requestly be able to add these two features in the future?

Thanks, very much.

**Comment by theinfin8y** [comment]
Hey @dwiyatci Thank you so much for opening this ticket. Glad to know that you are able to use `Modify Using JS` feature. @lazyvab Can we investigate if we can also override the XHR request payload and modify it before sending it to the server.

**Comment by dwiyatci** [comment]
comment_to_remove_stale

**Comment by dwiyatci** [comment]
comment_to_remove_stale

**Comment by dwiyatci** [comment]
comment_to_remove_stale

**Comment by sachinjain024** [comment]
Hey, @dwiyatci Thank you so much for the patience to wait on this. We will start investigating this now. cc - @sahil865gupta

**Comment by sachinjain024** [comment]
@dwiyatci Which library are you using for making the requests from the browser? Is it something like Axios or using fetch/XHR directly?

**Comment by dwiyatci** [comment]
@sachinjain024 Happy new year! 🥳  I'm using cross-fetch (https://github.com/lquixada/cross-fetch/) 😀

**Comment by sachinjain024** [comment]
@dwiyatci I have DMed you on Twitter. Kindly check there.

**Comment by sachinjain024** [comment]
This feature request is being discussed on our community slack with other users who also requested graphql query-based targeting. 

Here is the invite to join our community slack - https://join.slack.com/t/requestlycommunity/shared_invite/zt-113lursq9-2TI4bXLhkdNPEpTUJBprIA

@dwiyatci Can you please join that too so that we can have a productive discussion with all stake holders.

**Comment by dwiyatci** [comment]
Hey, just got back here. Been busy with work and my private life since the new year. Sorry! I'll try to join your community Slack tomorrow or the day after tomorrow. Maybe? 😬🤷🏻‍♂️

Wrt the website I was testing, it was a private corpo project, but I believe we can always use something like https://api.graphqlplaceholder.com/ or https://graphqlzero.almansi.me/ for testing purpose.

Simply open the Network tab of Chrome Dev Tools once you do some queries. There, you can see the corresponding Fetch/XHR requests of the GraphQL queries – they're actually just ordinary POST requests to the same (GraphQL) API endpoint but only differ in the (request) Payload.

**Comment by sachinjain024** [comment]
Thanks for sharing this info @dwiyatci -- See you on slack!

**Comment by sachinjain024** [comment]
Implementation has been done for this feature. We are doing a couple of other fixes before rolling this out in Chrome Store.

**Comment by sachinjain024** [comment]
The extension has been submitted to Chrome Store and Edge Store for review. Release version 22.1.18

**Comment by dwiyatci** [comment]
Thanks, very much, for the effort! I'll give it a spin once it's published in the Chrome Store. A small clarification: this new release contains only the first feature I requested, but still not the second yet, correct?

> 2. The ability to modify the request payload

And just out of curiosity: is there even an API exposed by Chrome for a Chrome extension to modify the request payload before it's being sent? If there isn't any, then the second feat might not be possible, right... 😅

**Comment by sachinjain024** [comment]
@dwiyatci -- You are right, it contains the first part of your request. Chrome doesn't provide APIs to modify the response even. We basically override the fetch and XHR object prototypes and write our custom implementation. It is very tricky to make It work for all websites and all cases. Still, the Modify Response works nicely.

Modify Request Data is also possible but honestly, that's a hell of a lot of code. We will provide that support in our desktop app - https://requestly.io/desktop in which it should be easy for us to do this.

**Comment by sachinjain024** [comment]
@dwiyatci I am closing this issue for now. We don't have immediate plans to allow modifying request body, I will open a separate one for that.

**Comment by dwiyatci** [comment]
Sure, it's fair enough. I understand the situation – modifying request body is quite a different game. While modifying response is pretty much the same as having a mock server (for the client), modifying request is like having a mock client (for the server), which I imagine its gonna be mega if Requestly could cover both sides in the future. 😃  All the best of luck with the roadmap ahead! ✨🏞
