### ISSUE TITLE
API Mock support data list

### ISSUE THREAD

**Issue by PeterChen1997** [requestly/requestly#1331]
Thx for create this useful app!

It would be better if app can remember the mock data in config or give a select to switch the mock data in one api.

![image](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/b8f31fe1-db33-4426-be45-0c9c53763b54/04a98820-6eca-4a11-8068-b936e433ad3e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9iOGYzMWZlMS1kYjMzLTQ0MjYtYmU0NS0wYzljNTM3NjNiNTQvMDRhOTg4MjAtNmVjYS00YTExLTgwNjgtYjkzNmU0MzNhZDNlIiwiaWF0IjoxNzA0ODgyNjg2LCJleHAiOjMzMjc1NDQyNjg2fQ.agVt7n39pqqIk8pRcCsJ7bE2BJKU_JyZvcJuUygH5pU)

**Comment by sagarsoni7** [comment]
Thanks @PeterChen1997 !
We'll work on this really soon

**Comment by PeterChen1997** [comment]
> Thanks @PeterChen1997 ! We'll work on this really soon

That's coolll. Thx for your work!
