### ISSUE TITLE
bug: Unable to save new rules after create new work space

### ISSUE THREAD

**Issue by kimpeeranut** [requestly/requestly#1352]
### Describe your issue?

Can't edit save new rules that just created

### Repro steps

1 Create new work space
2 Create new rules
3 Create rule (edit response)
4 Enter any mock response detail and check serve response without making a call to server

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Window 10

### Requestly Version

1.5.12

### Error screenshot

Here is error showing up

![2024-01-18_15h38_17](https://github.com/requestly/requestly/assets/36066066/e4c9ed86-eb44-463d-ab9e-2e7dc6508a20)

**Comment by DarkWolff71** [comment]
@kimpeeranut 
The issue is not reproducible.
![Capture1](https://github.com/requestly/requestly/assets/145280318/b0496c00-1fdd-455c-b6ac-0326a7875477)
