### ISSUE TITLE
Add support for attributes while injecting scripts in the Insert Scripts Rule

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#1374]
Feature Request taken from - https://stackoverflow.com/questions/77911144/chrome-extension-to-inject-javascripts-one-or-more-on-a-webpage

The idea here is to provide the capability to insert scripts, and the user should be able to provide additional attributes to the script URL like `data-*` or maybe change the type to `module`, which is common in ES modules.

**Comment by sachinjain024** [comment]
For the time being, provided a workaround on the SO question to the OP - https://stackoverflow.com/questions/77911144/chrome-extension-to-inject-javascripts-one-or-more-on-a-webpage/77912915#77912915

**Comment by nsrCodes** [comment]
1. This is now possible by wrapping the code inside a `script` or `style` tag and assigning the required attributes there. This will also be the default way code is formatted inside the editor for anyone using extension `v24.2.17` and above
2. The editor itself has been improved to provide errors/warnings for any mistakes while writing the wrapping html tags
3. A code editor is now also present [when the source type is url](https://developers.requestly.io/http-rules/modify-dom-inject-scripts/). This meant to only be used to specify the attributes and not anything else.

![Screenshot 2024-03-04 at 3 54 45 PM](https://github.com/requestly/requestly/assets/57226514/723e5f2a-3195-4162-8c19-d5b8fbd05f18)
![Screenshot 2024-03-04 at 3 54 23 PM](https://github.com/requestly/requestly/assets/57226514/33d67ae7-d1d6-4600-bef2-7d66d7ea2b4c)
![Screenshot 2024-03-04 at 3 53 55 PM](https://github.com/requestly/requestly/assets/57226514/f2907f64-d998-4367-8293-18fec96d5165)

These changes will not impact existing rules, but will only be available to users who are on the compatible version of the extension. Also, currently not supported on the desktop app.

Closed by:
https://github.com/requestly/requestly/pull/1386
https://github.com/requestly/requestly/pull/1474
