### ISSUE TITLE
bug: LINK.REQUESTLY_DOCS_TEST_URL_CONDITION outdated

### ISSUE THREAD

**Issue by BWagenerGenerali** [requestly/requestly#1381]
### Describe your issue?

The link LINK.REQUESTLY_DOCS_TEST_URL_CONDITION is outdated, it points to https://developers.requestly.io/test-url-condition which leads to a 404 page.

### Repro steps

https://developers.requestly.io/test-url-condition

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 10, Firefox

### Requestly Version

24.1.3

**Comment by nsrCodes** [comment]
fixed - https://github.com/requestly/requestly/pull/1382
