### ISSUE TITLE
bug: Loading huge rule collection start to failed

### ISSUE THREAD

**Issue by kimpeeranut** [requestly/requestly#1388]
### Describe your issue?

Background : User have bunch of rule that required for project, but requestly keep start endless loading collection

### Repro steps

1 Create rule > 100 rule until facing endless loading

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome, Desktop, Window 10

### Requestly Version

1.6.0

### Error screenshot

Log error 

> `[2024-02-06T04:26:18.510Z] @firebase/database: FIREBASE INTERNAL ERROR: Server Error: ClientId[27348144]:ErrorId[1412]: Write too large
`
![2024-02-06_12h14_06](https://github.com/requestly/requestly/assets/36066066/999f40a6-7930-4f18-81ec-cb64e41955c3)

**Comment by sagarsoni7** [comment]
To disable syncing

1. Make sure you are on a personal workspace
2. Go to Settings > Global Settings
3. Toggle "Enable Syncing"
