### ISSUE TITLE
[Features Request] API Client Module

### ISSUE THREAD

**Issue by huynhphuchuy** [requestly/requestly#1389]
I would like to request several features which help enhance the API Client module:

- Ability to create and store API requests permanently
- Ability to group API requests into collections for easy management
- Ability to import API collections from other sources such as Postman or Insomnia
- Ability to manage and switch between environment variables which could be embed directly in URL, headers, body payload..
- Ability to generate code snippets for API requests
- Ability to export collections of API requests
- Store JWT or cookies to share between API requests
- Integrate with OpenAPI to generate API doc for a collection

Thank you very much!!

**Comment by sagarsoni7** [comment]
Thanks @huynhphuchuy for placing the request. Will add this to our roadmap and keep you posted here.

**Comment by asachanfbd** [comment]
@huynhphuchuy most of the features requested by you are now available in Requestly. 

[Documentation](https://docs.requestly.com/general/api-client/overview) • [API Client](https://app.requestly.io/api-client/)
