### ISSUE TITLE
Sync Storage disabled?

### ISSUE THREAD

**Issue by mjbaldwin** [requestly/requestly#142]
Hi, I'm trying out Requestly but use my browser aross machines. And when I go to "storage settings" to try to switch from "local storage" to "sync storage", I get a message:

> We've disabled sync storage for the moment!

Sync is an absolute requirement for me. Is sync enabled for the paid plans? Is it disabled just for a few days, or has it been disabled for years? Is there an ETA for when it will come back?

It would be great if the docs could be updated with the answer to this as well, if this isn't just a few-days thing.

Thanks so much!

**Comment by sachinjain024** [comment]
Hey, @mjbaldwin Thank you so much for waiting for so long. Sync feature has been implemented now. We are just doing extensive testing right now within the team. Should be available really soon (less than a week).

cc - @sagarsoni7
