### ISSUE TITLE
bug: Request header inspection doesn't work for `Accept-Encoding`. [Mac Desktop]

### ISSUE THREAD

**Issue by lukesneeringer** [requestly/requestly#1445]
### Describe your issue?

I downloaded requestly because I wanted to know what headers I was sending to a server, and the tool I was using (reqwest crate for Rust) doesn't have an easy way to be verbose about a request.

This basic functionality doesn't work, although this appears to be limited to the `Accept-Encoding` header.

### Repro steps

My reproduction case is as follows:

1. Download the current Mac client (1.6.0), install disk image, open app, run the terminal command to enable interception (`. <(curl -sS localhost:7040/tpsetup)`).
2. Send several basic `curl` commands with distinct `Accept-Encoding` headers:

* `curl -I -v https://google.com/`
* `curl -I -v https://google.com/ -H "Accept-Encoding: gzip"`
* `curl -I -v https://google.com/ -H "Accept-Encoding: brotli"`
* `curl -I -v https://google.com/ -H "Accept-Encoding: identity"`

1. Observe that they all have an `accept-encoding: gzip` header.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

v1.6.0

### Error screenshot

![Screenshot 2024-02-22 at 10 58 32](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/ec0f4e51-8e45-4af2-9bfa-15ac326e8387/cb8b4c59-78d6-4db3-b332-069f6e6c1a43?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9lYzBmNGU1MS04ZTQ1LTRhZjItOWJmYS0xNWFjMzI2ZTgzODcvY2I4YjRjNTktNzhkNi00ZGIzLWIzMzItMDY5ZjZlNmMxYTQzIiwiaWF0IjoxNzA5NTM3OTkxLCJleHAiOjMzMjgwMDk3OTkxfQ.w9JxAdMRDaKKK5QRVzEDBsxETP24CNqqd3qg8C_Q2io)

![Screenshot 2024-02-22 at 10 58 59](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/a65ed6b8-baca-4199-ae24-6f93f00c0f08/554a636d-1c85-4425-bd00-1018fe292784?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9hNjVlZDZiOC1iYWNhLTQxOTktYWUyNC02ZjkzZjAwYzBmMDgvNTU0YTYzNmQtMWM4NS00NDI1LWJkMDAtMTAxOGZlMjkyNzg0IiwiaWF0IjoxNzA5NTM3OTkxLCJleHAiOjMzMjgwMDk3OTkxfQ.YzvUkRmVLUUUm7c8J1bcy7Aq__tBd8LrbsdVF-NaVhE)

**Comment by echo-sg** [comment]
Thank you for raising this, we'll check for the issue at our end and revert soon.

**Comment by nsrCodes** [comment]
Our [proxy middleware](https://github.com/requestly/requestly-proxy) splits the original connection ( _client -> server_) into two parts (_client -> proxy_ and _proxy -> server_) with some pre-defined assumptions. Overriding the `accept-encoding` is one of those assumptions. 

This needs to be fixed since this could also be a likely cause for https://github.com/requestly/requestly/issues/271

Thanks for pointing this out, we will try to address this ASAP
