### ISSUE TITLE
Can't install on OSX

### ISSUE THREAD

**Issue by earthgeek** [requestly/requestly#146]
I don't see the option to get the certificate mentioned on the website. The documentation doesn't mention it. I'm a bit confused.

**Comment by sagarsoni7** [comment]
@earthgeek - Let's connect over a quick zoom call and I'll help you setup everything?

[Schedule on Calendly](https://calendly.com/requestly-enterprise/requestly-premium-support)

Alternatively, there are some screenshots on this page, can you please check if they are helpful to you?
[requestly.io/for-safari](https://requestly.io/for-safari/)

**Comment by theinfin8y** [comment]
Hey @earthgeek -- Did you get a chance to try out the steps? We'd love to come on a call and help you out.
