### ISSUE TITLE
Replace String rule isn't working

### ISSUE THREAD

**Issue by israelboudoux** [requestly/requestly#149]
I have an application that requires some rewriting rules on the server side. When I use Requestly for doing these redirects, it doesn't work. Here they are the Request/Response:
=== Request...
POST /saml/acs HTTP/1.1
Host: localhost:8082
Connection: keep-alive
Content-Length: 6647
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: ...
Content-Type: application/x-www-form-urlencoded
User-Agent: ...
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,pt;q=0.8

==== Response...
HTTP/1.1 307 Temporary Redirect
Access-Control-Allow-Origin: https://sts.ynap.com
Access-Control-Expose-Headers: X-Content-Type-Options
Location: https://yyy-xxx-master.eks-dev.xxxxx.www.dev.e-comm/wapi/waars/internal/authenticated-masquerade
Connection: close
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 473
Server: Jetty(9.4.42.v20210604)

--
I have created the following Replace String Rule, which doesn't work:
Replace: https://yyy-xxx-master.eks-dev.xxxxx.www.dev.e-comm/wapi/
With: https://localhost:8082/
When Request URL Contains: https://yyy-xxx-master.eks-dev.xxxxx.www.dev.e-comm/wapi/waars/internal/authenticated-masquerade

It was supposed that the redirect will have the Location header modified which doesn't occur.

Hope that helps!

Best,
Israel

**Comment by theinfin8y** [comment]
Hey @israelboudoux, This could be happening because of 307 Internal redirects. Please allow us a couple of days to play around with such a setup and get back to you with a possible solution.

**Comment by israelboudoux** [comment]
Hey @theinfin8y, any news about that issue?

**Comment by sachinjain024** [comment]
Hey, @israelboudoux Thanks for the reminder. I will try to create a setup to reproduce this and see what we can do here. I doubt Chrome Extension can intercept 307 Internal redirects but this should be solvable with our desktop app. I will try out both tomorrow and let you know. Apologies for the delay from our side.

**Comment by israelboudoux** [comment]
nw @sachinjain024, I have a question: does your desktop app is able to intercept the request/response from the browsers like the plugin does?

**Comment by nafees87n** [comment]
@israelboudoux I recreated this issue using a mock API which does a 307 redirect to `https://yyy-xxx-master.eks-dev.xxxxx.www.dev.e-comm/wapi/waars/internal/authenticated-masquerade` and created this requestly replace rule which replaces domain with my `localhost` same as done by you. 

Here's the rule [https://app.requestly.io/rules/#sharedList/1639730461193-307-redirect](https://app.requestly.io/rules/#sharedList/1639730461193-307-redirect)

I also tried to create this using a local server on my machine where the endpoint does a 307 redirect same as your use case.

The rule is working as expected in both the cases. Can you please try using `http` with localhost instead of `https`? 
Please let me know if you face any trouble

**Comment by nafees87n** [comment]
> nw @sachinjain024, I have a question: does your desktop app is able to intercept the request/response from the browsers like the plugin does?

Yes

**Comment by sachinjain024** [comment]
@israelboudoux -- Did you get a chance to try out our desktop app? Here's a simple demo if you want to have a look before trying it out - https://www.youtube.com/watch?v=cqJcR-RcNXg

You can see we have an Apps section from which you can trigger Chrome (or any other browser installed on your machine). Then you will be able to see the traffic from that browser and apply the modification rules too.

**Comment by israelboudoux** [comment]
Hey @sachinjain024,
Actually, I have it installed. I'll try your suggestion. 

Thank you!

**Comment by israelboudoux** [comment]
Hey guys, I was able to complete the request/response flow using the Desktop app.
Thank you!

**Comment by sachinjain024** [comment]
Thank you so much @israelboudoux for letting us know that your problem was solved using the desktop app. Could you please help us with a review here - https://chrome.google.com/webstore/detail/requestly-modify-headers/mdnleldcmiljblolnjhpnblkcekpdkpa
