### ISSUE TITLE
how to modify http request header by myself js code

### ISSUE THREAD

**Issue by jonnywang** [requestly/requestly#150]
how to modify http request header by myself js code like modify http response using js

**Comment by theinfin8y** [comment]
@jonnywang You can modify request header using modify headers rule - https://requestly.io/features/modify-request-response-headers

I guess you are trying to modify using JS. Can you please explain your use case so that we can figure out a possible solution.

**Comment by jonnywang** [comment]
Yes, I want to modify using js code to change request header like referer、user-agent

and Is there a way to define a proxy pac function before send match request ?

Thanks for your reply!

**Comment by theinfin8y** [comment]
Thanks @jonnywang. We are considering to pick this up as feature request. Already added in our roadmap. Will keep you posted here.
