### ISSUE TITLE
Subscription on Dark Mode

### ISSUE THREAD

**Issue by kasparsiricenko** [requestly/requestly#151]
I don't see myself as a user of this app anymore... You don't treat users as human 
fellow developers 

![image](https://user-images.githubusercontent.com/64709398/143206069-da510129-5f18-4c99-9081-82e0f238f37a.png)

**Comment by sagarsoni7** [comment]
hey @kasparsiricenko thank you so much for taking the time to bring this issue to us. We released dark mode just a few hours ago and it was supposed to be free. Let me check with my team

**Comment by sagarsoni7** [comment]
Sorry that you went through this experience, it's a bug that caught us off guard. Would be resolved in a few minutes
