### ISSUE TITLE
bug: ENGG-1447: a bug occurs when I type a long string in the regex test for the API Response mock

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#1512]
### Describe your issue?

Reported by: Giovanni

### Repro steps

No additional details provided by user but we can still try out reproducing this ourselves.

### What Requestly tool were you using?

- [ ] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

latest

**Comment by rohanmathur91** [comment]
@sagarsoni7 Is this a blocker the user ?

**Comment by sagarsoni7** [comment]
@rohanmathur91 - No, we can pick this up in next cycle
