### ISSUE TITLE
bug: Session records not work for Chrome extensions

### ISSUE THREAD

**Issue by dengyakui** [requestly/requestly#1524]
### Describe your issue?

if i open the extension url below:
chrome-extension://mhnlakgilnojmhinhkckjpncpbhabphi/pages/chat/index.html
the record button not work.

### Repro steps

1. install a Chrome extension: [MaxAI.me](http://MaxAI.me)
2. open the extension's immersive chat page
3. open the Requestly extension, click the record button
4. the page not showing recording stauts

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Win10, Chrome 123.0.6312.58

### Requestly Version

v24.3.5

### Error screenshot

![image](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/ea2deed6-0745-4006-bfae-d4e4b7de770b/f444650e-8101-4862-92c3-2db8eac7b7fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi9lYTJkZWVkNi0wNzQ1LTQwMDYtYmZhZS1kNGU0YjdkZTc3MGIvZjQ0NDY1MGUtODEwMS00ODYyLTkyYzMtMmRiOGVhYzdiN2ZkIiwiaWF0IjoxNzExNDU0Mzc1LCJleHAiOjMzMjgyMDE0Mzc1fQ.E0r_Y2rBEADc8l3dXjxZO1LaBlJEROUYEoKeAAAOcLc)

**Comment by nafees87n** [comment]
Hey @dengyakui 
This is a technical limitation. Extensions are not allowed to work on browser's internal pages with schemes like `chrome://` `chrome-extension://` `about:` in firefox, `edge://` in Microsoft Edge for security reasons. Hence, recording does not work on these pages.

**Comment by sachinjain024** [comment]
Unfortunately, this is a technical limitation that can't be bypassed So closing this issue.
