### ISSUE TITLE
How To Use SessionBook/Recording Feature To Capture All Requests (Documents, Images, Audio, Video)

### ISSUE THREAD

**Issue by AdonisCodes** [requestly/requestly#1590]
There isn't any documentation on this, and I am working with a server side only php webapp for scraping for a client. And can't use requestly to inspect those as they don't make any json/other common datatype requests, only page redirecting & refreshing.

**Comment by AdonisCodes** [comment]
I see that the implementation you guys have doesn't record on refresh. Is there any workaround as this really is an important usecase for the tool I think.

**Comment by AdonisCodes** [comment]
https://github.com/requestly/requestly-web-sdk/blob/master/documentation/Network.md#specifications
According to the documentation of this. We can get access to request headers. I assume it is for non technical person safety. I am going to keep using the browser requests for now to inspect it easier rather than trying to create a workaround hack for this.

**Comment by sagarsoni7** [comment]
You're right, SessionBook can't really help much with server-side rendered webpages.
What's exactly your use case? Most of our dev users use it for frontend debugging.
