### ISSUE TITLE
Add Support for Folders/Collections for API Mocks in Mock Server

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#1596]
Right now, Requestly Mock Server is used to create API Mocks (endpoints) by providing the API response and other details.

Here are some main requirements
- Users should be able to organize their mocks inside a collection
- A collection can have an optional path and all the nested mocks get the collection prefix automatically
- Users should be able to enable/disable a mock
- Users should be able to download mocks & collections as JSON file

This helps multiple users collaborate in the mock server. Users can also create Mocks within a collection and the collection can be named on the users or APIs hierarchy.

Corresponding Linear Ticket - https://linear.app/requestly/issue/RQLY-411/folderscollections-support-in-mocks (For Internal Team only)

**Comment by rohanmathur91** [comment]
We have added the collection path support and its live, for enable/disable a mock and download mocks & collections as JSON file this we will pick soon, closing this issue.
