### ISSUE TITLE
feat: Make it easier to test "Overriding API Responses" feature (Implicit Rule Testing)

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#1597]
Override API Response is a very handy feature for frontend developers to unblock themselves from backend developers, simulate API errors, override configs, test negative cases, etc. but the responses overridden by Requestly aren't captured in Chrome Devtools so it always creates confusion for the end users whether the rule has applied or not.

Here are a few changes we are doing to improve the overall experience of testing a rule.
1. When the user saves the rule for the first time, give the visibility to testing feature
2. Auto-Save sessions when a user comes back to the rule editor, the user can view and delete the session.
3. Remove Execution Logs
4. Show a widget on the page whenever a rule is applied and by default keep it on for Script Rule, Response Rule and let user configure for other rule types.

**Comment by sachinjain024** [comment]
Here's a demo video of the implicit workflow of Testing the Rule

Uploading Screen Recording 2024-04-05 at 2.49.04 AM.mov…

**Comment by wrongsahil** [comment]
Here's how the final feature looks like
https://www.youtube.com/watch?v=2Crb4qXw8FA
