### ISSUE TITLE
Showing invalid date in Execution Logs table

### ISSUE THREAD

**Issue by SankhaChak** [requestly/requestly#164]
<img width="800" alt="screenshot-2021-12-30-at-10173_1md21i8" src="https://user-images.githubusercontent.com/16779465/147765172-3a412e8d-f639-4984-b27d-61d2aef588f0.png">

**Comment by sachinjain024** [comment]
This is happening for the ModifyResponse rule. I will also check for the Script rule, a similar issue might be there.
