### ISSUE TITLE
Add support to import Modheader Exported Profiles(JSON) to Requestly

### ISSUE THREAD

**Issue by kevinsmithrf** [requestly/requestly#1642]
I want to import Modheader Profiles to Requestly, but the import fails because support is not there. Please add support for importing JSON from ModHeader. I have lots of profiles and rules created in Modheader, which I want to move to Requestly.

[Stackoverflow Question for Details](https://stackoverflow.com/questions/78383989/how-can-i-import-modheader-json-profiles-into-requestly)

**Comment by sagarsoni7** [comment]
Hi @kevinsmithrf  thanks for raising this request.
We'll have a look into this soon.

**Comment by wrongsahil** [comment]
Fixed in https://github.com/requestly/requestly/pull/1933

You can import your modheader profile here https://app.requestly.io/import-from-modheader
