### ISSUE TITLE
How to exclude some domain name requests in the http proxy

### ISSUE THREAD

**Issue by beergold** [requestly/requestly#1680]
How to exclude some domain name requests in the http proxy, instead of directly connecting to the domain name request in the blacklist through the proxy such as the blacklist mechanism, such as *.apple.com

**Comment by sagarsoni7** [comment]
@beergold As of now we do not have support to exclude given domain domains in the app.
A few users have requested in the past but they managed to do it via their system proxy settings.

![image](https://github.com/requestly/requestly/assets/29792913/19add47b-624c-414b-9687-766294c8bbf8)

^ This works for the system wide proxy, not individual browser session launched by Requestly.

Does this help?

**Comment by sagarsoni7** [comment]
Thanks for sharing the details. I wish I could help but iOS does not have a native setting to bypass specific domains.

There're workarounds like creating your own config profile via [Apple Configurator](https://support.apple.com/en-in/apple-configurator) but they best way would be to have such settings at the Requestly level itself, which is honestly not in the near future plan.
