### ISSUE TITLE
Migrate to Requestly from Resource Override

### ISSUE THREAD

**Issue by payne-shaun** [requestly/requestly#172]
Hey Requestly team!

I have been using Resource Override for a long time. I recently got a chance to check out Requestly and I really liked it. It has a sleek UI and a lot more features than what Resource Override offered...

I want to migrate to Requestly but I face an issue. I have created many rules on Resource Override and I don’t know how to get them on Requestly. I am even willing to pay and get a premium plan. Please help me make the switch!!

**Comment by sahil865gupta** [comment]
Hey @payne-shaun. We are glad to know that you liked Requestly.

We would love to help you set up your rules. Can you create a [sharedlist](https://docs.requestly.io/managing-rules/sharing) for all your rules and share it with us. We can have a quick look and tell you what's wrong with them. 

P.S: You can also join our slack community too for faster communication 😉 
https://bit.ly/requestly-slack

**Comment by payne-shaun** [comment]
Thanks for responding

I am joining slack, will carry on the conversation there.
