### ISSUE TITLE
Choose Persona

### ISSUE THREAD

**Issue by vineetathome** [requestly/requestly#176]
Is there a need for choose persona on account settings. In any case. when you choose it you have to
1). choose from the dropdown
2). then click elsewhere on the screen for the choice to be selected. 

Ideally choose should be done in single click (that is if it is important to have)

**Comment by sagarsoni7** [comment]
@vineetathome - Hmm that makes sense. We will improve it eventually.

It isn’t used much though.

**Comment by vineetathome** [comment]
then I would say hide it.
