### ISSUE TITLE
Modifying Response Headers Not Working (OSX/Chrome)

### ISSUE THREAD

**Issue by joepk90** [requestly/requestly#178]
If this issue has been raised in the wrong repository, please let me know.

Using the Chrome Extension on OSX, modifying (adding, deleting, modifying) the Response Headers don't seem to be working.

I am able to Modify the Request Headers fine though.

This has been tested across two Macbooks.

**Comment by sahil865gupta** [comment]
Hey @joepk90. Thanks for letting us know about this.
I am able to reproduce this on my system too. Let us debug this. We will try to fix this as soon as possible.

**Comment by joepk90** [comment]
It actually looks like this is due to a bug in Chrome - here is the ticket:
https://bugs.chromium.org/p/chromium/issues/detail?id=258064
