### ISSUE TITLE
i'm at two rules, when i try to create a new rule it says i'm limited to 3 and won't let me

### ISSUE THREAD

**Issue by vv211** [requestly/requestly#179]
really just what the title says. i'm getting the error that i'm limited to a max of 3 rules on a free account and requestly won't let me create another one, but i only have 2 rules

**Comment by sachinjain024** [comment]
Hey @vv211 Can you please share a screenshot with us and we'd take a look at it?

**Comment by vv211** [comment]
![2022-01-23 22_58_34-My Rules](https://user-images.githubusercontent.com/9099977/150903644-b5672e79-1d9e-424e-8485-c2f65463a16d.png)

**Comment by nafees87n** [comment]
@vv211 Can you please share the email id you are using with requestly so that I can activate premium on your account? With premium account you can continue your work meanwhile, we'd take a look at this issue
