### ISSUE TITLE
bug: Microsoft 365 Word (online version) loading infinitely

### ISSUE THREAD

**Issue by Nyfos** [requestly/requestly#1800]
### Describe your issue?

As show on the screens below, when the Requestly extension is enabled in the navigator, the page loads infinitely, despite no rule being triggered.

![image](https://github.com/requestly/requestly/assets/58190823/086f2710-0836-4b08-9908-7b29a86ac1ec)
![image](https://github.com/requestly/requestly/assets/58190823/a706fbbc-8143-4a0e-8087-e807aba86046)

### Repro steps

Download and install Requestly extension, then navigate to office.com and load a .docx file. 

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11 with Brave Version 1.66.118 Chromium: 125.0.6422.147

### Requestly Version

v24.5.8

**Comment by nafees87n** [comment]
Getting this error: 
<img width="1431" alt="image" src="https://github.com/requestly/requestly/assets/56021937/6468b0d9-2d42-4081-866a-9baa806c0ba7">

@Nyfos Thanks for reporting this. We will try to fix this as soon as possible.

**Comment by nafees87n** [comment]
@Nyfos I can confirm that this is not an issue with our latest version `v24.5.27`. Can you please update the extension to the latest version.
You can follow the steps to manually update it from [here](https://developers.requestly.com/guides/update-requestly-extension/).

**Comment by Nyfos** [comment]
@nafees87n
Ok, just updated to the new version, from Chrome WebStore: `v24.5.27 (MV3)`.
_What's "MV3" standing for?_

...aaaaand, just realised it's working back as normal...
Let me know if the problem still happens to you (the page may be cached in my browser or something).

**Comment by nafees87n** [comment]
@Nyfos Thanks for the confirmation. Feel free to report if you encounter any issue.
MV3 refers to the new guidelines for browser extensions by chrome. You can read more about it [here](https://github.com/requestly/requestly/issues/1690)

**Comment by sachinjain024** [comment]
@nafees87n @Nyfos Are we good to close this issue?

**Comment by Nyfos** [comment]
@sachinjain024 
I no longer have the issue, but it seems that @nafees87n is still having it, as ---
Oops, my bad, I thought @nafees87n said that this _is_ an issue with the latest version.

Nevermind, as none of us is having the issue with the latest version, sure, we're good to close! 😁 
Thank you so much for your help! 🙏🏼
