### ISSUE TITLE
Replace Rule issue when entered `-`

### ISSUE THREAD

**Issue by vijay-2406** [requestly/requestly#1801]
In our replace string we are trying to replace a url with local host but in the url we have - (hyphen), when it encounters it, it is not replacing. Lets say we have my-sample-app, when we are replacing with url/my with local host url it is replacing but when try url/my-sample-app or even url/my- with localhost url it is not replacing. It was working previously but not working now

**Comment by wrongsahil** [comment]
Hey @vijay-2406. That seems odd. 
- Can you share the extension version (`chrome://extensions/?id=mdnleldcmiljblolnjhpnblkcekpdkpa`)
- Can you share sharedlist or screenshot of an example rule

**Comment by wrongsahil** [comment]
Closing this for now as this doesn't look reproducible
