### ISSUE TITLE
Enable button not working

### ISSUE THREAD

**Issue by Shathath** [requestly/requestly#181]
Enabling the rules from inside using switch button is not enabling the rules

**Comment by sagarsoni7** [comment]
Thanks Shathath for logging this issue. Right now it requires the rule to be saved after toggling it.

We'll soon improve this experience

**Comment by sagarsoni7** [comment]
Hi @Shathath - Can you please check now?

If it still doesn't work, maybe the Rule isn't matching. Can you please share the Rule here? (You can select the Rule in dashboard and click the Share icon, it will generate a link)

**Comment by sachinjain024** [comment]
This has been fixed so closing the issue.
