### ISSUE TITLE
Upgrade experience

### ISSUE THREAD

**Issue by vineetathome** [requestly/requestly#182]
I upgraded to the latest build today

1). New version available. Click here to upgrade. Ideally the cursor should change from pointer to hand. It does not. Clicking on it sure asks for restart message
2). The restart message shows. 'Are you sure you want to quit requestly' or something. It should tell say that, Confirm to upgrade and restart.

**Comment by wrongsahil** [comment]
Yeah makes sense
1. Added a pointer to the update dialog. Will get reflected from now on.
2. I have to check whether this is possible or not. If yes, I'll change that too

**Comment by vineetathome** [comment]
@wrongsahil I did check that now we have a pointer. Did you do the second one ?

**Comment by wrongsahil** [comment]
@vineetathome Yes. It is possible. I'll push this is next release
