### ISSUE TITLE
bug: Cannot set properties of undefined (setting '_method')

### ISSUE THREAD

**Issue by GreatDianna** [requestly/requestly#1823]
### Describe your issue?

As mentioned in https://github.com/the1812/Bilibili-Evolved/issues/4760, the problem still appears. I'm not very familiar with this field, any way to avoid this problem without disable requestly? I think it's already the latest version.

### Repro steps

1. Using both [Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved) and requestly.
2. These three functions don't work as expected: [viewCover](https://github.com/the1812/Bilibili-Evolved/blob/master/registry/dist/components/utils/view-cover.js), [showCoverBeforePlay](https://github.com/the1812/Bilibili-Evolved/blob/master/registry/dist/components/video/player/show-cover.js), [showUploadTime](https://github.com/the1812/Bilibili-Evolved/blob/master/registry/dist/components/video/player/show-upload-time.js)

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 10, Edge 128.0.2647.0 canary

### Requestly Version

Version 24.5.8

**Comment by wrongsahil** [comment]
Hi @GreatDianna , We've released a fix in the latest version, v24.7.29. Please follow [these steps](https://docs.requestly.com/guides/how-to-update-requestly-extension-manually) to update the extension manually. Let us know if this resolves the issue.

Related to #1980

**Comment by wrongsahil** [comment]
Closing this for now. https://github.com/requestly/requestly/issues/1980 Refer this for more details
