### ISSUE TITLE
bug: How to disable the constant opening of the application when launching the browser

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#1834]
### Describe your issue?

It's terribly inconvenient

- live chat

### Repro steps

- 

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome 124

### Requestly Version

24.5.27

**Comment by wrongsahil** [comment]
This was fixed in extension `>v24.7.2`
