### ISSUE TITLE
Folder on HTTP Rules Screen

### ISSUE THREAD

**Issue by vineetathome** [requestly/requestly#184]
Should you give the ability for segregating rules in folders. You should see how the mocks looks.
What is the idea of marketplace ? do you sell rules there ? Or what is the intent ?

**Comment by wrongsahil** [comment]
We do give the ability to segregate rules in folders. We call it groups though. Here's a doc for explaining how they work (https://requestly.io/blog/manage-rules-using-groups-in-requestly/)

Marketplace contains all the commonly used rules. We are renaming this to `Library` as our intent is not to sell from here.  But to make users use the most common rules more easily from here.

**Comment by vineetathome** [comment]
Cant upload the screenshot. But can you send me where to create the rules from on the Mac app ?

**Comment by wrongsahil** [comment]
@vineetathome You can create a new rule by going to `HTTP RULES` tab and then click on `New Rule` Button to create a rule

**Comment by vineetathome** [comment]
sorry wrong question.  I wanted to ask how to create a group and then a rule in that group ?

**Comment by wrongsahil** [comment]
First create a group by clicking on `New Group` Button on Rules Page
![Screenshot 2022-01-27 at 12 28 26 PM](https://user-images.githubusercontent.com/16779465/151307713-f4244ee0-b80f-4c6f-9cf0-9f8bf5f80466.png)

Then select the Group from this dropdown while creating a new rule.
![Screenshot 2022-01-27 at 12 28 05 PM](https://user-images.githubusercontent.com/16779465/151307819-e52b7bca-9f54-4ef2-bb71-0e1fc650aa13.png)

OR

You can move existing rules to a group too from `My Rules` Page.
- Select the rules to move
- Then click on `Change Group` Button
![image](https://user-images.githubusercontent.com/16779465/151308075-6c887511-7094-40fe-bdca-92bed55950ad.png)


Tip: You have enable/disable the rules in a group at the same time too
