### ISSUE TITLE
How can intercept a request that has a sessionid that changes per second?

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#1843]
request:

```
{"sessionid": "7183059a-e28f-4072-9be9-c9ec1287ffa2" #(this changes per second)
"action": "game",
"gameid": "6af0ca2c-8a2e-ef11-86c3-000d3a866863",
"gamemode": true,
}
```

response:

```
{
"action": "game",
"gameid": "6af0ca2c-8a2e-ef11-86c3-000d3a866863",
"friendlyid": 5542456982,
"dts": "2024-06-19T22:20:49.157Z",
"sessionid": "7183059a-e28f-4072-9be9-c9ec1287ffa2", #(i want this to be mirrored to the request body sessionid)
"brandgameid": "e5a04f51-6d20-4504-91bc-d17656d2e542"
}
```

**Comment by wrongsahil** [comment]
Modify Response Rule (Dynamic - Javascript) can be used for achieving this. The JS method in the rule contains requestBody as a param which can be used to render the response. Here are the docs for [same](https://arc.net/l/quote/gwhnjvwn)

Here's how the rule should look like https://app.requestly.io/rules#sharedList/1719222329836-Github-Issue-1843
<img width="1144" alt="image" src="https://github.com/requestly/requestly/assets/16779465/7a4c83b2-b89c-4b4a-b961-80ce70821972">
