### ISSUE TITLE
Plugin ruin all my url's with "#__rq_marker"bug: 

### ISSUE THREAD

**Issue by bigboban** [requestly/requestly#1882]
### Describe your issue?

All my url's in url field are ruined with "#__rq_marker". I can't copy/paste url and send it to someone for example because now it is "wierd". 

For example: https://github.com/requestly/requestly/issues#__rq_marker=https://github.com/requestly/requestly/issues

Please fix this ASAP.

### Repro steps

Open any web page.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows, Chrome

### Requestly Version

24.6.21 (MV3)

**Comment by vithano** [comment]
please fix this

**Comment by wrongsahil** [comment]
Hey @bigboban . This marker `#rq_marker` is added so that replace rule can work properly. This was introduced so that replace rule can work with [Chrome MV3 APIs](https://github.com/requestly/requestly/issues/1690). 

### Solution
In replace rule, instead of an open source condition, make a closed one which only targets specific urls.
![0118d88de7a7e8c2915da229ee7f8d3fc064905894ef9e0c5f8dc08d5bfd5ca7](https://github.com/requestly/requestly/assets/16779465/39e36842-3fdb-4797-a30b-7822107e753f)

**Comment by vithano** [comment]
i fixed my problem by using redirect rule instead of string replace

**Comment by wrongsahil** [comment]
In almost all the cases, you can achieve same thing using Redirect Rule + Wildcard/Regex too. Just that replace rule is more intuitive. 

https://github.com/requestly/requestly/issues/1797

**Comment by wrongsahil** [comment]
> Hey @bigboban . This marker `#rq_marker` is added so that replace rule can work properly. This was introduced so that replace rule can work with [Chrome MV3 APIs](https://github.com/requestly/requestly/issues/1690).
> 
> ### Solution
> In replace rule, instead of an open source condition, make a closed one which only targets specific urls. ![0118d88de7a7e8c2915da229ee7f8d3fc064905894ef9e0c5f8dc08d5bfd5ca7](https://private-user-images.githubusercontent.com/16779465/344142983-39e36842-3fdb-4797-a30b-7822107e753f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjIxNjksIm5iZiI6MTcyMDYyMTg2OSwicGF0aCI6Ii8xNjc3OTQ2NS8zNDQxNDI5ODMtMzllMzY4NDItM2ZkYi00Nzk3LWEzMGItNzgyMjEwN2U3NTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE0MzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDk4ODc4NjYxNWI4OGI1YWRhMzk3Njg2ODc2MTlhNmJkZmU3YWU0MjRlNjkyYzE1NGRiMjE3NjlmYTUzNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1M5ri_bb4MkVwBwCvFD-UGmWnc6gL85qcWHsuovhrws)

If you are facing this issue, please refrain from making open source matching conditions. Only target specific urls. 

If you still face this issue, then try using the methods mentioned [here](https://github.com/requestly/requestly/issues/1797) to convert replace rule into redirect rule

**Comment by wrongsahil** [comment]
We've released a patch which doesn't add marker for replace rule when source condition is empty
https://github.com/requestly/requestly/pull/2037/files
