### ISSUE TITLE
bug: Can't open global setting page in firefox after logined

### ISSUE THREAD

**Issue by Lyrillind** [requestly/requestly#1883]
### Describe your issue?

In firefox browser, after logined my account, when I open global setting page, it keeps asking me to install firefox extension.

The extension throwed an error.

<img width="1248" alt="image" src="https://github.com/requestly/requestly/assets/4125903/b1439e39-aae7-44b4-831d-0a104b8743f0">

### Repro steps

1. Open Requestly extension popup window
2. Click on "Open App" button
3. Login to app.requestly.io
4. Click on setting icon on the left of avatar

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

macOS 13.6.7 firefox 127.0.2

### Requestly Version

v24.5.8

### Error screenshot

![image](https://github.com/requestly/requestly/assets/4125903/14492447-41db-4b6a-9ddf-20b9298335da)

<img width="1248" alt="image" src="https://github.com/requestly/requestly/assets/4125903/c41d530a-fb7f-4762-93d9-2ea6945a28cb">

**Comment by RuntimeTerror10** [comment]
Hey @Lyrillind, this bug has now been fixed.
