### ISSUE TITLE
Improve search in traffic inspector to easily select logs for mocking GraphQL session

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#1888]
When trying to create a mock session containing graphql request; since the URL is the same it is hard to filter and select the exact requests that I want to save and mock.

Currently, I have to search for our `/graphql` endpoint and then go through the request details of each log to check their respective query and operation name. 

Would at least be nice to let the search query also search through the request body. This way I can search for the operation name directly

**Comment by nsrCodes** [comment]
We have made some improvements around this (https://github.com/requestly/requestly/pull/1857) 
Here's a video explaining the improvements:
1. highlight operation name next to the URL
2. search for the any part of the request body (query, operation name, variables, etc.)

https://github.com/requestly/requestly/assets/57226514/01978072-2fe1-40ce-91dd-948965ef0347
