### ISSUE TITLE
Intercept HTTPs traffic from Android Emulators (1-Click Setup)

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#1899]
The current process of intercepting traffic from Android emulators requires installing a certificate and proxy which is a bit cumbersome. 

With this feature, simplify the traffic interception setup from Android emulators.

**Comment by sachinjain024** [comment]
This is under PR review, desktop app release will be required. This is how the experience looks like right now --

https://github.com/user-attachments/assets/f8e4cedd-5a83-4fb8-94cc-1ab7f8d4426c

**Comment by sachinjain024** [comment]
Traffic Modification Demo

https://github.com/user-attachments/assets/5c41b4d4-6b19-42b6-8207-442b7d7f32a1

**Comment by wrongsahil** [comment]
Released in [v1.7.0](https://github.com/requestly/requestly-desktop-app/releases/tag/v1.7.0)
**Docs**: https://developers.requestly.com/android-emulators/
**Demo**
https://youtu.be/37R0qOw6mrY?si=3CGlgZXxTmCvXREW
