### ISSUE TITLE
Issue with Saving the rule

### ISSUE THREAD

**Issue by prashantbazaarvoice** [requestly/requestly#191]
I am using free version of requestly and have created only 3 rules in a but still when I am trying to save its throwing me a popup warning by stating I have already reached 3 rules I am though I am trying to delete but still its throwing the same error

**Comment by sachinjain024** [comment]
Thank you @prashantbazaarvoice for raising this issue. I have temporarily activated the basic plan on your account so that you get unlocked and use the product. We will check this on priority.

**Comment by breadbrowser** [comment]
I have a premium account and never paid. i only signed in with google
