### ISSUE TITLE
Requestly rule replace string conflict with library sentry/vue

### ISSUE THREAD

**Issue by dung-tv** [requestly/requestly#1921]
### Describe your issue?

I used requestly to create a replace string rule that when entering a website will replace the url to another url, but when using it with a website that uses the @sentry/vue & @sentry/tracing 7.52.1 library, there is a problem with the library. This causes conflict between functions in the library

### Repro steps

1. Create rule replace string
2. open tab with genshin daily checkin 
3. in the screen some component not rendering

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Edge Version 126.0.2592.87 (Official build) (64-bit)

### Requestly Version

v24.7.2

### Error screenshot

When i enable requestly:
![image](https://github.com/requestly/requestly/assets/58056993/73674222-5247-4c03-a93e-43ef89e30d53)
When i disable requestly:
![image](https://github.com/requestly/requestly/assets/58056993/6883af84-87a4-4517-b357-d8b33a3dfe2e)

**Comment by sachinjain024** [comment]
Hey @dung-tv Thanks for reporting this issue. We have just uploaded a new build in the Chrome Store, as soon as Google approves the build, it will be available.

Most likely this issue should be fixed as well.

FYI @wrongsahil

**Comment by wrongsahil** [comment]
Hey @dung-tv. v24.7.7 is available in the chrome store now.  Can you please manually update the extension using these [steps](https://developers.requestly.com/guides/update-requestly-extension/)

**Comment by dung-tv** [comment]
> Hey @dung-tv. v24.7.7 is available in the chrome store now. Can you please manually update the extension using these [steps](https://developers.requestly.com/guides/update-requestly-extension/)

Ohh, I updated to v24.7.7 and the problem is resolved, I will close this issue. Thank you for supporting this issue
