### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PratikRay2** [requestly/requestly#193]
I have purchased a premium plan but still, I am not able to save any rules. Kindly resolve this issue asap.

**Comment by sagarsoni7** [comment]
@PratikRay2 - I see multiple attempts were made to subscribe to the plan that caused this issue. Can you please refresh the page and see if issue still persists?

**Comment by sachinjain024** [comment]
Hey, @PratikRay2 Are you still facing this issue?

**Comment by PratikRay2** [comment]
No, I am not facing this issue anymore.


Thanks
Pratik Ray
