### ISSUE TITLE
'Pick from mock server' shows duplicate mock files

### ISSUE THREAD

**Issue by alonhartman** [requestly/requestly#196]
Hi,
I'm using the free version, and I have 3 mock files. Whenever I open the 'Pick from mock server' in the rule, I see duplications of the existing files with different 'Last updated' dates.
You can see it more in the attached video.

Thanks,
Alon.

https://user-images.githubusercontent.com/11316700/156917266-e90f6d4d-e749-4a99-a6bb-debe74733378.mp4

**Comment by sagarsoni7** [comment]
Thanks for bringing this issue to our notice @alonhartman, the video is indeed helpful.
We'll fix this really soon

**Comment by sachinjain024** [comment]
This has been fixed so closing the issue.
