### ISSUE TITLE
Redirect http by regex not work in v24.7.7

### ISSUE THREAD

**Issue by TiepHoangDev** [requestly/requestly#1966]
![image](https://github.com/user-attachments/assets/163ab3cd-0411-488d-84fe-a3eaba41d5f0)

**Comment by wrongsahil** [comment]
Hey @TiepHoangDev . Can you add a similar matching regex (with some random text in place of your regex). This would help us debug the issue

Also are you getting any errors while saving the rule?

**Comment by TiepHoangDev** [comment]
Hi, my redirect is work for me in old version, but new version is not working!
This is example of regex:
- regex: /https:\/\/www.google.com\/(?<query>.+)/
- output: https://127.0.0.1:5001/$1
example:
- url: https://www.google.com/search?q=hello
- expect request will redirect to: https://127.0.0.1:5001/search?q=hello

![image](https://github.com/user-attachments/assets/21cbbcc1-8443-4d9c-a4dd-21fd74ce7ffb)
thanks!

**Comment by TiepHoangDev** [comment]
yes. thank you!
