### ISSUE TITLE
Cannot access previously created rules

### ISSUE THREAD

**Issue by glindy89** [requestly/requestly#197]
Recently upgraded account and can no longer access the HTTP rules I previously created. HTTP Rules landing page prompts to "create first rule," and only new rules appear. I downloaded the desktop app for Mac and want to export/import my old rules but am unable to access them.

**Comment by sagarsoni7** [comment]
@glindy89 - Can you please visit this page and click the Send button? - [https://app.requestly.io/send-debug-report](https://app.requestly.io/send-debug-report)
