### ISSUE TITLE
Request headers not updated

### ISSUE THREAD

**Issue by hammond756** [requestly/requestly#1977]
I have a rule set up to add an X-API-KEY header to matching requests. This has worked perfectly for months now. But now the extension says that the rule is applied, but it's not.

<img width="993" alt="image" src="https://github.com/user-attachments/assets/8d63a3f9-7bef-4b3b-a48c-1db3875f93a3">

**Comment by wrongsahil** [comment]
Hey. Can you share the extension version which you are using right now. Also is it possible to share the rule with masked data?

**Comment by sachinjain024** [comment]
@hammond756 We might need to know the rule definition to see what could be happening. You can follow these steps - https://developers.requestly.com/http-rules/sharing-rules/#30632c31e6bd4d89844849e3ddeaa8f4 and share the link with us directly here or share with us over email - contact at requestly

**Comment by hammond756** [comment]
I duplicated the rule to share a redacted version of it. Then went to test if the copy fired on the matching URLs and now it works with the original rule 🤷 .. Consider this resolved then. Thanks for the quick response.
