### ISSUE TITLE
Response Modification Rule failing on mudah.my

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#198]
Response Rule breaking on Extension and Desktop App

### Steps to Reproduce
- Go to https://www.mudah.my/ECU+Mercedes+Benz+Repair+272+ME9+7-83077644.htm (any listing on https://www.mudah.my/list?nf=1)
- Now click on `Next Ad` <img width="1309" alt="Screenshot 2022-03-28 at 2 10 39 PM" src="https://user-images.githubusercontent.com/16779465/160360316-979d1142-239d-4b27-a622-26ad2a9f1910.png">
- This will fire a fetch request with url `https://gateway.mudah.my/osiris/v1/view`. Requestly fails to perform any response modification on this URL.

### Findings
initOptions seems to be missing here
<img width="1072" alt="Screenshot 2022-03-28 at 2 15 53 PM" src="https://user-images.githubusercontent.com/16779465/160361014-15535e1f-b870-498e-89c8-43b1928856e7.png">

**Comment by lazyvab** [comment]
Raised PR: https://github.com/requestly/requestly-master/pull/1216

**Comment by lazyvab** [comment]
<img width="1431" alt="fixed" src="https://user-images.githubusercontent.com/6367566/161382673-ed3d6009-bd12-4269-bc18-556e73ebb7de.png">
<img width="1370" alt="rule" src="https://user-images.githubusercontent.com/6367566/161382707-2bba0cff-a679-4fdc-9f35-349e848e9646.png">
