### ISSUE TITLE
gamefaqs poll map

### ISSUE THREAD

**Issue by jag176** [requestly/requestly#1981]
gamefaqs poll map doesn't work when requestly activated, even if no rules used

**Comment by sachinjain024** [comment]
We are releasing a new feature in the next couple of days that allow you to block Requestly on certain sites. Once that feature is released, we will let you know and you can put this website into the block list.

**Comment by wrongsahil** [comment]
Hey @jag176 . You can add this website to blocklist so that Requestly would not have any effect on that website.
Please refer the documentation [here](https://docs.requestly.com/changelogs/extension/v24723-blocklist-support)

**Comment by jag176** [comment]
How do I set up the blacklist? I see no option for it

**Comment by wrongsahil** [comment]
Hi @jag176 , We've released a fix in the latest version, v24.7.29. Please follow [these steps](https://docs.requestly.com/guides/how-to-update-requestly-extension-manually) to update the extension manually. Let us know if this resolves the issue.

**Comment by wrongsahil** [comment]
Related to #1980

**Comment by jag176** [comment]
Yes, it is working.

**Comment by wrongsahil** [comment]
Thanks for confirming :D . Will close this issue for now.
