### ISSUE TITLE
Requestly Makes Me Delete Chrome Cookies After Every Test/Request

### ISSUE THREAD

**Issue by sterling-api** [requestly/requestly#199]
hi.  I am testing a software but Chrome makes me clear my cookies after every test/request.  "Deactivate Requestly" does not resolve the issue.  I have tried uninstalling and reinstalling but this did not work either.  When I refresh the page while Requestly is deactivated, Chrome gives me the message (name of website) edirected you too many times.
[Try clearing your cookies]
ERR_TOO_MANY_REDIRECTS

**Comment by sachinjain024** [comment]
I'd love to get more details on the rule and how to reproduce. If this is something you can't share, please shoot an email to contact@requestly.io

**Comment by Sterlz-API** [comment]
I sent an email to the email provided.  Thank you.

**Comment by breadbrowser** [comment]
seems like a browser problem or just your code
