### ISSUE TITLE
bug: "Invalid regex. The negative lookahead assertion (?!...) is not supported."

### ISSUE THREAD

**Issue by Holokai** [requestly/requestly#1996]
### Describe your issue?

I've had a single  rule in requestly for 3-4 years now. This rule has suddenly stopped working, and when I try to save it now, I get an error: "Invalid regex. The negative lookahead assertion (?!...) is not supported." Has there been a change to negative lookahead support? If so, should this message relay further information? Thanks for any help!

Also the AI bot is confused:
![image](https://github.com/user-attachments/assets/1da3c6b2-1f95-4220-a96d-6ef2d99ce099)
![image](https://github.com/user-attachments/assets/a62701ba-74ad-4edb-a556-614f93c49247)

### Repro steps

Sample Rule:
/(?!.*something)(?!.*another)(url1|url2)/ig

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11, Chrome 126.0.6478.183

### Requestly Version

v24.7.23

### Error screenshot

![image](https://github.com/user-attachments/assets/c3ea3b46-57d4-4499-b2ad-e3fbf14b25f3)

**Comment by nafees87n** [comment]
Yes. Lookaheads are not supported now. This change comes after the chrome MV3 migration. Chrome uses [RE2](https://arc.net/l/quote/xwbjfakc) internally where lookaheads are not supported. 
Please refer to [this issue](https://github.com/requestly/requestly/issues/1863) for further updates.

**Comment by Holokai** [comment]
Thanks for the information @nafees87n.
