### ISSUE TITLE
Default proxy port can't be changed

### ISSUE THREAD

**Issue by svenkost** [requestly/requestly#200]
I need to be able to change the default port from 8080 to another port, because 8080 is already used by an application and that can't be changed. 

I can't find any option to change the port.

**Comment by breadbrowser** [comment]
why would you need a port

**Comment by sachinjain024** [comment]
@svenkost We have completed development for this. We should be able to release this soon. cc @nsrCodes

**Comment by nsrCodes** [comment]
This is now possible in the [latest release](https://github.com/requestly/requestly-desktop-app/releases) 🎉
