### ISSUE TITLE
im using this to get Comedy World on Vyond

### ISSUE THREAD

**Issue by AshHasThickFlaps** [requestly/requestly#201]
## Summary

Im watching tutorials and they all use the 2018 version, on 2022 version where is Replace Host?

**Comment by sagarsoni7** [comment]
@AshHasThickFlaps - Sorry we don't encourage using Requestly with apps like Vyond so you would have to explore yourself. Replace Host is now called Replace String though.

**Comment by AshHasThickFlaps** [comment]
ok, idk, the only other way I can find is with node, thank you.
