### ISSUE TITLE
Redirect request pattern with request params values

### ISSUE THREAD

**Issue by manjulalog** [requestly/requestly#202]
I need to write a rule for following requirement.

Request : https://abc.com/uiservice/course/pair/77e4129f-49fc-4a1c-a1e9-81c3756c27c1

Should redirect to : https://cde.com/uiservice/course/pair/77e4129f-49fc-4a1c-a1e9-81c3756c27c1

Note : 77e4129f-49fc-4a1c-a1e9-81c3756c27c1 is dynamic value

**Comment by sachinjain024** [comment]
@manjulalog There are two ways to do this.

You can try the Redirect Rule like this
Request URL --> Matches WildCard --> https://abc.com/uiservice/course/pair/*
Destination --> https://cde.com/uiservice/course/pair/$1

You can use a Replace String Rule like this
Replace https://abc.com/uiservice/course/pair
With https://cde.com/uiservice/course/pair

once you create the rule, you can use the Test this rule feature to try out the URLs

**Comment by sachinjain024** [comment]
@manjulalog Is your issue resolved? Can we close this ticket?

**Comment by sachinjain024** [comment]
Closing the issue for lack of activity.
