### ISSUE TITLE
bug: Requestly Chrome panel shows details for the wrong request

### ISSUE THREAD

**Issue by davidblumenthal** [requestly/requestly#2033]
### Describe your issue?

In the requestly Chrome developer tools panel, when I click on a request to see details about it, it shows information from a completely different request.

Note in the screenshot I've clicked on a graphql request on the left, and on the right it's showing me "Request URL:https://d9zgl8ybjt160.cloudfront.net/one-host/primary/iflstaging/vendors.e7c94775040044252a8a.js"

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/0f749415-fe26-4675-a3b0-3c522b38f510">

### Repro steps

Just open the Chrome developer tools.  I see this even with all Requestly rules turned off.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome 126.0.6478.185, Mac 14.5 (23F79)

### Requestly Version

v24.7.23

### Error screenshot

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/0f749415-fe26-4675-a3b0-3c522b38f510">

**Comment by nafees87n** [comment]
Hi @davidblumenthal 
Thanks for logging this. We can confirm that there is mismatch between a request and its details when the search bar is used. 
We will fix it in the next extension release.

**Comment by nafees87n** [comment]
Hi @davidblumenthal 
Fixed by PR: https://github.com/requestly/requestly-ui/pull/12
It will be released in the next extension release.
