### ISSUE TITLE
Extension option to remove the floating icon

### ISSUE THREAD

**Issue by matt-jolt** [requestly/requestly#2038]
This floating icon is so annoying and invasive. It always pops up in the upper right of my page and blocks functionality that I frequently use. I don't think it offers me anything, I can see the status in the extension icon of the toolbar.

PLEASE add a setting to hide this.
![Screenshot 2024-07-31 at 10 46 34 AM](https://github.com/user-attachments/assets/82ab0e06-4e28-4751-a3b0-c2585f497cde)

**Comment by wrongsahil** [comment]
Hey @matt-jolt . You can disable this `Rule Application Status` Widget by following the steps here
https://docs.requestly.com/guides/disable-rule-application-status-widget
