### ISSUE TITLE
Couldn't verify email

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#204]
## Expected Behavior

Verification email not working properly. 

## Current Behavior

![image](https://user-images.githubusercontent.com/3108399/169292442-2fdc225a-1f05-4744-b035-245535d86926.png)

**Comment by sachinjain024** [comment]
@echo-sg Can you please check if you are able to reproduce this issue?

**Comment by echo-sg** [comment]
checking the same

**Comment by sachinjain024** [comment]
@sagarsoni7 Is this issue fixed along with the reset password bug we fixed recently?
