### ISSUE TITLE
Support option to inject scripts only in the main document

### ISSUE THREAD

**Issue by nafees87n** [requestly/requestly#2053]
Script rules are currently applied to all documents on a page, including those within iframes. This leads to the scripts being injected unintentionally in the iframes as well.

**Comment by nafees87n** [comment]
# Possible Workarounds

## Use `window.self` to inject the script in only the top level main document

```html
<script type="text/javascript">
  if(window.top===window.self){
    // Add code here   
	console.log("Hello World");
  }
</script>
```

### Downsides

1.  This workaround can only be used with custom javascript code and not work when injecting remote code using URL.

**Comment by wrongsahil** [comment]
This is now supported. You can now use [advance filters](https://docs.requestly.com/general/http-rules-(modify-traffic)/advanced-usage/advance-targeting) to inject script in main frame or iframe only
