### ISSUE TITLE
Clicking on the Rule in traffic table in Android debugger takes me to 404

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#210]
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/3108399/173814199-6df8ce58-a8c3-476a-aed3-dc6609a01639.png">

When I click on the Response Rule icon in the last column, It takes me to the 404 page.

**Comment by nsrCodes** [comment]
This bug was also present inside the Preview section in the bottom panel. Both have been fixed, closing.
