### ISSUE TITLE
How to do advanced string mapping mapping in requestly redirect/rewrite rule?

### ISSUE THREAD

**Issue by qkhanhpro** [requestly/requestly#212]
Right now I have an URL like this http://my-app.com/api/item/{some-id}/detail?some-other-query-param=true

How can I write a redirect or string replace rule that allow me to forward this request to 
http://my-local-app.com/detail/{some-id}?some-other-query-param=true

So basically there are 2 piece of information I would like to perserve / pass through - that is the {some-id} and the ?some-other-query-param=true

I guess maybe Regexes can help with this but I can find no documentation :(

Something like this ( image just to illustrate )
![image](https://user-images.githubusercontent.com/10443536/177123171-bd9740ba-7936-463a-9438-be3fb67c1c66.png)

**Comment by lazyvab** [comment]
@qkhanhpro You may create a Redirect rule like this:
If request URL Matches (Regex) `/http:\/\/my-app\.com\/api\/item\/(.+)\/detail\?some-other-query-param=true/ig`
Redirect to: `http://my-local-app.com/detail/$1?some-other-query-param=true`

See documentation: https://docs.requestly.io/getting-started/features/rule-operators#regex-match-operator

<img width="1440" alt="Screenshot 2022-07-04 at 5 04 47 PM" src="https://user-images.githubusercontent.com/6367566/177146702-c28754de-a564-41fa-85be-c73eef8de296.png">
