### ISSUE TITLE
Getting Request body is already used error when using Modify Response Rule

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#213]
I am not able to modify response using requestly. I am getting this error - Failed to execute 'clone' on 'Request': Request body is already used .

Here's the rule
https://app.requestly.io/rules/#sharedList/1657006586241-Nikhil-shared-list-7-5-2022

This error only happens when we add the following code 

response = await fetch(request); - this code was in my app.

When the user removed this line in the code, he didn't get the error.

**Comment by lazyvab** [comment]
I am able to reproduce the issue.
It happens when we make POST request by passing request object of `Request` type to `fetch` API.

I'm currently working on it and roll out a fix soon.

**Comment by sachinjain024** [comment]
This has been fixed so closing this ticket.
