### ISSUE TITLE
feat: pick a local path to use as destination in Redirect Rule (Support for Map local files)

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#215]
I can pick a local path in Modify Response Rule but I can't do this in Redirect Rule. This will allow me to modify the file directly on my VSCode without having to copy and paste in the Requestly editor every time I make a change.

Feature Requested by Max

**Comment by breadbrowser** [comment]
this seems useless.

**Comment by wrongsahil** [comment]
Added support for this in [v1.4.21](https://github.com/requestly/requestly-desktop-app/releases/tag/v1.4.21)
