### ISSUE TITLE
override JSON response using javascript function

### ISSUE THREAD

**Issue by MrFrazSultan** [requestly/requestly#216]
I am trying to change the value of JSON response, i am assuming that this response is dynamic and i want to change only the value of this property bpi.USD.description and i want to change the value from **United States Dollar** to **US Dollar**

**Test URL:** https://api.coindesk.com/v1/bpi/currentprice.json

**Response:**
`{
  "time": {
    "updated": "Aug 3, 2022 20:25:00 UTC",
    "updatedISO": "2022-08-03T20:25:00+00:00",
    "updateduk": "Aug 3, 2022 at 21:25 BST"
  },
  "disclaimer": "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",
  "chartName": "Bitcoin",
  "bpi": {
    "USD": {
      "code": "USD",
      "symbol": "&#36;",
      "rate": "23,342.0112",
      "description": "United States Dollar",
      "rate_float": 23342.0112
    },
    "GBP": {
      "code": "GBP",
      "symbol": "&pound;",
      "rate": "19,504.3978",
      "description": "British Pound Sterling",
      "rate_float": 19504.3978
    },
    "EUR": {
      "code": "EUR",
      "symbol": "&euro;",
      "rate": "22,738.5269",
      "description": "Euro",
      "rate_float": 22738.5269
    }
  }
}`

And I am expecting this response:

=========================
`{
  "time": {
    "updated": "Aug 3, 2022 20:25:00 UTC",
    "updatedISO": "2022-08-03T20:25:00+00:00",
    "updateduk": "Aug 3, 2022 at 21:25 BST"
  },
  "disclaimer": "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",
  "chartName": "Bitcoin",
  "bpi": {
    "USD": {
      "code": "USD",
      "symbol": "&#36;",
      "rate": "23,342.0112",
      "description": "US Dollar",
      "rate_float": 23342.0112
    },
    "GBP": {
      "code": "GBP",
      "symbol": "&pound;",
      "rate": "19,504.3978",
      "description": "British Pound Sterling",
      "rate_float": 19504.3978
    },
    "EUR": {
      "code": "EUR",
      "symbol": "&euro;",
      "rate": "22,738.5269",
      "description": "Euro",
      "rate_float": 22738.5269
    }
  }
}`

How to use the javascript function for this?

i tried this but it didn't work, i am not into JS
===========================
`function modifyResponse(args) {
  const {method, url, response, responseType, requestHeaders, requestData, responseJSON} = args;
		bpi.USD.description = {"description": "US Dollar"};
  return response;
}`

**Comment by lazyvab** [comment]
@MrFrazSultan Happy to help you on this.

The JS function should look like:
```js
function modifyResponse(args) {
  const { responseJSON } = args;
  responseJSON.bpi.USD.description = "US Dollar";
  
  return JSON.stringify(responseJSON); // could directly return responseJSON if "Content-Type" header in response was "application/json" and not "application/javascript"
}
```

Here is a shared list with this rule which you can directly import.
https://app.requestly.io/rules/#sharedList/1659590444220-Issue-216

Please note that Requestly can apply the rule only if the request is triggered from a JavaScript (like an API call) and not in browser directly.

I also created a CodeSandbox playground for you to test the rule: https://c26ptb.csb.app/

**Comment by lazyvab** [comment]
@MrFrazSultan Can you please confirm if above rule worked for you?

**Comment by MrFrazSultan** [comment]
Done, Thanks.
