### ISSUE TITLE
Shared rules/lists not working

### ISSUE THREAD

**Issue by coreyb-cbs** [requestly/requestly#217]
## Expected Behavior
When I share a rule, it should be share-able.

## Current Behavior
I am sharing a link to a shared rule but it states "Shared List does not exist". Looks like the id for the shared list is coming up as "null" in the url. https://app.requestly.io/rules/#sharedList/null-BidBarrel-routeToPR749
<img width="309" alt="Screen Shot 2022-08-10 at 10 43 18 AM" src="https://user-images.githubusercontent.com/55097986/183931474-806aacf7-a1d0-4c9c-8a7a-5985e8f99c92.png">

When I go to my "Shared Lists" I also see the following error:
<img width="331" alt="Screen Shot 2022-08-10 at 10 43 04 AM" src="https://user-images.githubusercontent.com/55097986/183931619-7ecebde7-1617-4962-bae6-80b2def7e0e6.png">

## Steps to Reproduce
click the following shared rule link:
https://app.requestly.io/rules/#sharedList/null-BidBarrel-routeToPR749

## Your Environment

**Comment by sachinjain024** [comment]
Thanks, @coreyb-cbs for logging the issue. Looking into this.

**Comment by wrongsahil** [comment]
Hey @coreyb-cbs. We have fixed the issue. Can you check now

**Comment by coreyb-cbs** [comment]
Viewing the existing shared rule url still generated an error. Generating a new shared rule url worked - I no longer see `null` in the url and the rule displays as expected.

**Comment by sachinjain024** [comment]
@coreyb-cbs I guess this might be happening for only the sharedLists that you created recently (basically having null in the URL) Can you please confirm?

**Comment by coreyb-cbs** [comment]
Yes it is only occurring from the shared rules that i created recently, when i reported this bug. Creating new share urls from the same rules is working as expected now.
