### ISSUE TITLE
Does requestly is able to capture or analyze code?

### ISSUE THREAD

**Issue by raut-rahul** [requestly/requestly#218]
Hi team,

I am very happy using requestly to run and debug things locally. But I want to know what data requestly use for their analytics. I want to request requestly in our organization before that I want to know that is there any privacy issues to use it. 

- Does requestly analyzes code?
- Does requestly captures code snippets?
- At what level requestly captures user data?

**Comment by sachinjain024** [comment]
Hey, @raut-rahul This is Sachin - Founder & CEO, Requestly. You can check out our privacy policy here - https://requestly.io/privacy/. Having said that in analytics, we capture events like rule_created, rule_deleted, mock_created, etc that give us information about the product usage. We don't analyze code, code snippets, etc. in analytics.

Requestly rules are saved to your account but we don't process them. You can always turn off the sync though. Feel free to drop me an email at sachin@requestly.io or schedule a call - https://calendly.com/sachin-rq if you'd like to discuss anything specific.

**Comment by raut-rahul** [comment]
Thank you very much for clarification :)
