### ISSUE TITLE
Desktop app open in the existing profile browser Failure.

### ISSUE THREAD

**Issue by xu20160924** [requestly/requestly#221]
## Expected Behavior
Open in the existing profile browser successfully

## Current Behavior

![Uploading image.png…]()

## Steps to Reproduce
1. When I use the extension of requestly of Chrome to modify API response, that doesn't work as expected. I've observed the execution logs that which  I want to modify the response indeed matched the rule, but the response doesn't work, it is the same as before.
2. I try to use the desktop to do that.  first of all, connecting a new profile of Chrome that modifiy API response worked, and the response surely is configured. but the problem occurred when I connect existing chrome, and then I opened the console of Chrome, I got this error:
```
main.js:1119 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app.requestly.io') does not match the recipient window's origin ('https://amiusing.requestly.io').
```

## Possible Solution (Not obligatory)

I guess maybe this is because of some conflicts or potential problems with other plugins when opened in the existing profile？
## Your Environment

Chrome Browser
- Operating System and version : MacOS Monterey  12.5
- Extension Version : 22.8.9
- Desktop App Version : 1.4.4 (1.4.4)

**Comment by sachinjain024** [comment]
@nsrCodes I guess this isn't applicable anymore. Could you please move this forward?

**Comment by nsrCodes** [comment]
This might be a problem only when intercepting an existing chrome instance that also has the Requestly extension installed.
But it is still hard to reproduce and as mentioned, isn't applicable anymore.

Closing for now.
