### ISSUE TITLE
bug: error when trying to duplicate Redirect Rule from Edit Rule screen 

### ISSUE THREAD

**Issue by tyssejc** [requestly/requestly#2212]
### Describe your issue?

Possibly related to #1818 

As a user, when I try to duplicate a rule using the dropdown on the Edit Rule screen for a Redirect Rule, I get redirected to an error screen.

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/ce19774e-dd1a-48f1-9b45-654ecae0fbb3">

<img width="665" alt="image" src="https://github.com/user-attachments/assets/e20c0195-0fd2-4c12-a628-1f3a6b1d2f40">

Console log output
<img width="952" alt="image" src="https://github.com/user-attachments/assets/cb4fc3b5-571e-448e-aa07-8eac17628e2c">

Thanks team!

### Repro steps

1. Open Chrome
2. Click Requestly extension icon (using v24.9.18)
3. Click blue "Open App" button
4. Click an existing HTTP Rule (I tried with a Redirect Rule)
5. On the Edit Rule screen, click the **More** ⬇️  dropdown to the right of the pin 📌 icon
6. From the dropdown, select **Duplicate**

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

macOS 15.0, Chrome 129.0.6668.60 (arm64)

### Requestly Version

v24.9.18

### Error screenshot

<img width="665" alt="image" src="https://github.com/user-attachments/assets/e20c0195-0fd2-4c12-a628-1f3a6b1d2f40">

**Comment by nafees87n** [comment]
Thanks for reporting. We will fix it as soon as possible

**Comment by nafees87n** [comment]
Hi @tyssejc 
The fix has been deployed

**Comment by tyssejc** [comment]
Already?! That has got to be a world speed record. Thanks @nafees87n !
