### ISSUE TITLE
Some request headers like Host,Cache-Control cant be modify in Chrome 

### ISSUE THREAD

**Issue by superguy021** [requestly/requestly#222]
## Expected Behavior

Hi, can I modify request header like Host, Cache-Control? I tried but not useful for these two headers. Some others seem to be ok. Is there any thing I'm not realized? Look forward to your favourable reply

## Current Behavior
I modified reuqest header Host， but there is no effect，so does Cache-Control，but add header or modify headers like Accept-Encoding is ok.

## Your Environment
Chrome 104.0.5112.102 64
Win10 21H2
Requestly 22.8.9

**Comment by sagarsoni7** [comment]
[chrome.webRequest](https://developer.chrome.com/extensions/webRequest.html) and [chrome.declarativeWebRequest](https://developer.chrome.com/extensions/declarativeWebRequest.html) do not allow changing cache headers.
Even if we override the header, it will appear as changed but the browser won't respect it.
