### ISSUE TITLE
JSON format can be supported in the text box？

### ISSUE THREAD

**Issue by chenjunxyf** [requestly/requestly#224]
now can not format json in the text box.

it will be very convenient to format json automatically when edit the mock data.

**Comment by sachinjain024** [comment]
Hey @chenjunxyf -- We have made this change a couple of weeks. Could you please try again and see if the new editor helps?

cc - @RuntimeTerror10

**Comment by sachinjain024** [comment]
This is complete so closing this ticket. Users can now Pretty-Print the JSON in Script Rule & Modify Request Body & Modify Response rule.
