### ISSUE TITLE
Request: A place to ask questions?

### ISSUE THREAD

**Issue by velle** [requestly/requestly#2258]
You have  a *Discussions* section on your github, but it seems that I can't create a new discussion/post there. I am able to respond to existing discussions though. 

Is this an error i the setup? Or is it a deliberate choice that only some users are able to create new discussions? What does it take for me to be able to ask a question? :)

Sincerely, Thomas

**Comment by nsrCodes** [comment]
Hey @velle thanks for pointing this out. We have updated the settings for discussions to allow anyone to be able to create new discussion topics. 
Also feel free to tag me or anyone from the team when you do so.
