### ISSUE TITLE
Requestly does not Work when a page javascript code calls some non-standard port number

### ISSUE THREAD

**Issue by hmpmarketing** [requestly/requestly#226]
## Summary

Trying to load ct.pepperstone.com to replace the response of one file.

There are a couple of calls to a domain with port 5443 underneath, when requestly is on, these return a timeout in the Chrome console (seems when requestly is on, the calls to the domains with the port above simply time out). I have tried with both Chrome and Firefox and the same issue appears.

if you try to load ct.pepperstone.com without requestly, it works fine

Any way around this?

**Comment by sachinjain024** [comment]
Hey, @hmpmarketing Thanks for reporting the issue. A couple of questions before we can look into this -- 
1. Have you set up any modification rules on the underlying calls with the 5443 port?
2. If you have Requestly turned on without any modifications, do you still see the issue?

If you have any modification rules, can you please share the rule with us?

**Comment by sachinjain024** [comment]
@nsrCodes Can you please move this forward?

**Comment by nsrCodes** [comment]
Hey @hmpmarketing 
I could not reproduce this. The website you mentioned loads as expected even when intercepted by Requestly
Also could not find any calls to port `5443` when trying to connect to `ct.pepperstone.com` from both firefox and chrome.

Could you please check if the issue still persists and if so can you provide any further details that could help us reproduce this?

In the meantime, there is currently no way to stop Requestly from engaging with a particular port as it seems like a very niche use case. But we will look into implementing this if the need arises.

**Comment by nsrCodes** [comment]
It is now possible to change the port on which Requestly runs its proxy. 

To edit this: 
1. Click on the settings icon on the top right
2. Enter the port number you want the app to use for the proxy under the `Set default proxy port` setting.
3. Click the `Update` button and Restart the app
