### ISSUE TITLE
auto update and new tabs opening on auto update on their own

### ISSUE THREAD

**Issue by mhmm555** [requestly/requestly#229]
## Summary
hi i want to know if theres a way to stop a new tab from automatically opening up in the browser every time the extension auto updates, and if there is not then is there a way to stop the extension from auto updating all together? also would you be able to tell me if i install the extension files locally through the crx file instead of from chrome if that would stop the extension from auto updating?

**Comment by sachinjain024** [comment]
Hey, @mhmm555 Thanks for reporting this. A new tab is opened only once a month types to make users aware of the latest features in the product. Is it happening on every browser restart?

**Comment by sachinjain024** [comment]
@mhmm555 The frequency will be at max once a month and that too only with any major updates in the product. Chrome automatically updates all the extensions to the latest version. This happens to all the extensions you have on your machine.

**Comment by sachinjain024** [comment]
Thanks, @mhmm555! Closing this for now. Feel free to reopen if you have any follow up question.
