### ISSUE TITLE
Unable to access requestData in Modify Response Rule

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#231]
Using the Modify Response Rule, we are unable to access requestData it is always returning null

More context:

- the request is a POST request that has a body.
- the endpoint is an existing (real) endpoint
- using Modify Request Body Rule for the same request, we can access the requestData and change it successfully
- the issue is on the latest desktop app using chrome new profile

**Comment by wrongsahil** [comment]
Fixed in https://github.com/requestly/requestly-desktop-app/releases/tag/v1.4.13
