### ISSUE TITLE
Desktop App breaking nextjs server socket connection

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#232]
## Current Behavior

I believe that this method is breaking the web socket connection to our local development server, more specifically to webpack hmr (with nextjs server) the error is shown as follows:

<img src="https://user-images.githubusercontent.com/16779465/200104713-ba0def07-5b06-4ecf-babb-6bb8d6bc5da6.png" width="400">

## Steps to Reproduce

I belive using a create next js app locally + using the requestly desktop app with a new chrome profile + navigating to the page should trigger this error

## Your Environment

- Operating System and version :
- Extension Version :
- Desktop App Version :

**Comment by nsrCodes** [comment]
The web socket connection is working fine inside the proxy.
The problem is with the encoding of the messages being passed through the socket

<img width="1127" alt="websockets-next-error" src="https://user-images.githubusercontent.com/57226514/200808657-1cdbe635-0463-49fd-86c5-27cb62b5886d.png">
