### ISSUE TITLE
Debug Android apps with SSL Pinning

### ISSUE THREAD

**Issue by antoinerzad** [requestly/requestly#235]
Hello do you know if it is possible to use requestly on android on an application that does not belong to me and which has security (ssl pinning) thank you for your help

**Comment by wrongsahil** [comment]
Hey @antoinerzad. 
Unfortunately no. Requestly Android SDK as well as Desktop app don't work with apps which have SSL pinning. 

But i've seen people decompile the app and remove the SSL pinning. And then intercept the Network Requests (Not 100% sure about this though)
