### ISSUE TITLE
Collections variables support in API Client

### ISSUE THREAD

**Issue by RuntimeTerror10** [requestly/requestly#2351]
Currently there are only global level environments which the requests can consume. 

**Use Case**
 Ideal for API testing within a specific collection, where variables only pertain to the particular requests in that collection.

**Benefits**
* Better organization and encapsulation.
* Easier to manage variables on a per-project or per-collection basis.
* Avoids conflicts with other collections or environments.

**Comment by asachanfbd** [comment]
Collection variables [documentation](https://docs.requestly.com/general/api-client/environments-and-variables#how-to-create-collection-variables).
