### ISSUE TITLE
Add support for modifying requests in Web Sockets

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#238]
Right now only HTTPs requests can be modified, please see if this is possible to modify request & response headers for Web Sockets too.

Exact feature request here 

<img width="620" alt="image" src="https://user-images.githubusercontent.com/3108399/203947154-8a47310b-2ece-4239-a64a-45ac717b65f6.png">

**Comment by lazyvab** [comment]
@sachinjain024 Yes this is possible to do. I will include the fix in next release.

**Comment by sachinjain024** [comment]
@lazyvab Will this also be possible in MV3?

**Comment by lazyvab** [comment]
@sachinjain024 Yes, it will be supported in MV3 as well.

**Comment by sachinjain024** [comment]
great, lets release this today 🥳

**Comment by sachinjain024** [comment]
This is fixed and the latest version is available in Chrome Store now.

**Comment by sachinjain024** [comment]
Here's a proof of Headers working on WebSocket Requests 

## Link of the Rule

https://app.requestly.io/rules/#sharedList/1669384044775-Web-socket-Header-Rule-Testing Click on Import

## Website -- nimo.tv

![image](https://user-images.githubusercontent.com/3108399/204076565-aed0407f-8b60-4527-a8f7-b8a476d91639.png)

## Network Tab

![image](https://user-images.githubusercontent.com/3108399/204076587-71d10987-096d-44a8-b223-91850d1066ca.png)
