### ISSUE TITLE
Suggestion: Indication that a rule is not saved

### ISSUE THREAD

**Issue by mallowigi** [requestly/requestly#239]
Quick suggestion: what about setting an indication when a rule is edited but not saved? It's not particularly visible, and many times I was dumbfounded that "requestly isn't working!" only to find out that it's just not saved.

Maybe add a banner at the top, or something on the tab, I don't know.

**Comment by wrongsahil** [comment]
Thanks for the suggestion @mallowigi :D. I've faced this myself many times.

We'll try to incorporate this in upcoming release. Stay Tuned :D

**Comment by sachinjain024** [comment]
@nafees87n When can we release this?

**Comment by nafees87n** [comment]
@mallowigi thanks for the suggestion. 
We have released this. Please try it out and feel free to suggest any improvements. :)

**Comment by mallowigi** [comment]
It's too subtle. Better than nothing, but I think modifying the Tab name would be better, as this would show up if I am in another tab.

Look what Refined Github did:

<img width="242" alt="CleanShot 2022-12-16 at 18 51 55@2x" src="https://user-images.githubusercontent.com/5015756/208148689-a867d4e5-d7ce-42a4-8e63-71d2c7ed4055.png">

**Comment by lazyvab** [comment]
@mallowigi This is a good feedback. We have noted it and will definitely improve the experience sometime in near future.

For now, we will close this ticket as we have implemented at least one way to detect and indicate unsaved changes in UI and also warn users on exiting rule editor if user forgot to save changes.

Please feel free to reopen or log a new ticket for further suggestions.

**Comment by lazyvab** [comment]
@mallowigi We will track your suggestion in a separate ticket: https://github.com/requestly/requestly/issues/254.
