### ISSUE TITLE
URL path not fully visible

### ISSUE THREAD

**Issue by Shathath** [requestly/requestly#241]
![image](https://user-images.githubusercontent.com/23003918/204074219-b31d686b-d289-4a46-b214-906ce26a3fab.png)

can we show the URL as much as possible here we still enough amount of space in the back.

**Comment by sachinjain024** [comment]
@rohanmathur91 It should be a minor fix. Can you please see if we can fix it this week?

**Comment by rohanmathur91** [comment]
@sachinjain024 It's done, closing the issue.
