### ISSUE TITLE
Resizable text area

### ISSUE THREAD

**Issue by dmevt** [requestly/requestly#242]
Current behavior:
![image](https://user-images.githubusercontent.com/58940699/204085770-1df7fa4a-b130-4dc7-9259-4d1cc0248359.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/58940699/204085919-4dd4a45d-df60-42d0-940d-a7386f282912.png)

**Comment by sachinjain024** [comment]
Thanks, @dmevt for logging this issue. This is really helpful. We are running with reduced bandwidth for the next 2 weeks. We will pick this up at the earliest after that.

**Comment by dmevt** [comment]
Super, thank you 🙂

**Comment by sachinjain024** [comment]
@lazyvab Possible to pick up this usability issue in this sprint?

**Comment by sachinjain024** [comment]
@wrongsahil Can you please check if this is possible to pick up in this/next sprint?

**Comment by wrongsahil** [comment]
Hey @dmevt. We have added the support for resizing editors. 

Closing this. Feel free to open another issue if you have any other suggestions.
