### ISSUE TITLE
Delay field inside 'Modify API Response Rule'

### ISSUE THREAD

**Issue by dmevt** [requestly/requestly#248]
Current behavior:
![image](https://user-images.githubusercontent.com/58940699/205680890-84fb5772-705e-43e5-a99a-85b8c0c51b2a.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/58940699/205680939-bf2ea9ae-fe8b-4cd1-9603-f97cbecd241b.png)

This will make it possible to quickly change the values of endpoints in order to test loaders because almost every endpoint can have a loader and it will take a long time to create a separate rule with a delay.

**Comment by sachinjain024** [comment]
Thanks, @dmevt for logging this feature request. If this helps, you can create a separate delay rule with multiple pairs like this

<img width="844" alt="image" src="https://user-images.githubusercontent.com/3108399/205688442-669d20b5-e72c-4e9f-af53-ca953fee74be.png">

Or, you can also create a rich WildCard/Regex pattern to match all/relevant API URL patterns. Does this help?

**Comment by sachinjain024** [comment]
@dmevt Can we close this ticket?

**Comment by wrongsahil** [comment]
Closing this ticket due to lack of activity. Feel free to reopen this ticket incase you still facing this
