### ISSUE TITLE
Extension Manifest V3 migration

### ISSUE THREAD

**Issue by lazyvab** [requestly/requestly#250]
# IMPORTANT

This ticket has become stale and we have provided most of the features in MV3. Please follow the updates in this ticket - https://github.com/requestly/requestly/issues/1690 for MV3 roll out.

-----------

As Chrome [documentation](https://developer.chrome.com/docs/extensions/mv3/intro/) introduces:

> Manifest V3 represents one of the most significant shifts in the extensions platform since it launched a decade ago. Manifest V3 extensions enjoy enhancements in security, privacy, and performance; they can also use more contemporary open web technologies such as service workers and promises.

Chrome is soon going to phase out the support for Manifest V2 extension. [Read more](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)

But the good news is that Requestly is well prepared for the revolutionary migration, keeping its users unaffected to the most extent. Below is the list of all features that are changing or being newly introduced or dropped after the manifest migration.

| Feature | Availability in Manifest V3 extension | Changes |
| --- | :---: | --- |
| Redirect Request Rule* | :white_check_mark: | - |
| Replace String Rule* | :white_check_mark: | 1. The final URL will have a query parameter `__rq_marker__`. <br>2. Multiple replace modifications on same URL will not work unless Request URL is left empty. |
| Query Param Rule* | :white_check_mark: | - |
| Cancel Request Rule | :white_check_mark: | - |
| Modify Headers Rule | :white_check_mark: | - |
| User-Agent Rule | :white_check_mark: | - |
| Delay Network Requests Rule | :last_quarter_moon: | Delay in AJAX requests is not supported yet. (:construction: Under development) |
| Insert Scripts Rule | :white_check_mark: | In MV3, Chrome enforces [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) rule set on webpage to execute remote scripts. To reliably apply the rule, extension will remove CSP header from the webpage where rule is to be applied. This setting can be turned off by the user in the rule editor itself. |
| Modify API Response Rule | :white_check_mark: | - |
| Modify Request body Rule |*Coming Soon* | - |
| Rule Source Filters - Page URL condition | :x: | In MV3, rules are applied using DNR APIs and not JS.<br>Also, DNR API does not allow condition on page URL. |
| Rule Source Filters - Resource Type | :white_check_mark: | - |
| Rule Source Filters - Request Method | :white_check_mark: | - |
| Green Extension icon on rule applied | :x: | In MV3, there is no API which notifies when a rule is applied. |
| Rule Execution Logs | :x: | In MV3, there is no API which notifies when a rule is applied. |
| Console logging of rules | :x: | In MV3, there is no API which notifies when a rule is applied. |
| Requestly Devtool Panel | :x: | In MV3, there is no API which notifies when a rule is applied. |
| Rules executed in current tab :new: | :white_check_mark: | In Extension popup, there is a tab `Executed rules` which lists all rules executed in current tab. User can easily toggle their status or pin them. |
| Session Recording | :white_check_mark: | - |

:warning: *If there are multiple Redirect, Replace String, or Query Param rules defined on the same URL, only one of them will be applied. In future, we will solve this URL conflict problem by allowing users to specify `priority` with each rule. 

<hr>

We also have a BETA version of the MV3 extension on Chrome Web Store which you can install and validate if this migration affects you in any manner. 

To install, visit: https://chrome.google.com/webstore/detail/requestly-beta/hflhkgcfclhibpldaeppcmcnfkkndmhf
(The extension is accessible only via link in Chrome Web Store.)
<img width="1178" alt="Screenshot 2022-12-26 at 2 20 37 PM" src="https://user-images.githubusercontent.com/6367566/209527726-9f6329d2-e175-4b06-b268-4d10c3e742cc.png">

<hr>

Please feel free to ask questions in the comments or report an issue [here](https://github.com/requestly/requestly/issues/new/choose).

**Comment by sachinjain024** [comment]
@lazyvab Probably you forgot to share the Beta link in your ticket description.

**Comment by lazyvab** [comment]
@sachinjain024 I updated the description with the list of features and the installation link.

**Comment by sachinjain024** [comment]
@lazyvab I think we have solved for showing the rules executed at a page level and not at a request level. Is that correct?

**Comment by palashkaria** [comment]
I think having some indication that rules are applied is very important, because there have been lots of times that I was debugging something, only to realize later that Requestly rules were applied 😅

There's a potential solution here, where the "applied action count" can be displayed under the new DNR, by using [`chrome.declarativeNetRequest.setExtensionActionOptions(...)`](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-setExtensionActionOptions) 

it exposes a couple of params:

- `displayActionCountAsBadgeText: true` - shows the applied action count on the extension badge. This is what uBlock origin's MV3 experiment uses (see [this line](https://github.com/gorhill/uBlock/commit/a559f5f2715c58fea4de09330cf3d06194ccc897#diff-b788ab69a7d0431d3242ab5b74c860b770575e773521fe7f337aadb85d012fe6R7))

- `tabUpdate({increment, tabId})` - I assume this can be used to handle the count manually. Haven't tried it so not sure, but looks promising

Hope this helps!

**Comment by lazyvab** [comment]
@palashkaria I agree that the indication is required and in the current (Manifest v2) extension, we already do multiple things:

1. Make extension icon look green
2. Log event in browser console
3. Show the executed rule in extension popup under "Executed Rules"
4. In browser devtool "Requestly" panel, we show the request and the modification applied

We could achieve #3 above in MV3 extension but not others as we don't get any event when rule gets applied in packed mode.
Chromium developers are considering this requirement and probably going to support [chrome.declarativeNetRequest.getMatchedRules](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-getMatchedRules) when the user has enabled "Developer mode" on the extensions page. ([ref](https://bugs.chromium.org/p/chromium/issues/detail?id=1054752#c21))

 I already tried `chrome.declarativeNetRequest.setExtensionActionOptions` function once but it could be used only if you want to show a count badge. But here we would rather like to show a custom badge or make icon green.

#### Q. Why we cannot show the default count badge shown by DNR?

- The count shown is the number of DNR actions executed. And one Requestly rule is mostly implemented using more than one DNR dynamic action. So, the default count will never be a clear indication of how many user rules were actually applied.
- I tried using `tabUpdate({ increment: 0 })`, so it could always show `count=1` whenever there is some rule applied in page, but somehow `0` doesn't seem to be acceptable and the count still incremented with step=1.
- We already show a `REC` badge when Session is being recorded. But this can be replaced with a different extension icon.

<hr>

@sachinjain024 
>I think we have solved for showing the rules executed at a page level and not at a request level. Is that correct?

Yes, that's correct. In future, if Chrome starts supporting [chrome.declarativeNetRequest.getMatchedRules](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-getMatchedRules) with "Developer mode" enabled, we would find a solution at request level.

**Comment by palashkaria** [comment]
I think "number of rules applied" would be an even better indicator than just turning the icon green, as it can help me figure out if multiple rules have been applied when I didn't intend to; or if too few have been applied

**Comment by lazyvab** [comment]
@palashkaria I agree but it's currently impossible to map "number of DNR rules applied" to "number of requestly rules applied", as single requestly rule may translate to multiple DNR rules.

**Comment by palashkaria** [comment]
Got it, no clue about the internals so wouldn't know about the first part. Second part – yup, as I see there's only a dev mode hook.

**Comment by nvitaterna** [comment]
> Modify Request body Rule | Coming Soon

Is there any news regarding this? As it currently stands manifest v3 does not allow modifying the body of a request (or response) at all.

**Comment by sachinjain024** [comment]
Hey @nvitaterna Modifying Request Body & Modifying Response has been implemented in our Manifest V3 version. Our current MV3 version is rolled out to 10% of the user base. 

Here's the latest issue showing the updates of MV3 rollout - https://github.com/requestly/requestly/issues/1690

**Comment by sachinjain024** [comment]
Closing this issue. Please follow up on https://github.com/requestly/requestly/issues/1690
