### ISSUE TITLE
feature_request: Support Rule creation from Session Replay Traffic Table

### ISSUE THREAD

**Issue by adoin** [requestly/requestly#255]
For current, we can use the record to list all requests.
Why not pop menus to quickly modify specific network?
![Img](https://s2.loli.net/2022/12/18/RiQv7MeJWmSA8Gt.png)
Right click menu{
    create modification on current response,
    create modification on current request,
    ...and so on
}

**Comment by rohanmathur91** [comment]
Hi @adoin, this is really a good suggestion, we will try to add this support.

**Comment by sachinjain024** [comment]
@adoin -- In fact, @lazyvab is already experimenting with the Idea of showing Network traffic in Requestly developer tools and allowing developers to select a request/response and create modification rules straight from there. 

But this is super helpful to know that you're also thinking along these lines.

May I ask what did you expect when trying session recording and was that helpful?

**Comment by adoin** [comment]
It really helpful for me.
As I sugguested I hope requestly can do modification easier, for example, right click a recording network, choose modify response, 'static' tab showing current response data, 'code' tabs showing sample code for current response code such as&nbsp;
function modifyResponse(args) {
&nbsp; const {method, url, response, responseType, requestHeaders, requestData, responseJSON} = args;
&nbsp; // Change response below depending upon request attributes received in args
&nbsp; return JSON.stringify({
&nbsp; &nbsp; "code": 0,
&nbsp; &nbsp; "data": {
&nbsp; &nbsp; &nbsp; "userId": 363902178,
&nbsp; &nbsp; &nbsp; "userRoles":[1,2],
&nbsp; &nbsp; &nbsp; "isFans": 1,
      "books":[
      {id:1,name:'abc',desc:'xxcccczzz'},  
      {id:2,name:'def',desc:'qweqweqwe'}, 
      {id:3,name:'ghj',desc:'gfhfghfhg'}, 
     ]
&nbsp; &nbsp; },
&nbsp; &nbsp; "msg": "suc",
&nbsp; &nbsp; "serverTime": 1671501005831
&nbsp; });
}


This is enough for most of jobs, for my personal requirement requestly&nbsp;will be better&nbsp;if it support mock js such as allowed me using $mock as Mock.mock, but I think it's not basic requirement for others.&nbsp;




adoin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "requestly/requestly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月19日(星期一) 晚上9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [requestly/requestly] There should be a way to modify response or request easier. Such as this. (Issue #255)





 
@adoin -- In fact, @lazyvab is already experimenting with the Idea of showing Network traffic in Requestly developer tools and allowing developers to select a request/response and create modification rules straight from there.
 
But this is super helpful to know that you're also thinking along these lines.
 
May I ask what did you expect when trying session recording and was that helpful?

**Comment by rohanmathur91** [comment]
@adoin this is live, closing the issue.
