### ISSUE TITLE
When Requestly applies a rule, Icon turns green but nothing is shown in Console

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#258]
## Expected Behavior

When Requestly applies a rule, earlier it used to show what exactly requestly modified on the page with the Rule Name and the request URL details but now it is not shown anymore. For reference, the feature was mentioned in #203 and #207.

## Current Behavior

Nothing is shown in the console. The icon does turn green but console logs are not shown.

**Comment by sachinjain024** [comment]
To give you some context, I used a Header modification rule on httpbin.org/headers. Added a custom header, I was able to see the custom header there, icon also turned green but console log was not visible.

**Comment by lazyvab** [comment]
@sachinjain024 It is a known limitation with console logging of rule execution. 
If there is a rule applied on the very first URL (page URL), the HTML document is not fetched by then and our content scripts are not available to capture the execution log.

Any rule applied after document starts loading should still be seen in console logs.

**Comment by lazyvab** [comment]
@sachinjain024 This has been fixed in extension `v23.3.3`. Now the modifications on top URL can be seen in both extension popup and browser console. Closing the ticket.
