### ISSUE TITLE
Modify requests from DevTools

### ISSUE THREAD

**Issue by ncstrause** [requestly/requestly#262]
I'm using Requestly to add a header to all requests to a given host. It seems like requests for source maps from Chrome DevTools may not have the header because those requests are failing as if they weren't modified.

I'm seeing errors in the console like
> DevTools failed to load source map:...

Is Requestly supposed to be modifying requests from DevTools?

**Comment by sachinjain024** [comment]
Hey Nick, Thanks for opening the issue. Actually, It looks like the modern browsers Chrome & Firefox don't show the SourceMap HTTP requests in Network panel and they are not also passed to Chrome extensions for any modifications and hence you are not able to modify the headers for source map URLs.

However, you can use our open-source desktop app (Available on all platforms - Mac, Windows & Linux) and launch a browser and then do your testing. Download desktop app from here - https://requestly.io/downloads

Here's a quick youtube video that I created for you - https://youtu.be/Fiz9I2p-QWY

Please have a look and let me know if you are able to solve this. Happy to help further.

**Comment by ncstrause** [comment]
Thanks for the quick and thorough support. At this point just knowing that this is working as expected is enough for me to consider this solved. Source maps are not a critical use case but I wanted to solve the issue if possible.

**Comment by sachinjain024** [comment]
Not possible with Chrome extension due to technical constraint posed by the browsers but if you want to solve this problem in future, checkout the video and how standalone app can help. 

Thanks so much for your prompt response and closing this issue. Really appreciate it.
