### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by trickpattyFH20** [requestly/requestly#263]
Would you consider making the code for this open source in case this project ever goes away?
I'd love to have a backup fork of this.

**Comment by sachinjain024** [comment]
Hey, This is Sachin - Founder & CEO, Requestly. Thanks for reaching out and expressing your concern. We're a startup and I don't think/see we are going away anywhere for atleast next 4 years or so. Best case - Never.

Having said that, we've already started moving into open-source e.g.
- We're already considering [Manifest V3](https://github.com/requestly/requestly/issues/250) version to be open-source which should be rolled out in tentatively 5-6 months as per Chrome deadline for manifest v2
- We recently build Interception & Modification capabilities in Android app through native SDK which is fully open-source - https://github.com/requestly/requestly-android-sdk
- Our standalone desktop app is open-source - https://github.com/requestly/requestly-desktop-app

Feel free to drop me an email at sachin at requestly.io or schedule a time on my calendar - https://calendly.com/sachin-rq if you need to discuss further on this.

Always there to support our users!

Best
-SJ
