### ISSUE TITLE
feat: modify response immediately without waiting for server response

### ISSUE THREAD

**Issue by larkob** [requestly/requestly#266]
I'm using requestly to mock API responses for some very time-consuming API calls, and was hoping that the mocked response would be available immediately, but it turned out that requestly is waiting for the server to respond before providing the mocked response.

I'd like to ask for an option to disable the wait for a server response. It'd be nice if this could be a global setting, applying to all modified response rules, but it'd also be ok if I had to set this option for each rule individually.

**Comment by wrongsahil** [comment]
Hey @larkob. Yes right now it is not possible to return the response directly from the Response Rule. But it'll be good options to have. I'll add this to our bucket list. 

But this should be possible using Redirect Rule. You can create a new mock with the response and then redirect the API request to this mock. This should redirect the request to the new response without waiting for the response from the server.

**Comment by lazyvab** [comment]
We have picked this up and will solve it in the next few days. 

cc: @larkob

**Comment by lazyvab** [comment]
@larkob , @stevebertan - This is now possible in extension version `23.6.5` and desktop version `1.5.4`.

In the `Modify API Response` rule editor, there is a checkbox below the code block which has to be enabled to direct Requestly not to make the original request to serve the static response.
 
![image](https://github.com/requestly/requestly/assets/6367566/72a482f8-1ad2-404c-abfd-12ec35976ddb)

If status code is not specified, it will be `200` by default.

I'm closing the issue, but please feel free to ask questions or reopen it if the expectations are not met.

**Comment by stevebertan** [comment]
This is great! 🎉
