### ISSUE TITLE
bug: Unable to clear the Method filter in Modify API Response Rule

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#267]
### Describe your issue?

UI Issue described in the screenshot below

### Repro steps

N/A

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

Latest

### Error screenshot

Method filter gets cleared by clicking on the cross in the green circle but not by clicking on cross in the red circle

<img width="789" alt="Screenshot 2023-01-11 at 10 08 37 AM" src="https://user-images.githubusercontent.com/3108399/211719024-309f5000-31ae-460c-b2b5-22e4777a1e7a.png">

**Comment by sachinjain024** [comment]
I think the cross in the red circle is redundant, we can simply remove it and we can live with the green circle. Also the cross in individual method selected isn't visible clearly.

**Comment by lazyvab** [comment]
@sachinjain024 Fixed the issue.
Inclusions:
- Removed clear button from multi-select dropdown.
- Fixed color contrast in selected pills, as per dark scheme.
- Added a "Close" button in dialog footer.
