### ISSUE TITLE
bug: File uploads seem to be broken

### ISSUE THREAD

**Issue by Bluscream** [requestly/requestly#271]
### Describe your issue?

Whenever i hook the system in requestly all file uploads break/fail:

Here's the request in requestly:
```
curl --request POST \
 --url https://api.imgur.com/3/upload \
 --header 'accept-encoding: gzip' \
 --header 'amiusingrequestly: true' \
 --header 'authorization: Client-ID d297fd441566f99' \
 --header 'connection: Keep-Alive' \
 --header 'content-type: multipart/form-data; boundary=--------------------8daf4216c724c8f' \
 --header 'host: api.imgur.com' \
 --header 'user-agent: ShareX/14.1.0' \
 --data '----------------------8daf4216c724c8f
Content-Disposition: form-data; name="image"; filename="Adguard_ZzhIIMZEJq.png"
Content-Type: image/png

�PNG

```

Here's ShareX's error modal:
```

Imgur upload failed: (400) We don't support that file type!

Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/upload

Status code:
(400) Bad Request

Headers:
connection: close
x-post-rate-limit-limit: 1250
x-post-rate-limit-remaining: 1238
x-post-rate-limit-reset: 3204
x-ratelimit-clientlimit: 12500
x-ratelimit-clientremaining: 12500
x-ratelimit-clientreset: 86400
x-ratelimit-userlimit: 500
x-ratelimit-userremaining: 500
x-ratelimit-userreset: 3600
x-served-by: cache-hhn-etou8220024-HHN
x-cache: MISS
x-cache-hits: 0
x-timer: S1673471763.354511,VS0,VE672
access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
access-control-allow-origin: *
access-control-allow-credentials: true
x-frame-options: DENY
access-control-allow-headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
transfer-encoding: chunked
Accept-Ranges: bytes
Content-Type: application/json; charset=utf-8
Date: Wed, 11 Jan 2023 21:16:04 GMT
Server: cat factory 1.0

Response text:
{"status":400,"success":false,"data":{"error":"We don't support that file type!","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
``` 

### Repro steps

1. Open the requestly app
2. Hook the system (even with all rules disabled)
3. Try uploading a file on github or sharex for example

### What Requestly tool were you using?

- [X] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11

### Requestly Version

Desktop: Does not show (downloaded today) | Chrome: 23.1.9

**Comment by wrongsahil** [comment]
Hey @Bluscream. Thanks for the bug report.

I'm able to reproduce the issue only on Desktop App with `System Wide` proxy or with any app launched from Requestly Desktop App. 
Can you confirm whether it is happening with Chrome extension too as i'm not able to replicate it.

**Comment by Bluscream** [comment]
Not happening with only the chrome extension

**Comment by wrongsahil** [comment]
Thanks for the update. 
We'll investigate this issue and will let you know once it is fixed

**Comment by goehls** [comment]
good

**Comment by goehls** [comment]
hi @wrongsahil  is this issue fix?

**Comment by wrongsahil** [comment]
Hey @goehls . We tried some fixes for this last time. But wasn’t able to find any success.

Is this is a blocker for you? We can give it one more try if it is

**Comment by nsrCodes** [comment]
Hey @Bluscream we finally found the cause of this issue. Thanks for the detailed report, it really helped a lot since we were easily able to consistently reproduce the bug because of it. 

The fix has been merged and should be available to you in the next release.
