### ISSUE TITLE
bug: certificate trust error when chrome launched from desktop app

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#276]
### Describe your issue?

When Chrome is launched from Requestly Desktop App, the browser shows `You connection is not Secure`

### Repro steps

- Launch New Chrome Profile from Requestly Desktop App
- Go to any https site. Eg. https://requestly.io

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac Ventura 13.0.1

### Requestly Version

v1.4.20

### Error screenshot

<img width="418" alt="image" src="https://user-images.githubusercontent.com/16779465/213619509-841c06d6-8e01-4730-b32d-803d46ce8661.png">

**Comment by nsrCodes** [comment]
this is now fixed!
