### ISSUE TITLE
bug: updated dialog in not clickable

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#278]
### Describe your issue?

Requestly Desktop App update doesn't do anything when clicked

### Repro steps

- NA

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac Ventura 13.0.1

### Requestly Version

v1.4.19

### Error screenshot

![image](https://user-images.githubusercontent.com/16779465/213671491-cc05d13a-1385-4cd7-b91e-c5c57c66c105.png)

**Comment by sachinjain024** [comment]
@nsrCodes @wrongsahil -- I got into a different upgrade flow on an older mac today. Here's the screenshot for the same 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3108399/214551336-325227fc-02e8-4214-8306-320d718d904c.png">

cc - @echo-sg

**Comment by wrongsahil** [comment]
Fixed in https://github.com/requestly/requestly-desktop-app/releases/tag/v1.4.22
