### ISSUE TITLE
Modify Response rule should override status code as soon as headers are received

### ISSUE THREAD

**Issue by lazyvab** [requestly/requestly#279]
If an API is invoked using XHR, the status should be modified immediately after response headers are received. This is when XHR client's `readyState=2`.
Whereas, currently Requestly modifies both status code and response body when XHR client's `readyState=4` i.e. the request is complete.

Ref: 

- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState
- https://github.com/requestly/requestly/issues/252#issuecomment-1400127853

**Comment by sachinjain024** [comment]
@lazyvab -- I know there are certain tech limitations when working with the Chrome extension. Will @mdpratt be happy to use the standalone app and launch a new chrome instance for testing?

**Comment by mdpratt** [comment]
I'll make use of the desktop app, though it would be nice (if possible) to have this in the developer extension.

I would recommend though that these limitations be added somewhere in the extension (near to the field) so that other users don't get confused about functionality that seemingly "doesn't work" -- when in fact it's other technical limitations.

**Comment by lazyvab** [comment]
@mdpratt I agree and we will definitely fix this in the extension. Thanks again for discovering a must-fix bug.
FYI, the desktop app is much more flexible and applies the modifications cleanly. So, worth giving it a try.

**Comment by Glidias** [comment]
Yep, i noticed requests being made that doesn't result in a complete status (eg. if i turned off the server locally, etc.) will not trigger such rules unless I use the desktop app version.

**Comment by lazyvab** [comment]
@Glidias This issue has been fixed in extension version `23.2.6`. ([How to update manually?](https://medium.com/requestly/how-to-update-chrome-and-firefox-extensions-manually-29de9798f646))

Please confirm if it works for you.

**Comment by lazyvab** [comment]
@mdpratt  This issue has been fixed in extension version `23.2.6`. ([How to update manually?](https://medium.com/requestly/how-to-update-chrome-and-firefox-extensions-manually-29de9798f646))

Please confirm if it works for you.

cc: @Glidias

**Comment by Glidias** [comment]
Nope. I updated...But it doesn't seem to work for me still. I think my issue is actually a different case particularly because I am running on both a  localhost URL and also the site by a service worker handler which could be additional factors causing it to not work?

**Comment by lazyvab** [comment]
@Glidias Yes, yours seems a different case. If possible, can you please log a new issue with more details like screenshots, etc.?

**Comment by lazyvab** [comment]
Closing this ticket due to lack of activity. Please feel free to reopen.

**Comment by mdpratt** [comment]
Hi @lazyvab, I was away on vacation, apologies not getting back to you. I can confirm that this fix is in place! Thank you so much.
