### ISSUE TITLE
Modify Response Rule (Need more Payload Filtering Controls)

### ISSUE THREAD

**Issue by Glidias** [requestly/requestly#280]
UI needs more controls

- Allow for multiple Request payload key/value conditions.
- Allow for matching against non-string value matches . (currently, i must modify exported JSON and reimport rules again to get it to work as a non-string value) (eg. instead of `"value": "false"`)

eg.
```
 "filters": [
            {
              "requestMethod": [
                "POST"
              ],
              "requestPayload": {
                "key": "is_merchant_only",
                "value": false
              }
            }
          ],
```

**Comment by lazyvab** [comment]
@Glidias Thanks for logging the ticket. 
The request payload might not always be as simple as key-value pairs. It can also be a nested JSON or totally a different data type like typed buffers.

The support for request payload filter was specifically added to achieve GraphQL use-cases where the same endpoint can be used for different GraphQL operations and the type of operation name is actually sent in request payload. This filter would provide an easy way to target only one kind of operation at a time. Please refer to [this](https://docs.requestly.io/getting-started/modify-http-request-using-rules/modify-ajax-response-rule/mock-graphql-api-response) doc.

An alternate and more flexible way to target the rule based on request payload would be to use Programmatic (JS) mode in rule and add conditions on `requestData` argument of `modifyResponse` function.

```js
function modifyResponse(args) {
  const {method, url, response, responseType, requestHeaders, requestData, responseJSON} = args;
  
  if (requestData.is_merchant_only === false) {
    // return custom response
  }

  return response;
}
```

Do you think this solution would work for you?

**Comment by Glidias** [comment]
It should work for me. For intellisense and jsdocign the parameters, the below annotation is correct right?

```
function modifyResponse(args) {
  /**
   * @type {{
   *   method: string, url: string,
   *   response: any, responseType: string,
   *   requestHeaders: Object.{string, string},
   *   requestData: any,
   *   responseJSON: string | undefined
   * }}
   */
  const {method, url, response, responseType, requestHeaders, requestData, responseJSON} = args;
```
