### ISSUE TITLE
Modify Response Rule (option for Response body  to link to Mock/File Server)

### ISSUE THREAD

**Issue by Glidias** [requestly/requestly#281]
On both: Static Data, Programatically (Javascript)

On Desktop: + Local File

Also, why isn't the filtering options for payload key/value also made available for Redirect URL rule? Some things to consider here.

**Comment by sachinjain024** [comment]
@Glidias Thanks for sharing your feedback here! Loading local `file:///` based files isn't technically possible with the Chrome extension so that feature is only available in the desktop app.

Chrome extensions can't read the contents of local files stored on a disk. Does this answer your question?

**Comment by Glidias** [comment]
I know that DEsktop only supports file:///. But you also missed out the qiestion in the title... (can there be an option to link to Mock/File server like in Redirect URL Rule? 

Redirect  URL Rule should  also have similar filtering options to support filtering by payload key/value as well.

**Comment by sachinjain024** [comment]
Hey Glenn, Apologies for misunderstanding the original question. If I understand correctly you are asking two questions here --

1. Using Mock/File Server URLs directly in Redirect Rule?
2. Define an advanced filter like -- When the request payload contains a particular key/value then the Redirect Rule should be applied?

If these questions are correct, we do support the first point. You can click on the `Pick from Mock Server` button to select the URL for Mock/File Endpoint. Check the screenshot below

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3108399/214548858-360bf83f-02d1-4087-bf11-045d9b3df315.png">

For the second point, we don't have the option in the Redirect Rule as of now. Here's the reasoning

For the implementation of modifying API request payload or API response body, we override the XHR & fetch objects, and add our interceptors. Before the request is sent, we read the payload, apply the filter and give the new request payload to the server. Similarly for modifying API responses, when we get the response from the server, our interceptor modifies the response before it is read by the frontend application code.

However, Redirect Rule is implemented using webRequest API and we can't read the request payload or response body using webRequest API. 

This is why It is a bit tricky to provide request payload-level filtering in Redirect Rule.

Having said that, I'd love to understand the exact use-case from you. I might be able to suggest a better workaround in that case.

**Comment by Glidias** [comment]
GOt it, Redirect Rule is as what it needs to be.

For Modify Response, however, i guess given the way it's designed now, I can't think of any "sensible" UX way of including an an option to link to Mock/File server?  (<- since whatever that is imported in is just hardcoded text and are always unlinked) Right now, it can violate DRY in some cases due to unlinked hardcoded text response and the inability to reuse whatever i already have in my Mock/File server. As of now, the current workaround to minimise DRY is to simply capture every possible use case for the given hardcoded output and programatically determine whether to return original or mock content in the programmatic handler.
