### ISSUE TITLE
[Announcement] Requestly is now open-source 🚀🚀

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#284]
### Update Feb.21

Requestly is now open-source! Please check out the [CONTRIBUTING](https://github.com/requestly/requestly/blob/master/CONTRIBUTING.md) & [LICENSING](https://github.com/requestly/requestly/blob/master/LICENSE).

---
We're excited to announce that [Requestly, the powerful browser extension to intercept & modify network requests](https://requestly.io), will be open-source soon. Since our launch, we have been helping developers and testers worldwide to improve their development, testing & debugging workflows.

With Requestly, you get complete control over the network layer. You can easily redirect & modify HTTP requests and responses, modify the API response bodies, and much more without writing any code.

As we've grown, we've received multiple requests from our users to make Requestly open-source. We're thrilled to say that we're now finally doing it! Soon, Requestly's open-source code will be available on [GitHub](https://github.com/requestly/requestly), where you can access the complete source code, contribute to the project, and build on top of it.

This is a significant step forward for our community and us. Going open-source means we can collaborate with our users and other developers to make Requestly an even better solution for web debugging.

We got our inspiration from companies like Supabase, AppSmith, Cal, Hoppscotch, Posthog, Vercel, and many more who have contributed in their own ways to expand the open-source landscape. We are also heading towards a culture where we will be running the company in an open environment - Be it our roadmap or sprint planning.

## What's next?

We've recently launched amazing features like Team Workspaces for seamless collaboration and modifying API request payload as a rule type. In our upcoming releases, we are going to: 

- Scale team workspaces to Mock Server and HTTP sessions (record & replay browsing sessions).
- Improve the experience of debugging Android & iOS apps using the desktop app.
- Add Network Traffic Table in the browser extension and provide support to identify, monitor & validate individual network requests through plugins.
- Better support to debug your web apps on mobile browsers

We're really looking forward to the contributions from the community in the form of bug fixes, feature requests, and pull requests. Star us on [GitHub](https://github.com/requestly/requestly/), and stay tuned for our next update.

Happy debugging!

‍Originally published at - https://requestly.io/blog/requestly-is-going-open-source

**Comment by jo-chemla** [comment]
Quick question, long-time user of requestly here: Is there a community build of Requestly - either the desktop app or the browser extensions? 
 - This would allow to make the desktop app available via a requestly winget package, which would simplify install via `winget install requestly` - manifest creation is facilitated by [Komac](https://github.com/russellbanks/Komac), I can handle that + push update on every github release via a simple Github Action workflow. 
 - It would also remove the limitations like Modify API Response or Request Body + probably avoid the requirement for an account with email.
