### ISSUE TITLE
bug: Desktop App sends amiusing HTTP Request Header to the server

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#285]
### Describe your issue?

Requestly desktop app is adding a header amIusingRequestly

### Repro steps

1. Open Desktop App
2. Connect Chrome
3. Inspect any traffic and Requestly adds a request header

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

Latest

**Comment by sachinjain024** [comment]
Further Context - https://stackoverflow.com/questions/75332658/modify-http-response-on-the-user-agent-client-side/75332757#75332757

**Comment by sachinjain024** [comment]
Duplicates - https://github.com/requestly/requestly-desktop-app/issues/22

**Comment by wrongsahil** [comment]
Hey @foolioo. We're little bit busy with making Requestly completely [opensource](https://github.com/requestly/requestly/issues/284). We'll try to fix this by next week.

**Comment by wrongsahil** [comment]
Hey @foolioo. We fixed this in our latest [release v1.4.24](https://github.com/requestly/requestly-desktop-app/releases/tag/v1.4.24). Your app should get updated automatically.

**Comment by sachinjain024** [comment]
@foolioo Thanks for sharing this with us. @wrongsahil & I will investigate this tomorrow. We do not forward CONNECT as it is but instead we create a new request. The way it works is

Browser --Connects to Proxy -- Proxy connects to Server

So there is something that is not forwarded and Cloudflare is able to detect it.

**Comment by wrongsahil** [comment]
Closing this issues. Will open a new issue for this
