### ISSUE TITLE
bug: Today all my rules disappear !!

### ISSUE THREAD

**Issue by nathanredblur** [requestly/requestly#298]
### Describe your issue?

I was about to do a presentation and all my HTTP Rules disappears!! no appears anywhere, and I only can see the rules that I deleted yesterday.

### Repro steps

Just open requestly when you are just about do a quick tour about your new feature to your client and notice how all your rules has disappeared. 

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOs 13, chrome lattest

### Requestly Version

23.2.6

### Error screenshot

![CleanShot 2023-02-08 at 16 44 53](https://user-images.githubusercontent.com/1273018/217658194-045fcdd8-fe3c-4a85-a4d9-06a22cde6015.png)

**Comment by sachinjain024** [comment]
@nathanredblur Thanks for creating the ticket. Were you logged in when you created the rules?

**Comment by nathanredblur** [comment]
Of course.
