### ISSUE TITLE
Add visible logs

### ISSUE THREAD

**Issue by Samiii-AP** [requestly/requestly#304]
When a rule fails for a technical reason, Requestly remain silent and no clue helps the user find the issue.
For example:
* The URL regexp fails: no error shown
* The JSON body is not valid: no error shown

When a rule fails (global try/catch?), please log it (even if it's technical) and expose the logs to the user. If possible, raise a toaster or something that shows that a new log entry has been created either on the rule itself or globaly.

**Comment by lazyvab** [comment]
@Samiii-AP -
>The URL regexp fails: no error shown

 This issue has been fixed in https://github.com/requestly/requestly/issues/306.
