### ISSUE TITLE
Make rules links actual HTML links

### ISSUE THREAD

**Issue by Samiii-AP** [requestly/requestly#305]
In the interface, please use actual HTML links (<a href>) to allow us to open it in a new tab.

Currently, in HTTP Rules, the rules are links but impossible to open them in new tabs. This is a problem when we want to check the coherence of their content for example.

**Comment by malay5** [comment]
Could you please provide more description of what is required?

**Comment by lazyvab** [comment]
@malay5 When you are on the Rules list page, the name of rules appear as links. But you cannot open a rule in new tab using `Cmd+click` or right-click and `Open Link in New Tab`. 

This is most likely because the link is not an HTML link `<a>` and an on-click listener is attached using JS.

**Comment by wrongsahil** [comment]
Duplicate of #770
