### ISSUE TITLE
"Modify response" rule should allow empty `Response Body`

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [requestly/requestly#312]
If leave the `Response Body` empty, I will get error when click `Save` button.

![image](https://user-images.githubusercontent.com/24372782/220601534-dc64b63b-ce70-49c1-96bd-204b7f23bf7f.png)

Workaround: add a space in order to save the rule.

**Comment by sagarsoni7** [comment]
Thanks @Farsen976! I'm interested to know why did you require empty (zero-length) response body? 
Why not prefer returning `{}`, `[]`, `""` (empty string enclosed in quotes), `null`, etc instead? Zero-length response won't be valid JSON and may cause unexpected behaviour

**Comment by sagarsoni7** [comment]
If still required, how about showing a skippable warning instead?

**Comment by nafees87n** [comment]
Hello @xuan-nguyen-swe , thank you for logging this. I am curious about why you require an empty response body. As @sagarsoni7  pointed out, an empty response can sometimes lead to unexpected behaviour, especially if the client expects a specific response format.

It might be beneficial to consider returning a minimal response body, such as an empty JSON object, to ensure that the response is well-formed and the client can handle it correctly.

**Comment by nafees87n** [comment]
If your requirement is to override the status code without changing the response body, then this is not currently supported with static response. However, you can use the [Javascript mode in the response rule](https://docs.requestly.io/browser-extension/chrome/http-modifications/response-rule#programmatic-response-modification) to achieve this in the meantime.

We are aware of this limitation and are working on adding support for this feature in static response. In the meantime, please let us know if you have any further questions or concerns, and we will be happy to assist you.

**Comment by xuan-nguyen-swe** [comment]
Thanks for replying!

In real life, there are many times the api responses with an empty body. We cannot control it if it's an external service. The mocking tools should be flexible to allow any possible cases, so we can test our app with whatever api we can.

As you mentioned, I also want the case to change only response status.

**Comment by nafees87n** [comment]
@xuan-nguyen-swe Thanks for raising this issue. Closing this as this has been fixed by #425.

I have logged another ticket for overriding status code without changing response body #586. Please feel free to add suggestions over there.
