### ISSUE TITLE
Support for connecting existing profile for edge 

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [requestly/requestly#314]
`Connected Apps` in Desktop-App should allow to choose any existing profiles of browsers.

For example, I am using Microsoft Edge on Windows 10. I have multiple profiles (ex. Profile 1, Profile 2, etc.).
Now, I install Requestly Desktop-App.
I see only this item

![image](https://user-images.githubusercontent.com/24372782/220603005-1f171e99-20d2-4bab-bcf0-c160405b2057.png)

I would expect to select Profile 1, Profile 2, etc. and working on that selected profile.

Currently, it's very unconvenient because Requestly always try to create a totally new profile each time start working with it.
My installed extensions and everything I need for daily work are completely removed after closing the browser.

**Comment by wrongsahil** [comment]
Hey @xuan-nguyen-swe . We added support for Existing edge profile in our latest release.

**Comment by xuan-nguyen-swe** [comment]
> Hey @xuan-nguyen-swe . We added support for Existing edge profile in our latest release. 

Cool, thanks for a very fast response and fixing! I will update to the new version soon.
