### ISSUE TITLE
Could not record session, getting error - something went wrong

### ISSUE THREAD

**Issue by lazyvab** [requestly/requestly#321]
Randomly, on clicking `View recording` button in extension popup, a page opens with below error:

<img width="1310" alt="Screenshot 2023-03-01 at 11 20 42 PM" src="https://user-images.githubusercontent.com/6367566/222221374-c3a1f981-a0c2-48cb-9920-d285a5ad490d.png">

**Comment by lazyvab** [comment]
We use `rrweb` library to record sessions. It had a [bug](https://github.com/rrweb-io/rrweb/issues/1090) where the recorder initializes very late in the page load lifecycle if there are few resources in the page that load delayed. 

Meanwhile, if the user clicks `View recording`, no DOM event is captured and therefore session could not be replayed.

**Comment by sachinjain024** [comment]
@lazyvab I guess this is fixed in the v23.3.2? Can we close this ticket?

**Comment by lazyvab** [comment]
Yes, this is fixed in extension `v23.3.3`. Closing the issue.
