### ISSUE TITLE
Need to refresh the page after modifying request/response rule

### ISSUE THREAD

**Issue by wrongsahil** [requestly/requestly#338]
Ideally the rules should work without refreshing the page after activating the rule.

Not many people know about this and those who know sometimes this becomes a blocker because they might be in the middle of a flow where refreshing the page loses the state. 

I think we can solve it easily by message passing to all the tabs to update the rule definitions if the rule definition is changed.

**Comment by lazyvab** [comment]
This has been fixed in extension `v23.3.3`.
Now there is no need to refresh the page if `Modify Request` or `Modify Response` rule is updated or its status is toggled or a new rule is created.
