### ISSUE TITLE
Request type filter on delay network requests

### ISSUE THREAD

**Issue by gzurl** [requestly/requestly#377]
Being able to delay network requests on the client side is very useful!
And especially for AJAX requests.

Quite often, those AJAX GET requests are triggered automatically after a manually triggered POST request.
It would be interesting to apply the delay filter to a certain request type (i.e.: only GET), so the POST request happens immediately and the GET requests can be delayed for debugging purposes.

**Comment by sachinjain024** [comment]
Hey, @gzurl You can actually use the Filter Icon to provide the additional HTTP Method filter.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/3108399/223722439-1c2c65f3-e0af-4978-9450-6c6675afa385.png">

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3108399/223722600-af984743-0fec-4bc2-9b21-817157353a9d.png">

**Comment by gzurl** [comment]
Oops! Thanks!!

I guess I was hoping for a direct combo there :-)

**Comment by sachinjain024** [comment]
Thanks for raising this! We'd think about how can we improve the experience and improve discoverability here.
