### ISSUE TITLE
Connecting existing profile requires browser restart

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#391]
It feels very overwhelming when we have to connect an existing profile with the desktop app as it requires a browser restart. Here's the exact feedback from a user 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3108399/224908907-a45b84ea-f22c-4706-9c36-6d42b1a46613.png">

**Comment by sachinjain024** [comment]
Good news: We've finally started working on this. We will ship this in a week or so.

**Comment by nafees87n** [comment]
This is the new experience where an existing browser profile can be connected using extension. We will ship it by next week.

https://github.com/user-attachments/assets/a128afe4-5b07-40df-87a5-198023c61ba0

**Comment by wrongsahil** [comment]
This is now supported.
https://docs.requestly.com/desktop-app/setup/connect-existing-browser-profile
