### ISSUE TITLE
[desktop_app] [linux] [distribution] Flatpak/Flathub

### ISSUE THREAD

**Issue by RichardFevrier** [requestly/requestly#396]
Hello everyone 👋

Having an `AppImage` is quite nice but having a `flatpak` available trough `Flathub` could be great too 🙂

Thanks for all your work 🙏

**Comment by sagarsoni7** [comment]
Hi @RichardFevrier, glad to know Requestly has been helpful to you.  I'm interested to know what `flatpak` can offer over `AppImage`?

**Comment by RichardFevrier** [comment]
Hi @sagarsoni7, for the end user `Flatpak` brings seemless integration over `AppImage`.
- `Flatpak` can be distributed over the `FlatHub` platform, desktop `App Stores` (Gnome, KDE..) brings this platform to the user and by concequence every app listed there.
- Updates are automatically managed by the app stores too (I know you can install a daemon for `AppImage` to solve that but who does?)
- `Flatpak` also brings better integration with the desktop environment since the user does not have to make the binary executable (yes it is a small step but still) and overall the apps are listed in the apps view with their respective icons, where `AppImages` usually end up in a hidden folder `~/.local/bin`.

Comming from 15 years of macOS you can make a parallel with apps distributed as `.dmg` from a website or from the `App Store`.
At least with `.dmg` you dont need to make extra step (executable) and your `Applications` folder have the real app icon.

To summary it is about discoverability/maintenance (app stores) and integration (desktop environment) and overall remove frictions.
