### ISSUE TITLE
bug: RegEx matching doesn't match due to missing slashes

### ISSUE THREAD

**Issue by SethFalco** [requestly/requestly#426]
### Describe your issue?

When creating a new HTTP rule, one can specify to match URLs with RegEx.

However, no indication is given to users that the RegEx must start and end with a forward-slash (`/`) character.

These are applied automatically on save, however the **Test this Rule** tab can be used without saving. If the user did not manually insert a `/` at the start and end of the RegEx, it will just fail to match everything.

### Repro steps

1. Under HTTP Rules, press **New Rule**.
2. Select something like **Modify Headers**, then press **Create Rule**.
3. Select the dropdown that defaulted to **Contains** and set it to **Matches (RegEx)**.
4. Type `runescape`.
5. Add a random header modification, like `X-UWU: uwu`
6. Press **Test this Rule**
7. Populate the **Request URL** field with `https://runescape.com/` (should match)
8. When you press **Test rule** it will show that headers _have not_ been modified.
9. Manually add a `/` to the start and end of the RegEx.
10. When you press **Test rule** it will show that headers _have_ been modified.

### Expected

One or more of the following should happen:
* When **Match (RegEx)** is selected, automatically inserts slashes.
* When **Test rule** is pressed, automatically inserts slashes.
* When the slashes are not there, display a warning that they are required.
* Alternatively, do not expose slashes in the text field at all and just handle it under-the-hood if they aren't there.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Firefox Nightly 110

### Requestly Version

23.3.3

### Error screenshot

![image](https://user-images.githubusercontent.com/22801583/226678641-af9b80fe-a358-40cd-bd32-da3ee83d2ec6.png)

> The issue, when using RegEx the input expects to have a `/` at the start and end but it's not mandated.

![image](https://user-images.githubusercontent.com/22801583/226678944-2d91124a-280f-4126-8ae4-87e97674223e.png)

> Either by adding the `/` characters manually, or pressing **Create rule** to automatically insert them, the test now performs as expected.

**Comment by sachinjain024** [comment]
Hey @SethFalco, Thanks a lot for creating this issue with the detailed steps 🙏  We will try to solve it this week, at max early next week.

cc - @wrongsahil

**Comment by nafees87n** [comment]
Hey @SethFalco,
Thanks for reporting this. We have deployed the fix. Now while using the `test this rule` feature, the slashes are added automatically. 

Please feel free to log a new for any suggestions you have.
