### ISSUE TITLE
bug: redirect outside of chrome

### ISSUE THREAD

**Issue by MDarroll** [requestly/requestly#442]
### Describe your issue?

I have a QR code that use to redirect to a broken link. I use the redirect tool and now it works perfect in chrome. However it doesnt work anywhere else the extension is not installed. Can anybody now scan qr code and get to my redirect site >? How can i accomplish this ?

### Repro steps

Redirected tool

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

mac

### Requestly Version

new

**Comment by sagarsoni7** [comment]
@MDarroll Redirect you setup in Requestly works for you only - as it is intended for developers for testing.

Want you want is a web proxy that could help you redirect in production. Cloudflare can help here.

[Configuring URL forwarding or redirects with Page Rules](https://developers.cloudflare.com/support/page-rules/configuring-url-forwarding-or-redirects-with-page-rules/)
