### ISSUE TITLE
bug: The iOS system cannot follow the setting HTTP/API rules.

### ISSUE THREAD

**Issue by FantasticDreamtw** [requestly/requestly#447]
### Describe your issue?

Steps:
1. Set the proxy and port and connect the iphone with laptop. (Successful connection)
2. Install a certificate. (It's successful)
3. Turn on the HTTP and API rules I set before.
4. Launch safari and chrome to test the websites.

Observation results:
I connect my iPhone with laptop requestly and test some websites in my iphone system. However, it seems that iOS cannot follow the HTTP and API rules that I set and shows the wrong results.

Other information:
With the same steps and setting, Android phones are always successful but iOS always fails to follow the HTTP/API rules. However, iOS can be successful with Charles and Fiddler. So, there may be a bug in Requestly.io.

### Repro steps

Steps:
1. Set the proxy and port and connect the iphone with laptop. (Successful connection)
2. Install a certificate. (It's successfully)
3. Turn on the HTTP and API rules I set before.
4. Launch safari and chrome to test the websites.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

iOS 15

### Requestly Version

1.4.24

**Comment by FantasticDreamtw** [comment]
Hi,

I don't use mobile data of my iPhone, I use the hostpot wifi signal from my laptop. I turn on the hostpot of my Win 10 laptop and share the hostpot signal with my iPhone, so my iPhone and my laptop are in the same network. I also set proxy and port in the wifi environment . However, iphone cannot get the rules through requestly desktop app. With the same steps, my iPhone can follow and get the rules successfully when I using Charles and Fiddler.

Thanks

**Comment by sagarsoni7** [comment]
Thanks, that was helpful. ` I also set proxy and port in the wifi environment` - this is being set in the iPhone right?

After this setting proxy step,  can you please try opening http://amiusing.requestly.io/ in iPhone Safari? Does it show success or failure? (Note it's `http://` and not `https://`)

**Comment by FantasticDreamtw** [comment]
Hi,

Yes, I set the wifi proxy and port in my iphone instead of the laptop. I also connect the checking http url and the connection is successful. Everything goes well about the precondition setting but fails to get the HTTP rules.

Thanks.

**Comment by sagarsoni7** [comment]
Can we jump over a quick call? calendly[dot]com/requestly/sagar

**Comment by sagarsoni7** [comment]
Can you please try in iPhone Chrome once? Some rules like Redirects work differently

**Comment by FantasticDreamtw** [comment]
I also did the same procedures in iPhone Chrome and it seems that the iPhone still cannot follow the HTTP rules we set. Could you try to add some HTTP rules or modify API responses and use iPhone for the testing? Maybe you can reproduce the same issues.

Thank you.

**Comment by sagarsoni7** [comment]
@FantasticDreamtw - I'm so sorry I missed notification on this issue. Is this still open?
We can get on a quick call to discuss this - https://calendly.com/requestly
