### ISSUE TITLE
bug: modifyResponse is not work on XMLHttpRequest 'loadstart' callback.

### ISSUE THREAD

**Issue by adshield-joon** [requestly/requestly#481]
### Describe your issue?

modifyResponse is not work on XMLHttpRequest 'loadstart' callback.

### Repro steps

1. Create a modify response rule
2. Create xml http request and request loadstart callback - req.addEventListener('loadstart', () => console.log(req.response));
3. send xml http request and check log

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac, Chrome

### Requestly Version

latest

**Comment by lazyvab** [comment]
@adshield-joon The [loadstart](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadstart_event) event is triggered when the request data starts sending to the server. The [readyState](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState) is `1` at this moment.

- When response headers are received, the `readyState` becomes `2`. At this point, you can read response status code.
- When response starts loading, the `readyState` becomes `3`.
- When response is finished loading, the `readyState` becomes `4`. This is the moment when you should actually read the response.

So, ideally an application can read response only when either `readyState` becomes `4` or `load` event is triggered.

Hope this answers your query. Please let me know if we can close the ticket.
