### ISSUE TITLE
bug: modify response does not work in script that inserted in the head

### ISSUE THREAD

**Issue by adshield-joon** [requestly/requestly#482]
### Describe your issue?

modify response does not work in script that inserted in the head

### reason
`window.__REQUESTLY__.responseRulesByUrl` is empty when head script is executed.

### Repro steps

1. create modify response rule
2. insert inline script on head - <head><script>fetch('URL')</script></head>

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac, Chrome

### Requestly Version

latest

**Comment by lazyvab** [comment]
@adshield-joon The extension adds client-side (JS) hooks on `fetch` method to modify API response. But there can always be some delay in attaching those hooks in page and therefore the early `fetch` calls like you mentioned might get missed.

However, you may use our desktop application which can intercept any type of request and modify its response, irrespective of when it is invoked.

Please find the download link [here](https://requestly.io/downloads).

**Comment by wrongsahil** [comment]
Closing this. Feel free to reopen it if you are still facing this
