### ISSUE TITLE
Unable to delete requestly rules

### ISSUE THREAD

**Issue by dannielum** [requestly/requestly#519]
I am getting CORS network errors when trying to delete some requestly rules.

```
Request URL: https://api.june.so/sdk/identify
Request Method: OPTIONS
Status Code: 403 Forbidden
```

```
Request URL: https://api.june.so/sdk/identify
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by sachinjain024** [comment]
Hey @dannielum Is this still an issue?

**Comment by dannielum** [comment]
yes, it is still an issue for me 😞

**Comment by wrongsahil** [comment]
@dannielum I hope this issue is fixed now. Feel free to reopen this if you are still facing it

**Comment by Sanscripter** [comment]
Just ran into this today
