### ISSUE TITLE
bug: unable to load my rules

### ISSUE THREAD

**Issue by dannielum** [requestly/requestly#520]
### Describe your issue?

After successfully uploading some rules, I started to see the error when navigating to the HTTP Rules page.

```
Something went wrong.
Cannot read properties of undefined (reading 'startsWith')
```
The uploaded rules might be corrupted which breaks the parsing of the rules.

### Repro steps

1. Open requestly App
2. Upload rules
3. Successfully uploaded rules
4. Navigate to HTTP Rules
5. Error displayed

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS 13.2.1, Chrome

### Requestly Version

23.4.5

**Comment by sachinjain024** [comment]
@nafees87n Could you please confirm whether this is resolved or not?

**Comment by dannielum** [comment]
yes, thank you!
