### ISSUE TITLE
Display the group status in the rule details view & plugin

### ISSUE THREAD

**Issue by Samiii-AP** [requestly/requestly#547]
In the detail of a rule, if the group it belongs to is disabled, it would be great to mention it somewhere.
Otherwise, you think that the rule is enabled and you waste time searching why you don't have the expected result.

Steps to reproduce:
1. Place a rule in a group
2. Disable the group
3. Go to the details of the rule (typically from the plugin where you don't see the group)
4. Enable the rule if not already enabled

Observed:
1. Nothing mention that the rule will not be applied because of the group status. You think that your rule is enabled

Expected:
1. Something tells you that your rule will not be applied because of the group status.

Note: This "mention" should also be displayed on the plugin to explicitly show that the rule won't apply.

**Comment by wrongsahil** [comment]
@Samiii-AP We've fixed this issue. Now you cannot modify the status of the rule from popup incase the group is deactivated
<img width="545" alt="image" src="https://github.com/requestly/requestly/assets/16779465/90605e34-7ac6-48e0-ac54-49081e54c489">
