### ISSUE TITLE
bug: insert scripts on Firefox is not executed on Slack (Bypass CSP enforced using HTML meta tags)

### ISSUE THREAD

**Issue by SethFalco** [requestly/requestly#549]
### Describe your issue?

I'm using the **← Insert Scripts** rule to inject JavaScript into Slack on Firefox.

In Requestly I can see that the conditions were met, and that the script was injected. I can also see the script in the `<head>` of the document via Inspect Element. Despite scattering `console.log` all over the script, none of the logs are printed under the Console tab.

This script works exactly as intended on Chromium, and I am able to inject scripts on other sites like [Google](https://google.com) on Firefox.

### Repro steps

1. Open the Requestly app
2. Create a new **← Insert Scripts** rule
3. For the condition, use: 
    * `HOST`
    * `Equals`
    * `app.slack.com`
4. For the script settings, use:
    * `Language: JS`
    * `Code Source: CODE`
    * `Insert: After Page Load`
5. Paste the following script (do skim it first!):

<details>
<summary>Click to expand!</summary>

```js
// Site-specific configuration.

/** 
 * Key/value pairs for filtering outgoing transmissions. If any match, the
 * outgoing transmission is dropped.
 * 
 * In each nested array, index 0 represents the property key, and index 1
 * represents the value it must equal to be considered a match.
 * 
 * @type {string[][]}
 */
const FILTER_CONDITIONS = [
  ["type", "user_typing"]
];

// Generic script for blocking outgoing WebSocket messages.

/**
 * The original {@link WebSocket#send} implementation.
 * 
 * @type {function}
 */
const SEND = window.WebSocket.prototype.send;

/**
 * Wrapper around the built-in {@link WebSocket#send} function, but filtering
 * events against {@link FILTER_CONDITIONS}.
 * 
 * @param {string | ArrayBufferLike | Blob | ArrayBufferView} data
 */
function preprocessedSend(data) {
  if (typeof data !== 'string') {
    console.log('Received non-string data, forwarding without check.');
    return SEND.apply(this, [data]);
  }

  try {
    const parsed = JSON.parse(data);

    for (const pair of FILTER_CONDITIONS) {
      if (parsed[pair[0]] === pair[1]) {
        return;
      }
    }

    return SEND.apply(this, [data]);
  } catch (err) {
    if (err instanceof SyntaxError) {
      console.log('Received non-JSON data, forwarding without check.');
      return SEND.apply(this, [data]);
    }

    throw err;
  }
}

window.WebSocket.prototype.send = preprocessedSend;

```

</details>

> The result should be that all outgoing WebSocket messages should go through except `user_typing` which is instead dropped. This results in Slack and other users not getting my typing events. i.e. "Seth is typing…"

![image](https://user-images.githubusercontent.com/22801583/232886008-7e61a7be-fbda-44bb-8bc3-02e59944242b.png)
> My configuration for this rule.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Debian 11, Firefox 112.0 (64-bit)

### Requestly Version

v23.4.5

**Comment by sagarsoni7** [comment]
Thanks @SethFalco for the detailed info.
`app.slack.com` has CSP that prevents execution of inline JS
<img width="1679" alt="Screenshot 2023-04-19 at 1 26 42 AM" src="https://user-images.githubusercontent.com/29792913/232890959-4b7ed665-ce8c-44e6-b6f8-e9ff1f510ecb.png">

**Comment by sagarsoni7** [comment]
<img width="1191" alt="Screenshot 2023-04-19 at 1 29 39 AM" src="https://user-images.githubusercontent.com/29792913/232891597-0fbc0ac4-0186-4820-b89b-0668fbebc6a5.png">

**Comment by SethFalco** [comment]
Ahh, that's my bad. I was under the impression that extensions, bookmarklets, etc could bypass CSP, but I can see other extensions have the same problem on Firefox.

I was exploring if I could do this through a user-script instead, but that isn't going to work either. :thinking: 

Relevant bug on Firefox:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

Interesting reads:
* https://github.com/violentmonkey/violentmonkey/issues/173
* https://github.com/violentmonkey/violentmonkey/issues/1001

Not sure if much can be done here then, or if this should be closed and we can just wait for Mozilla to address it in Firefox, though it's been 7 years already. ^-^'

**Comment by sachinjain024** [comment]
@sagarsoni7 This is very interesting! Good solution, we should update our existing article https://requestly.io/blog/learn-and-bypass-content-security-policy-http-response-header and mention this approach too.

**Comment by sachinjain024** [comment]
@sagarsoni7 @SethFalco -- Just wondering if using the Insert script feature if we remote the meta tag that matches the content-security-policy, does Firefox still apply the CSP restrictions?

**Comment by sagarsoni7** [comment]
@sachinjain024 - No, it doesn't apply restrictions then. ^^ Updated the screenshot with script injection working.

**Comment by sachinjain024** [comment]
@sagarsoni7 Then it should be completely solvable with just the browser extension without the need of using desktop app? Basically, then we can create two blocks (pairs) of scripts

- The First block removes the meta tag
- Second block inserts the actual script

Thoughts?

**Comment by SethFalco** [comment]
> Bypassing CSP is possible for extensions if it is enforced via a HTTP header (since extensions can modify headers).

Right, but what I meant is that the CSP specification dictates this _shouldn't_ be require at all. I'm assuming this is why it works in Chromium for example.

> [Policy](https://www.w3.org/TR/CSP3/#content-security-policy-object) enforced on a resource SHOULD NOT interfere with the operation of user-agent features like addons, extensions, or bookmarklets. These kinds of features generally advance the user’s priority over page authors, as espoused in [[HTML-DESIGN]](https://www.w3.org/TR/CSP3/#biblio-html-design).
> 
> — https://www.w3.org/TR/CSP3/#extensions

> Create a Modify Response Rule which replaces/removes/invalidates Content-Security-Policy meta tag in HTML

If this will be documented anywhere, instead of advising to remove the CSP outright, perhaps it's better to use a regex to replace only the `script-src`, `style-src`, and `default-src` portion of the CSP when and as necessary?

What users do in practice is entirely up to them! But I think a formal article shouldn't specifically advise undermining the browsers built-in security features.

For example, something like the following for scripts:

```js
const CSP = "<meta http-equiv=\"Content-Security-Policy\" content=\"base-uri 'self'; script-src 'none'; object-src 'none';  default-src 'none'\">";
CSP.replace(/\s*(script|default)-src.+?(;|(?="))/g, "");

// Input:  <meta http-equiv="Content-Security-Policy" content="base-uri 'self'; script-src 'none'; object-src 'none';  default-src 'none'">
// Output: <meta http-equiv="Content-Security-Policy" content="base-uri 'self'; object-src 'none';">
```

Even this is a little aggressive. Ideally, all that has to happen is to remove `none` if it's there, and include `unsafe-inline`. This proposal is just to keep it as a one-liner.

> Then it should be completely solvable with just the browser extension without the need of using desktop app? Basically, then we can create two blocks (pairs) of scripts

I would be surprised if this would work tbh. If CSP is blocking scripts, I don't see how one could use a script to remove the meta tag in the first place to execute the next script.

I did do an experiment where I tried to make uBlock Origin remove the CSP through a custom filter:

```
app.slack.com##meta[http-equiv=Content-Security-Policy]
```

However, it wasn't removed at all. Probably because uBlock Origin doesn't remove the actual content from the DOM, so that was a bust.

**Comment by sagarsoni7** [comment]
@sachinjain024 - If you mean to remove meta like with a script injection like
```
function deleteMetaTag() {
  const metaTags = document.getElementsByTagName('meta');

  for (let i = 0; i < metaTags.length; i++) {
    if (metaTags[i].getAttribute('http-equiv') === 'Content-Security-Policy') {
      metaTags[i].parentNode.removeChild(metaTags[i]);
      break;
    }
  }
}

deleteMetaTag();
```

it won't work since even this script won't get executed since CSP is restricting in-line script in OP's case.
I'm yet to see if it works in case CSP is restricting other domains but not in-line scripts.

**Comment by sagarsoni7** [comment]
> If this will be documented anywhere, instead of advising to remove the CSP outright, perhaps it's better to use a regex to replace only the `script-src`, `style-src`, and `default-src` portion of the CSP when and as necessary?

> What users do in practice is entirely up to them! But I think a formal article should try to minimize advising to undermine the browsers built-in security features.

Totally agreed!

**Comment by wrongsahil** [comment]
@Kanishkrawatt @sagarsoni7 How to bypass CSP enforced using HTML meta tag.
