### ISSUE TITLE
[RQ-225] bug: rules get applied when top level domain is `app.requestly.io`

### ISSUE THREAD

**Issue by rohanmathur91** [requestly/requestly#551]
### Describe your issue?

Rules are applied even when top-level domain is `app.request.io` ie on internal domains, which breaks the app.

### Repro steps

Here is the shared test [rule](https://app.requestly.io/rules#sharedList/1681902767357-test)

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

macOS 13.2.1

### Requestly Version

23.4.5

<sub>[RQ-225](https://linear.app/requestly/issue/RQ-225/bug-rules-get-applied-when-top-level-domain-is-apprequestlyio)</sub>

**Comment by lazyvab** [comment]
The fix has been released in extension version `23.4.25`.
