### ISSUE TITLE
disconnected experience in redirect rule for `Pick from Files/Mock server`

### ISSUE THREAD

**Issue by rohanmathur91** [requestly/requestly#552]
### Describe your issue?

Inside the redirect rule editor, when clicking on `Create New` in the mocks modal it navigates to a new window where the user expects that after creating the mock the rule should also get created, but this doesn't happen.

### Repro steps

1. Goto redirect rule editor and choose `Pick from Files/Mock server` and click `Select mock/file`
2. Click on `Create New` which opens new window, and create mock.
3. Goto my-rules page (no rule created)

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

macOS 13.2.1

### Requestly Version

23.4.5

### Error screenshot

https://user-images.githubusercontent.com/61556757/233189609-9c43bcc6-2a87-4a94-b343-f194ca55f8e6.mov

**Comment by wrongsahil** [comment]
This got fixed in https://github.com/requestly/requestly/pull/891
