### ISSUE TITLE
bug: File Disappears on File Server

### ISSUE THREAD

**Issue by roofleDev** [requestly/requestly#554]
### Describe your issue?

My mock file disappeared from the File Server tab.

### Repro steps

Steps to Reproduce:

1. I added a Mock File to the File Server tab
2. I created an HTTP Rule pointing a request to that file
3. The next day, the File Server tab was empty, but I can still see the HTTP Rule pointing to the phantom file

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS 13.1

### Requestly Version

23.4.5

**Comment by sachinjain024** [comment]
Hey, @roofleDev Thanks for creating the ticket. Just to double check, are you logged in to the app?

**Comment by sachinjain024** [comment]
Thanks @roofleDev! Oh great to know it was you over the chat. We will solve the issue in next-to-next week. We are doing a company-wide hackathon for the next two days. I hope this isn't a blocker.

For the moment, if you have the file can you please try creating it again and unblock yourself? We will continue investigation on this.

**Comment by roofleDev** [comment]
Yes, I did create another file to move forward. Cheers to the hackathon!

**Comment by wrongsahil** [comment]
@roofleDev I hope this issue is fixed now. Feel free to reopen it incase you are still facing this

**Comment by roofleDev** [comment]
Yep - thank you!
