### ISSUE TITLE
bug: File upload seems broken in file server

### ISSUE THREAD

**Issue by sachinjain024** [requestly/requestly#555]
### Describe your issue?

When uploaded requestly-web-sdk.js I got the file content as null 

### Repro steps

https://app.requestly.io/sessions/saved/1mwEOo7gTZCfFl67YQrE

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

Latest

### Error screenshot

<img width="888" alt="image" src="https://user-images.githubusercontent.com/3108399/233451955-ae9cd9a1-c322-4e90-b9bb-780e349e67ab.png">

**Comment by wrongsahil** [comment]
This got fixed in this PR https://github.com/requestly/requestly/pull/792
