### ISSUE TITLE
Override status code without changing the response body

### ISSUE THREAD

**Issue by nafees87n** [requestly/requestly#586]
The option to override status code with changing response body is currently not supported with static response.

### Workaround
[Javascript (Dynamic) mode in the response rule](https://docs.requestly.io/browser-extension/chrome/http-modifications/response-rule#programmatic-response-modification) can be used to achieve this which can return the original response body. Here's are the steps

1. Change the mode to Dynamic (Javascript)
2. Change status code according to your usecase
<img width="924" alt="image" src="https://user-images.githubusercontent.com/16779465/236457553-89843ee6-8fe7-4b36-a9bf-a2cbc6964649.png">

**Comment by wrongsahil** [comment]
IMO adding an extra setting in Static Mode will make it more complex. Current workaround works for almost all the cases. So don't see any point in exposing an extra setting just for this
 
 @Kanishkrawatt @sagarsoni7 This can be added as an `How To` in Response Rule
