### ISSUE TITLE
Typo: Shared List modal should have its CTA as "Copy Link" instead of "Copy text"

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#624]
# Issue
When a user creates a shared list the primary action is to copy the link of the Shared List created. The CTA text thus needs to be updated from "Copy text" to "Copy Link".

<img width="1440" alt="copy text shared list modal" src="https://github.com/requestly/requestly/assets/56088056/16921c3f-805b-4f94-96eb-9be5bed2d97f">

# Repro steps
1. Open the Requestly Web app/ Desktop App.
2. Create a test rule. You can also directly import a rule from the [templates](https://app.requestly.io/rules/templates).
3. Click on 'Share button' to start generating a shared list.
4. Click on 'Generate link' button to generate a link to the shared list.
5. Copy the link to shared list and share with your colleagues.

# Occurs on
- Extension
- Desktop-App

**Comment by jayraikhere** [comment]
I want to pickup the issue.

**Comment by echo-sg** [comment]
Hi [jayraikhere](https://github.com/jayraikhere), please go ahead!

**Comment by ncharanaraj** [comment]
Hey, @echo-sg  I noticed that this problem still hasn't been resolved after two weeks. So, I went ahead and fixed the mistake in the code and submitted a pull request.

**Comment by malay5** [comment]
Is the issue fixed? If not, please assign it to me

**Comment by echo-sg** [comment]
The issue has been fixed @malay5. We have some issues which haven't been picked, do check them out!
