### ISSUE TITLE
Remove option to copy cURL from Request pane in Traffic Table

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#626]
### Issue

Remove 'Copy cURL' button from top left of the Request pane in Traffic Table.

<img width="1440" alt="Screenshot 2023-05-18 at 2 11 54 PM" src="https://github.com/requestly/requestly/assets/56088056/f9819476-682e-48ad-9385-449735225355">

### Repro steps

1. Open the Requestly Desktop App.
2. Connect any app from the 'Connect Apps' modal. Traffic interception would start for that particular app.
3. From the traffic table, click on any request to open the request pane

### Occurs on

- Desktop-App

**Comment by echo-sg** [comment]
Related issue #623 {bug: Close button should be on the top right of the request pane in the traffic inspector}

**Comment by vladutvoicu** [comment]
Hello! I would like to work on this issue and #623
