### ISSUE TITLE
As a developer, I'd like to use a Requestly API, so that I can automatically create rules in my shared workspaces

### ISSUE THREAD

**Issue by DavidAtoniqLevine** [requestly/requestly#640]
# Background
We develop JavaScript that our users include on their websites. When we are developing new code, we test our new code on customer websites by using Requestly to block the current production JS on a customer website and replace that with a version in development or test. We share these rules within a team shared workspace so others on our team can test these versions in development too. Some members of the team are in our company, and others work for our customers who want to test out for themselves a new version of our JavaScript before it goes live.

# Integrating Requestly with our build process
We use Github flow to deploy code in branches / main to web servers where they can be included on public websites. Each branch's JS is deployed to a unique URL, so the JS on one branch does not interfer with another. Today, we manually create a Requestly rule in our team workspace to replace the production JS with that branch's unique JS for testing. This is error prone and time consuming. Instead, we would like to use an API from our Github flow code to automate the process of creating this Requestly rule.

**Comment by sachinjain024** [comment]
Thanks @DavidAtoniqLevine for creating this issue. Please allow us a couple of days to discuss this internally and get back to you.

**Comment by wrongsahil** [comment]
Hey @DavidAtoniqLevine . We've starting working on this. This should be available to you by next week :D

**Comment by sachinjain024** [comment]
Hi @DavidAtoniqLevine This feature is now live! 

You can get started quickly with API to configure rules using this doc - https://developers.requestly.io/api/overview/

**Comment by sachinjain024** [comment]
Closing this ticket, happy to give demo for this feature.
