### ISSUE TITLE
Dynamic Query Parameters

### ISSUE THREAD

**Issue by nsrCodes** [requestly/requestly#645]
Being able to write custom logic to add dynamic query parameters.
An example use case is adding the current time stamp in the query parameter. 

This can be done for most cases using the insert script rule with custom code like this: 
[Sample Rule](https://app.requestly.io/rules#sharedList/1685033923537-add-current-ts-as-query-param)
```
const currentUrl = document.URL
console.log('currentUrl', currentUrl)

const url = new URL(currentUrl)

if(!url.searchParams.has('ts')) {
    url.searchParams.append('ts', Date.now())
    window.location = url.href
}
```

But this does not work on requests for serve static content (like JSON, or CSS). In such cases the script rule runs on the parent site, not the requested asset.

**Comment by sachinjain024** [comment]
@nsrCodes We have a pre-defined function called rq_rand(N) that adds N-digit random number. You can use that in Redirects, QueryParams, etc.

However, This might not be possible with MV3 implementation.
