### ISSUE TITLE
Fix: Casing of breadcrumb in Modify API Response rule editor

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#708]
### Issue
In Modify API Response rule editor, breadcrumb has the wrong casing. API is in lower case("api") and should instead be in upper case. 
<img width="1440" alt="Screenshot 2023-06-12 at 1 56 46 PM" src="https://github.com/requestly/requestly/assets/56088056/a49d27c7-8219-419a-a0d6-b19fce02581a">

### Repro Steps
- Open the Requestly Web App [app.requestly.io](http://app.requestly.io/).
- Click on "Create New Rule" and then select "Modify API response" rule to open the editor.

**Comment by ncharanaraj** [comment]
Hi @echo-sg assign this task to me I will fix it.

**Comment by echo-sg** [comment]
Hey @ncharanaraj, assigned this to you!

**Comment by ncharanaraj** [comment]
Hello @echo-sg - I'm not able to run the UI application locally. Can you help me, with how to set it up? 
I am not able to follow the below steps.
![image](https://github.com/requestly/requestly/assets/43924299/ed3594ca-224d-473c-89da-9870aac95e03)

**Comment by nafees87n** [comment]
Hey @ncharanaraj 
What is the exact problem you are facing? Are you able to build the extension?

**Comment by ncharanaraj** [comment]
Yes, I'm not able build the extension.

**Comment by nafees87n** [comment]
@ncharanaraj is there any error being logged?
What is the exact step you are stuck at? What all steps have you completed?

**Comment by alexxuss1996** [comment]
> @ncharanaraj is there any error being logged? What is the exact step you are stuck at? What all steps have you completed?

I experienced similar issues in the past. If you on Windows machine you can't simply write `BROWSER=chrome` or `ENV=local` before `npm` command. It would help if you had Crossenv or similar tool for that.

**Comment by lazyvab** [comment]
@alexxuss1996 Our development team works on MacOS and we have never encountered this issue. Thanks for bringing it to our attention. We will update the build steps to work cross platform.

@ncharanaraj Meanwhile, I found [this](https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows) stackoverflow post with multiple suggestions. Can you please try one of those and unblock yourself?
