### ISSUE TITLE
Naming inconsistency: Export HAR on the sessions screen

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#728]
### Issue
We have a feature which lets the user download a HAR capture for their traffic session. We call this "Download HAR" at all other places. Only here we have "Export as HAR"(top right). This needs to be changed to "Download HAR".
![image](https://github.com/requestly/requestly/assets/56088056/4ae77572-7745-4512-9230-7e0da0096af6)

### Repro steps
- Download Requestly's [Desktop App](https://requestly.io/desktop).
- The issue is in session viewer, so you need a session to work on the issue.
- Connect an app to start intercepting traffic. Click on "Save Session" on the top right.
- Navigate on the "Sessions" tab from the sidebar and open the session.

**Comment by lazyvab** [comment]
Merged the PR. Closing the issue.
