### ISSUE TITLE
Grouping support in Mock Server

### ISSUE THREAD

**Issue by fangleW** [requestly/requestly#729]
It is recommended that the mock server add a grouping function. 

In addition, the current http rules grouping function is not easy to use. Can drag and drop be supported? #971

**Comment by echo-sg** [comment]
Hey @fangleW
This is Shrey from the product team. Thanks for your feedback. 
We have logged this in our roadmap, will keep you posted!

**Comment by rohanmathur91** [comment]
@fangleW We have added collection support for mocks https://github.com/requestly/requestly/pull/1634 so closing this issue. For drag and drop support refer https://github.com/requestly/requestly/issues/971
