### ISSUE TITLE
Change label text from "Choose Password" to "Password"

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#755]
### Issue
Change label text from "Choose Password" to "Password".
<img width="1440" alt="Screenshot 2023-06-20 at 9 12 52 PM" src="https://github.com/requestly/requestly/assets/56088056/de04547b-3c2b-4500-aeb1-a7039b07f842">

### Repro steps
- Open [Requestly's Web App](https://app.requestly.io).
- Click on Signup Button on the top right.

**Comment by itspunkaj** [comment]
hey i want to contribute to this

**Comment by itspunkaj** [comment]
can you elaborate how shoul i proceed?

**Comment by echo-sg** [comment]
Hey @itspunkaj, assigning this to you. Please refer our [Contributing guidelines](https://github.com/requestly/requestly/blob/master/CONTRIBUTING.md) to get started.

**Comment by itspunkaj** [comment]
hey @echo-sg i have sent a PR let me know if there is an issue

**Comment by lazyvab** [comment]
Thanks @itspunkaj for your contribution. Merged the PR and deployed the change.
