### ISSUE TITLE
Rule name should be an HTML link

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#770]
### Issue
When you are on the Rules list page, the name of rules appear as links. But you cannot open a rule in new tab using Cmd+click or right-click and Open Link in New Tab.
<img width="1440" alt="Screenshot 2023-06-23 at 11 08 45 AM" src="https://github.com/requestly/requestly/assets/56088056/6a6c0d56-3f99-4653-a6cd-afdfcccf30ca">

### Repro steps
- Open Requestly's [Web App](https://app.requestly.io/).
- Create a rule if there aren't any.
- Open the [rules list page](https://app.requestly.io/rules/my-rules).

### Related issue
#305

**Comment by ncharanaraj** [comment]
Hello, @echo-sg I will add target='_blank' and href="/#" to the rules anchor tag. Can you assign me this task?

**Comment by sachinjain024** [comment]
Hey @ncharanaraj Any luck here?

**Comment by ncharanaraj** [comment]
Hello, @sachinjain024 I figured it out and I'm requesting for review now.

**Comment by lazyvab** [comment]
@ncharanaraj I checked your pull request and it does not meet the expectation. Do you want to give another try?

**Comment by ncharanaraj** [comment]
@lazyvab I'll try

**Comment by ncharanaraj** [comment]
@lazyvab Path has been updated

**Comment by waheedshams** [comment]
hi can i work on this?

**Comment by echo-sg** [comment]
@waheedshams can you pick this issue?

**Comment by wwzeng1** [comment]
Hey @echo-sg! I can take this one :)

**Comment by Nischalj10** [comment]
Hey @echo-sg, if this is done, can you mark this as closed?

**Comment by wrongsahil** [comment]
This is not yet completed. Reopening this

**Comment by ncharanaraj** [comment]
Hello Team,

I apologize for the delay in my response. I have implemented the required changes, and I've tested them locally. Everything seems to be working perfectly, including the ability to open links in a new tab using the "cmd/ctrl + click" and the right-click context menu.

You can watch a video clip demonstrating this functionality here: [Video Link](https://clipchamp.com/watch/93vl0G7oFm5)

I would appreciate it if @wrongsahil and @sachinjain024  could review the changes. Once I receive their feedback, I'll proceed with creating a pull request.

Please let me know. 

Thank you!.

**Comment by DoyeDesigns** [comment]
Hello @echo-sg , have this issue been solved? I’d like to work on it.

**Comment by echo-sg** [comment]
@DoyeDesigns this is solved, can you please check our other [open issues](https://github.com/requestly/requestly/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for contribution.
