### ISSUE TITLE
Bug: Chrome Extension freezes on load

### ISSUE THREAD

**Issue by digitalmaster** [requestly/requestly#771]
### Describe your issue?

Whenever i open the app from the chrome extension it just freezes. 

### Repro steps

Repro Steps:
1. Click on the requesttly icon
2. Click open in app

**Expectation:** Opens app allowing me to make changes
**Result:** Freezes

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Ventura 13.4.1, Chrome

### Requestly Version

v23.6.23

### Error screenshot

https://github.com/requestly/requestly/assets/1279335/1054b481-9925-4a25-bc0c-0a2a12f35374

**Comment by digitalmaster** [comment]
Update: I removed and reinstall the extension and now the issue is gone 🤷‍♂️ Closing for now.

**Comment by sachinjain024** [comment]
Thanks @digitalmaster for logging this issue. Please keep us informed if this happens again.
