### ISSUE TITLE
bug: very slow app

### ISSUE THREAD

**Issue by Harikrishnan-Prabhakar** [requestly/requestly#826]
### Describe your issue?

When clicking on the chrome extension, it loads very slow.

### Repro steps

Click on the extension
Click on open app.
Keeps on loading for few minutes before showing the api's. 

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac 13.4

### Requestly Version

v23.7.10

**Comment by wrongsahil** [comment]
@Harikrishnan-Prabhakar Thanks for reporting this issue. We currently are working on improvements which will boost up the speed of app.

**Comment by wrongsahil** [comment]
Hey @Harikrishnan-Prabhakar . We've shipped some major performance updates this week. Would be awesome if you can give it another try.

Closing this issue for now. Feel free to open this again if you are still facing this issue
