### ISSUE TITLE
Add url encoding to url replacer

### ISSUE THREAD

**Issue by Dragon-0609** [requestly/requestly#836]
Hello. I need url encoding of current url in the url replacer.

For example, I have:
`https://something.com/lorem?s=ipsum&token=123`

I want to replace `something.com/` to `another.com/try?text=`, so I in the end I could get `https://another.com/try?text=lorem?s=ipsum&token=123`. 

The problem is that the GET parameters from `something.com` are sent to `another.com`. I don't want it. I want it pass like it's.

In the end I want to get this url: `https://another.com/try?text=lorem%3Fs%3Dipsum%26token%3D123`

**Comment by wrongsahil** [comment]
@Dragon-0609 You could use `wildcard operator` along with `rq_encode` inbuilt method in Redirect Rule to achieve this.

<img width="848" alt="image" src="https://github.com/requestly/requestly/assets/16779465/291e570e-2209-416d-a231-633066070979">

Here's the Shared List for Same
https://app.requestly.io/rules#sharedList/1689271718164-rq-encode-and-wildcard-usage

**Comment by Dragon-0609** [comment]
Thanks. It's what I wanted.
