### ISSUE TITLE
bug: CSS Colour Picker Overflow in monaco editor

### ISSUE THREAD

**Issue by Calculamatrise** [requestly/requestly#845]
### Describe your issue?

The z-index for the colour picker overlay in the CSS language editor overflows and is cut-off.

### Repro steps

1. Open Requestly app
2. Create a rule
3. Set language to CSS
4. Set a colour for HTML background
5. Hover over colour value

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome Version 114.0.5735.199 (Official Build) (64-bit)

### Requestly Version

v23.7.12

### Error screenshot

![image](https://github.com/requestly/requestly/assets/51772836/eaedf4a0-69c7-426c-85c7-16e7bf748166)

**Comment by wrongsahil** [comment]
We've replaced monaco editor with codemirror. This shouldn't be happening now
PR: https://github.com/requestly/requestly/pull/1774
