### ISSUE TITLE
bug: high cpu & ram usage, and most request previews are not displayed properly in desktop app

### ISSUE THREAD

**Issue by spinfal** [requestly/requestly#858]
### Describe your issue?

When connected system-wide, I run into constant app freezes and high CPU/RAM usage. Not only this, but almost every request I try to view has malformed or improperly displayed Preview content (see images)

I have also reinstalled Requestly, with no luck.

### Repro steps

1. Use the app with system-wide enabled
2. Visit a website in a browser
3. Click around on different requests
   - At this point, you may start to see performance issues
4. Click a request, such as one with .json
5. View the "Preview" section

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11 (22H2, build 22621.1992), Opera One (version: 100.0.4815.76)

### Requestly Version

1.5.7 (recently updated to 1.5.8, still experiencing this issue)

### Error screenshot
![High CPU and RAM usage](https://github.com/requestly/requestly/assets/65109978/0fd1e66d-8f74-4b81-bfa2-d44af1bb5bbb)
![Incorrect response](https://github.com/requestly/requestly/assets/65109978/3ea032f7-7835-469b-b5be-688158e1a8ea)
![Proper response](https://github.com/requestly/requestly/assets/65109978/71df39fb-20eb-4604-aac5-5e85fa4d7c68)

**Comment by sachinjain024** [comment]
Hey @spinfal Thanks for reporting the issue. We've shipped some major performance related changes this week. Could you please upgrade to latest build and try again?

**Comment by wrongsahil** [comment]
Hey @spinfal . We've fixed the Preview issue as well the app performance issue. Closing this issue for now. Feel free to open it again if you face the issue again
