### ISSUE TITLE
Hope to support m1 chip as soon as possible, the application should be arm structure

### ISSUE THREAD

**Issue by beergold** [requestly/requestly#860]
although it can work on m1, the architecture is x86 instead of arm, so the rosetta needs to work, causing the application to load very Catton, hoping to adapt as soon as possible.

**Comment by echo-sg** [comment]
Hey @beergold, we already have this in our roadmap and will pick this soon. I'll keep you posted with the updates.

**Comment by nsrCodes** [comment]
starting from [release v1.5.9](https://github.com/requestly/requestly-desktop-app/releases/tag/v1.5.9) we will be shipping both an x86 and arm build. Your app should automatically update to the correct build type (Regardless of what you initially installed).

Thanks for pointing this out @beergold
