### ISSUE TITLE
bug: Secure websockets are broken

### ISSUE THREAD

**Issue by medzhidov** [requestly/requestly#908]
### Describe your issue?

MacOS app does not provide real proxy for wss or does not skip it, but create a fake wss connection that does not work. For example, that is my two websocket without requestly (first is always finished after connection because it is not working address, second wss is localhost webpack HMR):
https://cln.sh/VHfmNKxL

That is hot it is working with requestly dmg app:
https://cln.sh/MhCtYgG3

With requestly it is does not sent any messages and keep connections that cannot be estabilish because address is invalid

### Repro steps

1. Open requestly
2. Go to Connect Apps
3. Select Chrome (existing profile)
4. Open any page with ws connection

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS Ventura 13.5 (22G74)

### Requestly Version

v1.5.8

**Comment by nsrCodes** [comment]
This is similar to https://github.com/requestly/requestly/issues/232 for which a fix has already been released.

@medzhidov Can you share the bundler being used for the live dev setup?

If you can provide the code you are running (or even a dummy copy of it) to reproduce this, it will make it much easier to debug this

**Comment by medzhidov** [comment]
@nsrCodes 
Just check this url under proxy: https://libwebsockets.org/testserver/

https://cln.sh/LVt5tv6L
