### ISSUE TITLE
bug: Cannot read properties of undefined (reading 'accounts')

### ISSUE THREAD

**Issue by Suiram1701** [requestly/requestly#939]
### Describe your issue?

Whenever I try to open Requestly as a browser extension, I get the message "Unexpected application error!". I also tried reinstalling it but it doesn't work either.

### Repro steps

1. Install it from the chrome webstore
2. Open "app.requestly.io"
3. Getting the error

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11, Chrome 115.0.5790.171

### Requestly Version

23.8.8

### Error screenshot

![requestly_error](https://github.com/requestly/requestly/assets/110390261/db3f09df-0d77-4831-9205-4d35deeb943f)

**Comment by wrongsahil** [comment]
Hey @Suiram1701 . We are looking into this issue. Will let you know once this is fixed

**Comment by Suiram1701** [comment]
It worked, thanks for help.
