### ISSUE TITLE
[CX-85] Indicator to show number of rules are enabled in a group

### ISSUE THREAD

**Issue by Balasundararao** [requestly/requestly#956]
I have bunch of groups and each has multiple rules. i m not sure which one is enabled.  Cant go to each group and verify  or by mistake rule is enabled  by default that is not needed.     Its possible to show how many rules are  enabled  to identify it?

<sub>[CX-85](https://linear.app/requestly/issue/CX-85/indicator-to-show-number-of-rules-are-enabled-in-a-group)</sub>

**Comment by wrongsahil** [comment]
Hi @Balasundararao. This looks like a great feedback. We'll prioritise this in the upcoming week.

**Comment by sachinjain024** [comment]
@echo-sg Can we take this up as a part of our Rules List filter experience change?

**Comment by wrongsahil** [comment]
Hey @Balasundararao. This is now supported in Requestly. Thanks for opening this issue :D
