### ISSUE TITLE
Bug: Async XHR Response

### ISSUE THREAD

**Issue by anlinguist** [requestly/requestly#960]
### Describe your issue?

The XHR monkey patch doesn't seem to work asynchronously. The entire asynchronous logic does run (e.g. I get a log after the asynchronous logic runs), but the app receives the response from the XHR request before the async logic complete.

### Repro steps

1. Open the requestly app. 
2. Create a response rule for an XHR request. e.g.:
```
async function modifyResponse(args) {
  const {method, url, response, responseType, requestHeaders, requestData, responseJSON} = args;
  let resp = response
  try {
    resp = JSON.parse(response);
  } catch (e) {
    return resp
  }
  
  // run async logic and modify the resp
  await new Promise(resolve => setTimeout(resolve, 3000));
  resp["test"] = "abc"

  console.log(resp)
  return resp
}
```
3. Try it out. The app that makes the request will not see the "test" value inside the response object. You'll see the log with the resp data, but the app receives the resp data before it can be modified.

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS, Chrome 115

### Requestly Version

v23.8.12

**Comment by anlinguist** [comment]
@wrongsahil any ideas on this? Async fetch works no problem but I can't get async xhr to work properly.

**Comment by wrongsahil** [comment]
Hey @anlinguist. Sorry for the delay in response. Currently, we only support async code in requests triggered using fetch. XHR isn’t supported at the moment.

We're discussing and testing a potential solution to enable support for XHR as well. We'll keep you posted on any developments.

**Comment by anlinguist** [comment]
hey, thanks for getting back to me @wrongsahil. For my purposes, I was able to proxy and monkey patch XHR to allow async operations on the XHR response data. 

In short, my approach pauses the original XHR request before it is sent, creates and runs a fetch request from it, takes the fetch request response and freely applies async operations on it, resumes the original XHR request, and overrides the XHR response using the now available response from the fetch operation. Here's how I did it:

1. Save a reference to the original XMLHttpRequest object and its methods (send, open, setRequestHeader).
2. Override the global XMLHttpRequest object with a custom constructor function.
3. Inside the custom constructor, capture the request details (URL, method, headers) by overriding the open and setRequestHeader methods and storing them in a requestDetails object.
4. Override the send method to defer sending the request. It attempts to retrieve a response rule based on the request URL, request data, and method.
5. If a response rule is found, it enters an async logic; otherwise, it sends the request as-is.
6. In the async logic, a separate fetch request is made to the original URL using the captured request details. The response is then modified based on the response rule's modification function, if specified.
7. The modified response is stored in a responseOverrides object, and getters are defined for the response, responseText, status, and statusText properties of the xhr object to return the modified response.
8. Finally, the original send method is called to resume the original XHR request, but with the overridden response properties returning the modified response to the caller.

Of course, this approach does make an extra request to the original URL in order to fetch and modify the response data. This additional request may have performance implications, especially if the response modifications are extensive or if there are a large number of XHR requests being intercepted. For my purposes, this is acceptable.

**Comment by lazyvab** [comment]
@anlinguist If API request is not idempotent in nature, firing it multiple times may lead to unexpected results. For instance, a POST request which creates new data on server may create it multiple times.

**Comment by anlinguist** [comment]
Yes, that's true, so for many usecases, it may not be an ideal solution. If the request you're targeting is an XHR and ends up creating/updating/deleting data on a server, this would not be an ideal approach.

However, if the request you're targeting is for obtaining data from a server, it works. For my purposes, this was an acceptable workaround - I have rules around which XHR requests duplicate the request using the fetch request approach, and all of my rules really focus on getting data from the server rather than posting/putting/deleting/etc.

Due to the synchronous nature of XHR's readystatechange, I could not figure out another way to perform asynchronous logic directly on the XHR request.

**Comment by anlinguist** [comment]
To further reduce the risk of accidentally applying this double request approach to xhr requests that are not idempotent, I added a new flag in the rules themselves which explicitly sets XHR logic to be async. If this flag is not set to true in the rule itself, it will use the synchronous logic instead.

**Comment by wrongsahil** [comment]
Hey @anlinguist. Great news! 🎉 The new extension version 24.5.8 is now available in the Chrome Extension Store. You can now use async with XHR requests too! :D

Thank you so much for helping us implement this feature.
