### ISSUE TITLE
Enforce HTTP Header Character Casing

### ISSUE THREAD

**Issue by sagarsoni7** [requestly/requestly#969]
Is there a way to enforce the character casing of request headers? Eg: X-MY-KEY seems to be sent as X-My-Key.

**Comment by wrongsahil** [comment]
Test

**Comment by DarkWolff71** [comment]
@sagarsoni7 
Since the header field names are case-insensitive, it is just Chrome's way of displaying the first letter as capital. Currently, there is no way to modify that in the developer tools.
